### ISSUE TITLE
RE3 Crashing - won't hook?

### ISSUE THREAD

**Issue by antispamtutoruser123** [praydog/REFramework#100]
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/7797562/re2_framework_log.txt)
I'm on a bit of a non standard setup.  I remote desktop into my PC from my macbook.  PC doesn't have a display.  Then I'm playing VR wirelessly using Vridge.  Headset Vive Flow.

Non standard setup. Sorry!

**Comment by antispamtutoruser123** [comment]
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/7797602/re2_framework_log.txt)

Here's another log file.  I disabled all overlays.  Disabled Steam theater.  And launched the game from the Steam desktop window.

Game never loads into VR but the desktop version is showing the setup menu and it's running at about 2fps.

**Comment by antispamtutoruser123** [comment]
It's not crashing anymore.  Just failing to launch into VR.  So the crashing might have had something to do with overlays I had running.

**Comment by nickyb78** [comment]
Mine isnt loading into headset either. Im just stuck in the steam vr loading screen. I can see the game on my desktop though. Iv disabled all overlays and using dx11.

**Comment by antispamtutoruser123** [comment]
I just tested RE7 and that's working great so at least it doesn't appear to be my setup.  Something wrong with RE3

**Comment by anzbert** [comment]
same here. i am stuck in the steamVR space with the game sound and can only see the game on the monitor

**Comment by nickyb78** [comment]
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/7797979/re2_framework_log.txt)

**Comment by nickyb78** [comment]
Resident evil 2 is the same. Wont load into headset. Iv posted my log text for resident evil 3 if that helps.

**Comment by ianwitherow** [comment]
Same here - VR view just shows SteamVR, but the game is running and the camera moves with the headset.

Oculus AirLink with Quest 2 on Windows 10. Let me know if there's any other information that would help.

![image](https://user-images.githubusercontent.com/1964272/147859500-b91b8e22-43a2-4f31-832f-f02417a95827.png)

**Comment by anzbert** [comment]
try this: https://www.reddit.com/r/AnthemTheGame/comments/ar5b8b/psa_workaround_to_disable_hdr_on_nvidia_cards/

or unplug your monitor. i think its an issue with HDR screens

**Comment by ianwitherow** [comment]
> try this: https://www.reddit.com/r/AnthemTheGame/comments/ar5b8b/psa_workaround_to_disable_hdr_on_nvidia_cards/
> 
> or unplug your monitor. i think its an issue with HDR screens

That worked! Thanks!

**Comment by nickyb78** [comment]
That worked for me. For some reason my gun wont shoot. Im pressing triggers on oculus controlers but nothing happens. All other controls work

**Comment by anzbert** [comment]
you need to hold the grip button and then the trigger will work

**Comment by nickyb78** [comment]
That worked. I feel stupid now ha thanks

**Comment by antispamtutoruser123** [comment]
Solved it.  DX12 is not working.   in re_config.ini change DX12 to DX11 and it works perfectly now.
