### ISSUE TITLE
MHR Crashing Quickly With Mods Installed

### ISSUE THREAD

**Issue by UltimitCuest** [praydog/REFramework#1003]
**Describe the bug**
Installed reframework along with custom UI and better matchmaking for monster hunter rise. Game is randomly crashing within a minute or two of opening the game. It often crashes right as I load up a character, but also sometime crashes after I get to run around the hub for a few seconds. Sometimes it crashes early, while im browsing the main menu.  With either mod I have installed it crashes at about the same spot. With reframework and no mods it either crashes right upon startup or does not crash at all. Attached are the logs of a recent crash. Before installing the mods and reframework manually, i did try to install them through nexusmods vortex, although it didn't work.

**Upload logs and any crash dumps**
[Uploading re2_framework_log.txt…]()
[reframework_crash.dmp](https://github.com/praydog/REFramework/files/14553216/reframework_crash.dmp)

**Identify the REFramework version**
REFramework-26-1-617-1707054287

**To Reproduce**
1. Opening game
2. Loading a character

**Expected behavior**
game work

**Desktop and VR (please complete the following information):**
 - OS (Windows 10
 - NVIDIA GeForce GTX 1070
 - Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz   3.19 GHz

**Steam Deck/Linux (please complete the following information):**
 - N/A

**Virtual Reality (please complete the following information):**
 - N/A

**Additional context**
uh

**Comment by praydog** [comment]
You didn't upload your log.

**Comment by praydog** [comment]
And what other mod are you using? There's a separate mod you have installed that seems to be causing the issues, not REFramework according to the crash dump.

**Comment by praydog** [comment]
According to the dump, there are two possibilities here:

1. You are using an REFramework plugin that is unstable, and not properly using REFramework's API and instead opting for an external solution
2. You are using some external overlay software that is using an unstable hooking method

**Comment by praydog** [comment]
Disable medal.tv, it just crashes with REFramework.
