### ISSUE TITLE
Dragon's Dogma 2 Character Creator - Menu not showing

### ISSUE THREAD

**Issue by LeonNamowitz** [praydog/REFramework#1004]
**Describe the bug**
The menu is not rendering. It sometimes flickers quickly at startup but then vanishes. Pressing the menu key **does** bring up the cursor but still no menu. 

**Upload logs and any crash dumps**
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/14570168/re2_framework_log.txt)

**Identify the REFramework version**
Github developer build e1a13a6 (Nightly 629)

**To Reproduce**
1. Open the game.
2. Press the menu key.
3. Notice the cursor appearing, but no menu.

**Expected behavior**
The menu showing up.

**Desktop and VR (please complete the following information):**
 - OS:   Win 10
 - GPU: RTX 4080
 - CPU: i5 12600kf

**Additional context**
I've tried reinstalling, disabling every type of other overlay (Nvidia, Steam), clearing shader cache, but nothing helped.

These are the latest errors the log gives:

[error] [D3D12] Failed to get back buffer for rtv.
[error] Present failed: 87a0001

**Comment by praydog** [comment]
Try the newest nightly and report back: https://github.com/praydog/REFramework-nightly/releases/

**Comment by LeonNamowitz** [comment]
Sadly no improvement, behaves pretty much exactly like before. 

New logs: 
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/14591087/re2_framework_log.txt)
[excerpt of other errors](https://gist.github.com/LeonNamowitz/b3d98f09c2a72f27812d15fd31854f66)

I swear the log looks different every time. Sometimes it only includes the "present failed: 87a0001" error, sometimes no errors at all and sometimes a 60MB monstrosity I can't even upload.
[short video of some flickering](https://streamable.com/4oi1pc) (game always starts in this window for me and then switches to fullscreen)

Not sure what else I can do to help with this.

**Comment by praydog** [comment]
Download nightly again and upload logs https://github.com/praydog/REFramework-nightly/releases/

It won't fix anything but should give me more context and if I should rule out third party software causing conflicts.

**Comment by LeonNamowitz** [comment]
Literally just did (Nightly 641). I don't see any obvious errors but I've had that before as well.
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/14592960/re2_framework_log.txt)

The menu flickers and disappears when the game fullscreens. For context I have the Nvidia overlay and Steam overlay disabled. No Afterburner running either.

**Comment by praydog** [comment]
OH. I know what it is. It's DLSS3... I think. It's inserting fake present calls, confusing REFramework. I have Hardware Accelerated GPU Scheduling turned off, so DLSS3 was not auto-activating for me so I couldn't see the issue.

**Comment by LeonNamowitz** [comment]
I'm getting mixed feelings here now, I just had it work once by randomly changing things but can't reproduce.
Shouldn't deleting the framegen DLL stop it from engaging? Because that doesn't change a thing.

**Comment by LeonNamowitz** [comment]
Yeah nvm that's it, you're a genius. Restarting without GPU Scheduling and the menu renders flawlessly. 
So weird because you can't change any settings in this demo.

Good luck fixing it though ^^

**Comment by praydog** [comment]
Fixed in e206942355177d0c7a6ca0f294acd55c8e26169e
