### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by datboi1234567** [praydog/REFramework#1006]
It was working just fine then started crashing as the mod menu started to initialize the mod
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/14589996/re2_framework_log.txt)
[reframework_crash.dmp](https://github.com/praydog/REFramework/files/14589999/reframework_crash.dmp)

I am running the most recent version which is 1.53 I think

I am running windows 11, a RTX 4060, and an i7 as a CPU along with a metaquest 3 headset

**Comment by praydog** [comment]
1. Disable medal.tv
2. Make sure you are using the correct version of RE7 mod for your game. If you are using the very latest version of RE7, you need to use the "RE7.zip". If you are using the old, pre-RT version, you must use RE7_TDB49.zip

**Comment by praydog** [comment]
I've pinned down a crash to the medal.tv software. It's just not compatible with REFramework.
