### ISSUE TITLE
RE7 Extreme artifacts and ghosting 

### ISSUE THREAD

**Issue by unleashed7** [praydog/REFramework#1007]
I tried everything I could think of to solve this, I can't imagine this being normal, or is it?

https://github.com/praydog/REFramework/assets/49449100/09ede8b0-7ff4-4192-8c97-eb6907a5a06f

Showing on the video in order:
- Shadows popping in and out of existence
- Lights flickering (similar to enabling Disable Temporal Fix)
- Hands/body leaving long ghost trails
- Double reflection image of the gate, turning with the camera
- Strong ghost image of both hands on the outside
- Settings I use
- Headset on/off (this to show that the path and house is barely visible in VR due to unexplained darkness)

Things I tried:
1. Latest nightly (641) and stable (1.5.3) builds (both non-TDB)
2. OpenXR and OpenVR
3. Every combination of in-game setting
4. Every setting in REFramework
5. GPU scheduling on/off
6. Reinstalling game/framework

I didn't try the non-RT build yet, but the RT version is supported and couldn't find anyone else having this issue, so assuming it must be a bug. Even in [this random YT gameplay](https://www.youtube.com/live/9sMrpfJ2Mgc?si=DJUZmJsYPPxkQjyv&t=273), the gate is correctly mirrored in the reflection (I think, as it's hard to see) while for me there's missing/incorrect reflection.

Setup:
- Quest 3
- RTX 4090
- i5 13600k

**Comment by praydog** [comment]
Turn ray tracing off

**Comment by praydog** [comment]
You can try one of the pd-upscaler builds here if you want to even attempt to actually leave ray tracing on: https://github.com/praydog/REFramework/actions

But it might not actually fix anything other than TAA. I'm not trying to fix the Ray Tracing option.

**Comment by unleashed7** [comment]
> You can try one of the pd-upscaler builds here if you want to even attempt to actually leave ray tracing on: https://github.com/praydog/REFramework/actions
> 
> But it might not actually fix anything other than TAA. I'm not trying to fix the Ray Tracing option.

Oh, I thought something's wrong on my end, I saw some videos that you were quick to make the mod compatible with the RTX version back when it came out, I assume that was mostly for compatibility with the DX12 version then? But if it's not meant to run well like this, then I'll just give it up. Thanks!

**Comment by praydog** [comment]
The RT version works fine. Just not with the actual Ray Tracing option enabled.
