### ISSUE TITLE
DD2 - Crash on REFramework initialization - Nightly 673

### ISSUE THREAD

**Issue by thesilentw** [praydog/REFramework#1011]
**Describe the bug**
Crash just after the CAPCOM logo with REFramework installed. Crash does not occur without REFramework.

**Identify the REFramework version**
Reproduced on REF Nightly 673 (5154ccb055b694674694b79806ed356374084e60)

**To Reproduce**
1. Install REFramework (no VR options)
2. Start DD2
3. Observe crash

**Desktop Hardware:**
 - Windows 10
 - Radeon RX 6750 XT
 - AMD Ryzen 9 5900X

[reframework_crash.dmp](https://github.com/praydog/REFramework/files/14734110/reframework_crash.dmp)
[reframework_revision.txt](https://github.com/praydog/REFramework/files/14734111/reframework_revision.txt)

**Comment by praydog** [comment]
Merging with issue #1010
