### ISSUE TITLE
[DD2] DLSS disabled with latests commits

### ISSUE THREAD

**Issue by kawo** [praydog/REFramework#1022]
**Describe the bug**
Since commit https://github.com/praydog/REFramework/commit/dd2b7c4b944467d64e7bd9d20972ea6e0c6a5228 and so on 'til https://github.com/praydog/REFramework/commit/5f95146508a2e871adfdb65bf8513321fd27140c DLSS is totaly disabled in DD2 (show greyed out ingame).

**Upload logs and any crash dumps**
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/14857877/re2_framework_log.txt)

**Identify the REFramework version**
Since https://github.com/praydog/REFramework/commit/dd2b7c4b944467d64e7bd9d20972ea6e0c6a5228 to https://github.com/praydog/REFramework/commit/5f95146508a2e871adfdb65bf8513321fd27140c

**To Reproduce**
1. Download nightly build (or Nightly 763 on Nexus) and extract dinput8.dll to main folder
2. Launch the game
3. DLSS settings are greyed out and not working

**Expected behavior**
DLSS working

**Screenshots**
![2054970_20240403215643_1](https://github.com/praydog/REFramework/assets/548404/073c8521-245c-4bd7-915c-341d8e3fe231)

**Desktop and VR (please complete the following information):**
 - Windows 11
 - RTX 3080
 - Core i7 13700KF

**Additional context**
Tryed deleting shader cache, REF config, _storage_ folder but the issue still appear.
Also noted that in _storage_, only sl.interposer.dll is here (before, all streamline files + nvngx_dlss was there).

**Comment by praydog** [comment]
Figured out the issue. A new build will be pushed shortly.

**Comment by praydog** [comment]
Fixed in 3a72ddaf8b4ade7c6ad9427d3bcbeabaa9c08f3d
