### ISSUE TITLE
Crashing with REF 780

### ISSUE THREAD

**Issue by Storm4195** [praydog/REFramework#1024]
**Describe the bug**
A clear and concise description of what the bug is. If the bug only started to happen after a certain REFramework update, let us know which version the bug appeared in.
I kept crashing so I reinstalled REF and only used one mod, still crashed. Works fine when I uninstall REF

**Upload logs and any crash [reframework_crash.dmp](https://github.com/praydog/REFramework/files/14877474/reframework_crash.dmp)
Locate the `re2_framework_log.txt` in your game directory and upload it along with the issue.
If you crashed, upload the `reframework_crash.dmp` file as well.

**Identify the REFramework version** 
If the REFramework version or commit hash is known, submit this information. 
I'm on the latest 780 build

**To Reproduce**
1. have any mod using REF installed
2. launch with REF
3. See the crash

**Expected behavior**
I expected game to run.

**Screenshots**
None

**Desktop and VR (please complete the following information):**
 - Windows 11
 - RTX 3080ti
 - i5-12400f

**Steam Deck/Linux (please complete the following information):**
 - Proton version

**Virtual Reality (please complete the following information):**
 - Headset model
 - Runtime (OpenVR or OpenXR)

**Additional context**

**Comment by praydog** [comment]
Disable Medal.tv, this is causing the crashes.
