### ISSUE TITLE
Crash at start up

### ISSUE THREAD

**Issue by Kaosangel** [praydog/REFramework#1025]
**Describe the bug**
A clear and concise description of what the bug is. If the bug only started to happen after a certain REFramework update, let us know which version the bug appeared in.

**Upload logs and any crash dumps**
Locate the `re2_framework_log.txt` in your game directory and upload it along with the issue.
If you crashed, upload the `reframework_crash.dmp` file as well.

**Identify the REFramework version**
If the REFramework version or commit hash is known, submit this information.

**To Reproduce**

[re2_framework_log.txt](https://github.com/praydog/REFramework/files/14879397/re2_framework_log.txt)
[reframework_crash.dmp](https://github.com/praydog/REFramework/files/14879398/reframework_crash.dmp)

I just saw that there is an update I am going to try that version...yup that fixed it.

5. See error

**Expected behavior**

**Screenshots**

**Desktop and VR (please complete the following information):**
 - OS (e.g. Windows 11)
 - Graphics card
 - CPU

**Steam Deck/Linux (please complete the following information):**
 - Proton version

**Virtual Reality (please complete the following information):**
 - Headset model
 - Runtime (OpenVR or OpenXR)

**Additional context**

**Comment by praydog** [comment]
Should be fixed in 2dbae5d1008fc9fc4712e4a48d0a5c17a49fe1d2

Get the latest release on nexus or https://github.com/praydog/REFramework-nightly/releases/
