### ISSUE TITLE
Storage Chest low fps/crash

### ISSUE THREAD

**Issue by GetarnteKadse** [praydog/REFramework#1026]
REFramework causes very low fps and game crash in buy/sell and storage chest menu for me

**Comment by praydog** [comment]
Closed due to insufficient information. Please re-read the issue template and/or the REFramework wiki for required information and files to upload.

https://cursey.github.io/reframework-book/#reporting-a-bug
https://github.com/praydog/REFramework/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
