### ISSUE TITLE
DD2 Inventory/Storage/Merchant Low FPS

### ISSUE THREAD

**Issue by TheBrainninja** [praydog/REFramework#1027]
**Describe the bug**
Whenever entering Storage or a Merchant menu (does not matter the merchant, nor the storage location), the framerate plummets to between 0 and 5 fps (1fps most commonly), and remains this way until a few seconds after exiting the storage/merchant at which point the game "speeds up" back to whatever its previous framerate was.

**Upload logs and any crash dumps**
Locate the `re2_framework_log.txt` in your game directory and upload it along with the issue.
If you crashed, upload the `reframework_crash.dmp` file as well.
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/14895387/re2_framework_log.txt)

**Identify the REFramework version**
144db886528ce60dc659e6fa242119ef7bbc86a6 (per reframework_revision.txt)

**To Reproduce**
1. Go to any merchant or storage box (inc. innkeepers, chests in player-owned home
2. Click on Deposit/Withdraw/Combine/Buy/Sell
3. Observe the framerate tank
4. That's it

**Expected behavior**
No meaningful performance change (outside of acceptable transition frame drops) when entering a menu.

**Desktop and VR (please complete the following information):**
 - Windows 11
 - RTX 3080
 - Ryzen 5800X

**Additional context**
I've tried disabling the other mods that depend on REFramework, and the issue has still occurred without exception. This began happening in the last few days, I'm sorry I do not know what version it was but since then I have removed and re-added REFramework, I've validated the files on Steam, and when I get back to modding again...same issue.

**Comment by praydog** [comment]
Users are saying this is because of the Quality Raytracing mod you're using, which requires REFramework. Not certain this is an REFramework issue. You can try deleting `quality_raytracing.lua` from your `reframework/autorun/` folder.

**Comment by TheBrainninja** [comment]
I had “uninstalled” all mods using Fluffy Mod Manager, but had not manually verified the file removal. I then manually removed all potentially relevant files, verified on Steam, launched the game, and experienced a (slightly lessened) version of the same problem. So yes, as you said, this does not seem directly related to REFramework, sorry for bothering you with this before more fully troubleshooting the issue. I’m going to fully uninstall the game, verify the directory is entirely empty, then reinstall and try again. Thanks for your time!

**Comment by TheBrainninja** [comment]
Just re-commenting to say that the issue still occurs with/without REFramework, on a completely cleaned out install (checked and it even used a second Denuvo activation), so whatever’s causing the issue doesn’t seem related to any mod; other users also reporting this issue without ever installing any mods. Seems like a bug in the game itself, but it’s hard for us to know for sure.

**Comment by Lennn888** [comment]
Capcom [commented ](https://steamcommunity.com/app/2054970/discussions/0/4289188517340570427/)that issue for weeks, definitely comes from the game:

> 16. Accessing the following screens may temporarily increase processing load.
>     Smithies
>     Armories
>     Sundry Shops
>     Scrap Stores
>     Pawn Guild
>     Item Storage
>     Changing pawns
