### ISSUE TITLE
RE7 - Tilted Camera 

### ISSUE THREAD

**Issue by Tarww** [praydog/REFramework#103]
The main issue my setup seems to be having with RE7 in particular is the camera is tilted sideways at about a 30°-45° angle. Can't seem to fix this issue, the other games don't have this problem so I believe it's either something to do with the Quest 2 (using the link cable) not playing well with it or maybe I have some specific camera settings that are messing it up. 

I only know one other user who is having this issue and they're on a Rift S, so maybe it's an Oculus thing?

**Comment by Unicake** [comment]
windows mixed reality here, same bug, it's tilted forwards

**Comment by budwheizzah** [comment]
Same bug, using Valve Index. The relative center position needs to be recalculated with the help of a recenter button like any seated VR game. Especially the fact that this is completely decoupled from pitch to roll to yaw, when there is an offset it can destroy the best of VR legs in 5 seconds, giving the sensation you are on a sinking 18ft boat in 60ft waves.

**Comment by Pastek76** [comment]
Same with HTC Vive headset, have to break your neck to be able to play. Is there a fix or a property to set up in the config.txt ?

**Comment by budwheizzah** [comment]
Someone suggested using the menu to turn Free Camera on, and the back off. This apparently resolves the initially tilted rotation issue, although I didn't get a chance to test yet. 

Keep in mind that because this mod currently moves the entire camera on the vertical rotation axis, it's also critically important that your seated position be facing in the same direction as the player model is, with your head correctly lined up. If you look to the sides while moving your vertical rotation axis, it will appear as if the cam is tilting, which is not the same issue as the initial rotation being tilted.

**Comment by Tarww** [comment]
> Same with HTC Vive headset, have to break your neck to be able to play. 🤣 Is there a fix or a property to add to the re2_fw_config.txt ?

Download the newest build from

https://ci.appveyor.com/project/praydog/reframework/branch/master/artifacts

It should be fixed now, the camera no longer moves with the Y axis (although aiming and the torch does)

**Comment by Tarww** [comment]
> Someone suggested using the menu to turn Free Camera on, and then back off. This apparently resolves the initially tilted rotation issue, although I didn't get a chance to test yet.
> 
> Keep in mind that because this mod currently moves the entire camera on the vertical rotation axis, it's also critically important that your seated position be facing in the same direction as the player model is, with your head correctly lined up. If you look to the sides while moving your vertical rotation axis, it will appear as if the cam is tilting, which is not the same issue as the initial rotation being tilted.

See my comment above for the link, Praydog added an option in the menu to disconnect the Y axis movement from the camera.

**Comment by budwheizzah** [comment]
> See my comment above for the link, Praydog added an option in the menu to disconnect the Y axis movement from the camera.

Oh! No way, already! That is absolutely awesome!

**Comment by Tarww** [comment]
> 

Yep! They are hard at work!

**Comment by praydog** [comment]
Fixed in db2d12bd460275266fe0dd3c8ccac4e5556f5102
