### ISSUE TITLE
Severe framedrops and stutter with "Load Loose Files" option clicked on in Reframework Ver. 802

### ISSUE THREAD

**Issue by Lupercal40000** [praydog/REFramework#1031]
**Describe the bug**
Game running smooth with several mods enabled. Using the latest DLSS and Framegen mod. But when I click on "Load Loose files", game starts stuttering and have framedrops of up to 20 fps while running around in the game.

**Upload logs and any crash dumps**
No crashing

**REFramework version**
REFramework Nightly Build 802

**Steps to reproduce the behavior**
1. Go to 'REFramework Menu'
2. Click on to enable: Loose Files Loader.

**Expected behavior**
Framedrops, stutter every 5-10 seconds. Decrease in general game performance. Getting smooth performance at 60fps everywhere with this option disabled

**Desktop and VR (please complete the following information):**
 Windows 11
RTX 4090
64 GB Ram
i9-14900 KF
4TB SSD
DLSS and DLSSG 3.70 latest
Reshade
Framegen mod

**Steam Deck/Linux (please complete the following information)**
 Steam desktop

**Virtual Reality (please complete the following information)**
None

**Additional context**
Game is stable, with the usual milisecond framedrops of 1-2 fps while loading into a new city area, its an issue with the game engine. Getting smooth 60fps with Framegen mod enabled. Problems only start when I enable the Loose File Loader option.

**Comment by Lupercal40000** [comment]
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/14913823/re2_framework_log.txt)

**Comment by praydog** [comment]
I have to ask, do you need the loose file loader for any reason? Are any mods asking you to enable it?

I'm not really seeing an immediate fix for this because of the way this works. Every file the game requests (tens of thousands likely), the loose file loader needs to do a check on disk to see if it can load it from there. Now there could be some precaching of the existing files on disk, but I'd have to consider if there would be a hit to performance doing this as well.

**Comment by praydog** [comment]
I will try to implement some simple caching here which should alleviate the problem a bit. It might still lag slightly whenever the files are first encountered, but the rest should be okay.

**Comment by Lupercal40000** [comment]
> I have to ask, do you need the loose file loader for any reason? Are any mods asking you to enable it?
> 
> I'm not really seeing an immediate fix for this because of the way this works. Every file the game requests (tens of thousands likely), the loose file loader needs to do a check on disk to see if it can load it from there. Now there could be some precaching of the existing files on disk, but I'd have to consider if there would be a hit to performance doing this as well.

I was enabling to be able to use the Mesh Mod Enabler, that requires it to be enabled to use. Thanks.

**Comment by Lupercal40000** [comment]
> > > I have to ask, do you need the loose file loader for any reason? Are any mods asking you to enable it?
> > > I'm not really seeing an immediate fix for this because of the way this works. Every file the game requests (tens of thousands likely), the loose file loader needs to do a check on disk to see if it can load it from there. Now there could be some precaching of the existing files on disk, but I'd have to consider if there would be a hit to performance doing this as well.
> > 
> > 
> > I was enabling to be able to use the Mesh Mod Enabler, that requires it to be enabled to use. Thanks.
> 
> Can you try the new nightly build here and check if the performance is better? https://github.com/praydog/REFramework-nightly/releases/
> 
> There may be slight hitches when files are first encountered, as mentioned, but should ease up after it knows about them.

OK thank. Will do.
