### ISSUE TITLE
RE8 controllers doesn't work

### ISSUE THREAD

**Issue by FrostKatana** [praydog/REFramework#1039]
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/14968521/re2_framework_log.txt)
In RE8 controllers doesn't work. I'm using Rift S . Tried RE2, works perfectly. In RE8 I move around as a ghost and I can see headless Ethan. There are no controller prompts and no controller motion tracking. I can move only when using keyboard. I don't have any controllers connected. Tried to run it in OpenXR as well.

**Comment by praydog** [comment]
Pirated copies are not supported.
