### ISSUE TITLE
WHOLE PC freeze after using REFramework on RE4

### ISSUE THREAD

**Issue by Luminary0007** [praydog/REFramework#1043]
it does freeze after few minutes when playing RE4 or any other game, i also tried without using MSI or any other PC performance tracking and it still kept freezing, but when i remove REFramework completely from my PC everything runs normal

**Upload logs and any crash dumps**
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/15013089/re2_framework_log.txt)
[reframework_crash.dmp](https://github.com/praydog/REFramework/files/15013092/reframework_crash.dmp)
[reframework_crash.dmp](https://github.com/praydog/REFramework/files/15013094/reframework_crash.dmp)

 - Windows 11 Pro
 - RTX 4090
 - Intel i9-14900K

 Latest RE4 Version on steam

![screen](https://github.com/praydog/REFramework/assets/167327641/16d13513-6cd9-4ae4-ae9a-dca35e383e52)

**Comment by praydog** [comment]
Did you try not using the trainer?

**Comment by Luminary0007** [comment]
> Did you try not using the trainer?

I will try, thank you for replying

**Comment by Luminary0007** [comment]
> Did you try not using the trainer?

I figured out the problem was on my system
