### ISSUE TITLE
RE2 reframework does not initialize "exception thrown"

### ISSUE THREAD

**Issue by Hoparduc-Snowpanther** [praydog/REFramework#1051]
tried multiple nightlys and stable builds, aswell as d12 and d11

[re2_framework_log.txt](https://github.com/praydog/REFramework/files/15137455/re2_framework_log.txt)

im on non ray tracing version

reframework never initializes, the txt file is linked but it ends with "exception thrown"

desktop
windows 10

**Comment by praydog** [comment]
You are on the RT version. Use RE2.zip

Did you pirate the game?

**Comment by Hoparduc-Snowpanther** [comment]
omg yes that was the issue thank you.
