### ISSUE TITLE
Resi 2 and 3 do not start in VR

### ISSUE THREAD

**Issue by Ichbinihremutter** [praydog/REFramework#106]
hi 
1 thank you for reading.

1st things first :
I can start those games from Vr they just start not in vr.
i get a message from steam that the game starts in vr and my monitor which can affect performance
i do use a display emulator
i did set the renderer on both to dx 11

what did i miss out ? 

further : i can use the menu and set it to first person, it just stays the same.
i can see my steam home.
i can see the game when i click on the left menu and klick on desktop.

regards

**Comment by anzbert** [comment]
try this: https://www.reddit.com/r/AnthemTheGame/comments/ar5b8b/psa_workaround_to_disable_hdr_on_nvidia_cards/

or unplug your monitor. i think its an issue with HDR screens

**Comment by Ichbinihremutter** [comment]
anzbert i use a display emulator.
i also did try hdr off and on on the resident evil settings menü.
today i try plug on a monitor (that one had hdr)

**Comment by Ichbinihremutter** [comment]
did reinstall resi 2, connect my tv, and the display emulator after that, btoh worked after connecting to the tv for 1 Time !
