### ISSUE TITLE
DD2 ReFramework LUA Autorun Script Error Issues

### ISSUE THREAD

**Issue by Kalyshnikov** [praydog/REFramework#1065]
All of the .LUA Mods/Scripts in my DD2 Game Autorun folder are giving me errors in the ReFramework ScriptRunner. My game is stuck on a black screen while still running. I don't have a very high number of mods just most of the highest recommended from nexus and these mods were all manually downloaded and placed into the ReFramework MODS folder in .zip format. All of the other Mods are not having any issues or conflicts with my game or ReFramework. Screenshots and ReFramework log text are provided for reference. 

If anyone has any fix actions or advice for this issue please let me know. 

[DD2re2_framework_log.txt](https://github.com/praydog/REFramework/files/15458019/DD2re2_framework_log.txt)

**Identify the REFramework version**
Github developer build 7bd947d (Nightly 924). Downloaded manually from Nexus page.
Extracted dinput8.dll from the zip file into my Dragon's Dogma 2 game install folder.

1. Go to 'ModManager.exe for Fluffy and Launch as Admin'
2. Click 'Enable for available mods'
3. Scroll down and click 'Launch Game'
4. ReFramework Initializes on Start up '.LUA Script errors Pop up Window for all contents in the ReFramework Autorun Folder"
5.  Dragon's Dogma 2 will be stuck on a black screen while running -  without loading into the Main Menu.

**Expected behavior**
Launch DD2 from the Mod Manager as Admin with mods enabled and verify that each mod is working properly.

**Screenshots**
![Screenshot DD2 ReFW32024-05-27 175533](https://github.com/praydog/REFramework/assets/170964335/7d7906b6-ed84-4543-ae48-4dfd24a4d60d)
![Screenshot DD2 ReFWLUA2024-05-27 175533](https://github.com/praydog/REFramework/assets/170964335/02f8ccb8-f524-4d6f-89e7-414e282dbbef)

**Desktop and VR (please complete the following information):**
Lenovo Legion Go 
 - OS (Windows 11)
Processor	AMD Ryzen Z1 Extreme                              3.30 GHz
Installed RAM	16.0 GB (9.69 GB usable)
System type	64-bit operating system, x64-based processor

**Comment by Kalyshnikov** [comment]
UPDATE: Game Launch working.
1. Restart computer
2. Open Game directory file - Delete dinput8 file from installed game folder. (Copy and pasted current dinput8 file into a MISC Back up Folder for precautionary purpose.)
3. Deleted current dinput8 file from DD2 Game Install folder. EXP: [C:\Users\jaywh\KAL9\steamapps\common\Dragons Dogma 2] Copy/Paste NEW / UPDATED ReFramework dinput8 file.
4. Close all windows and current Apps. 
5. Restart CPU 
6. Launch Mod Manager as Admin
7. Launch Game Option 

My assumption is there was an issue with my Game file folder not loading/refreshing after placing dinput8 file. Restarting my CPU and replacing the dinput8 file the second time seemed to fix the initial ScriptRunner .LUA file issue.

Will continue to monitor and troubleshoot if needed. Issue will be closed if able to run the game properly at a stable rate.

**Comment by praydog** [comment]
Your error is just because you did not correctly update dinput8.dll, after looking at your logs. Closing.
