### ISSUE TITLE
Scene Timescale settings for RE7_TDB49

### ISSUE THREAD

**Issue by kanadianborn** [praydog/REFramework#1067]
Most if not all builds of RE7_TDB49 lack the scene settings i.e timescale buttons presumably forgotten to be included cause the RT version of REFramework for RE7 includes the aforementioned settings if so could you please readd the scene menu for RE7_TDB49 in the future?
![Screenshot 2024-05-28 230200](https://github.com/praydog/REFramework/assets/171109120/274fdd8e-3be5-4a74-9c5b-1ae624b94957)
![Screenshot 2024-05-28 230348](https://github.com/praydog/REFramework/assets/171109120/67d7d734-e593-4555-8aa7-16a5d9f9c29a)

**Comment by praydog** [comment]
It is intended because it actually doesn't exist.
