### ISSUE TITLE
DD2:Crash after official frame generation update

### ISSUE THREAD

**Issue by www0041** [praydog/REFramework#1069]
**Describe the bug**
After CAPCOM updated Dragon's Dogma 2 and provided official frame generation on 31st May, the game starts crashing if I open frame generation in the setting menu. It seems that the new update is not compatible with REFramewok.

**Upload logs and any crash dumps**
[re2_framework_log.txt](https://github.com/user-attachments/files/15508946/re2_framework_log.txt)
[reframework_crash.dmp](https://github.com/user-attachments/files/15508951/reframework_crash.dmp)

**Identify the REFramework version**
I use the newest version(Nightly 939),and also try old versions. The problem always exists.

**To Reproduce**
One situation:
1. Download the game on Steam
2. Install dinput8.dll
3. Play the game normally
4. Open official frame generation
5. The game crashes with out CrashReport

Another situation:
1.Uninstall REFramework
2.Launch the game and open frame generation with out crashing
3.Install REFramework
4.Crash on RE engine start up screen

**Expected behavior**
I wish this problem will be fixed as soon as possible.

**Screenshots**

**Desktop and VR (please complete the following information):**
 - OS : Windows 11
 - Graphics card: NVIDIA GeForce RTX 4070 LAPTOP
 - CPU: I7-14700HX

**Comment by revanmj** [comment]
To be precise, in my case it crashes when I try to enable official FG option and then save the settings (until saving settings, there is no crash).

**Comment by www0041** [comment]
> To be precise, in my case it crashes when I try to enable official FG option and then save the settings (until saving settings, there is no crash).

Thanks for your supplement. Actually my problem is the same as yours T_T

**Comment by catcallofcthulhu** [comment]
I'm having the exact same issue. RTX 4080 if that matters.

[reframework_crash.dmp](https://github.com/user-attachments/files/15523983/reframework_crash.dmp)
[re2_framework_log.txt](https://github.com/user-attachments/files/15523984/re2_framework_log.txt)

**Comment by praydog** [comment]
Fixed
