### ISSUE TITLE
Xbox one controller doesn’t work with RE7 or Village

### ISSUE THREAD

**Issue by hydro94530** [praydog/REFramework#107]
It works just fine with 2 and 3 though. Does anyone know what might be wrong? Thanks in advance.

**Comment by Tarww** [comment]
I've had this occur with me in 7. Turning the controller on and off again fixed it for me.

**Comment by hydro94530** [comment]
Thanks. I did manage to get it working in 7 once. Nothing on Village yet.

**Comment by nickyb78** [comment]
How did you get it to work. My xbox controler isnt working either

**Comment by hydro94530** [comment]
I went into big picture mode and then launched the game from there and it worked. Didn't seem to work for Village though.
