### ISSUE TITLE
Dragon's Dogma 2 Cannot Open with REFramework installed (June 02 2024)

### ISSUE THREAD

**Issue by siiirk** [praydog/REFramework#1071]
The game will not open with REFramework installed. The window will open (blank), hang around for a bit, then close automatically. Apparently does not count as a crash, since crash dump is not generated.
[re2_framework_log.txt](https://github.com/user-attachments/files/15526041/re2_framework_log.txt)

Tested with June 02 Nightly Build 953.
DLSS = None
DLSS_FrameGeneration=OFF
Verified game files repeatedly, no effect.

 - OS Windows 11
 - Graphics card NVIDIA GeForce RTX 4090 
 - CPU 13th Gen Intel(R) Core(TM) i9-13900HX

**Comment by praydog** [comment]
Try the newest nightly build and report back

https://github.com/praydog/REFramework-nightly/releases/

**Comment by siiirk** [comment]
That seems to have done the trick! Awesome, thank you 🙏
