### ISSUE TITLE
DD2: CTD on startup

### ISSUE THREAD

**Issue by CorcairiDhearg** [praydog/REFramework#1072]
Dragon's Dogma 2 is still CTDing on startup even with the new nightly release, REF Nightly 953 (52c6916751ea695ec62694d9d480ff4e6e89b844)

I've had this issue since the newest Dragon's Dogma 2 patch released. I've never turned on the Frame Generator feature added, I can't even toggle it on in the settings. I completely uninstalled and reinstalled the game with both the previous nightly release and this one just to make sure my copy of the game was fresh. When REFramework is installed, I start the game, it hangs on a black screen for a bit, and then CTD, and continues to do so until I remove the dinput8.dll

There's no reframework_crash.dmp generated, so unfortunately all I have is the log. 
[re2_framework_log.txt](https://github.com/user-attachments/files/15526108/re2_framework_log.txt)

OS: Windows 11
Graphics card: NVIDIA GeForce RTX 3080
CPU: 13th Gen Intel(R) Core(TM) i7-13700K

**Comment by praydog** [comment]
Try the newest nightly build and report back

https://github.com/praydog/REFramework-nightly/releases/

**Comment by CorcairiDhearg** [comment]
Unfortunately still is crashing nightly 957 as well, exact same way as described before. Here is the log for that as still no reframework_crash.dmp
[re2_framework_log.txt](https://github.com/user-attachments/files/15537556/re2_framework_log.txt)

**Comment by vconti34** [comment]
I am also facing the same problem. I have tried basically every potential option and I cannot get the game to get past the black loadup screen that the OP was saying and I also dont get a crash.dmp file.

**Comment by praydog** [comment]
I think the issues are resulting from D3D12 getting hooked too early - not sure why this is happening yet. So far common link I am seeing is this appears to be happening on Windows 11. I'd need to test on my W11 PC to verify.

**Comment by Joyfal** [comment]
fwiw, I am on Windows 11 with 13600kf and 4090, don't have this issue. But I did get some occasional crash when exiting out of menu and toggling frame generation in menu in game

**Comment by vconti34** [comment]
I am on windows 10 with a rtx 3080 and i9-10900 intel cpu

**Comment by praydog** [comment]
I'm continuing to look into this. I've made some headway but will need some time. Something Capcom did to the renderer is making this a bit harder to solve, but I'm getting there.

**Comment by Joyfal** [comment]
Everything looks good on my side, even toggling frame generation in game no longer crashes. Thank you!

However, I noticed a minor issue where the crash dmp is still generated after me quiting the game from menu manually. This does not impact the gaming experience though (hence minor)

[re2_framework_log.txt](https://github.com/user-attachments/files/15596093/re2_framework_log.txt)
[reframework_crash.dmp](https://github.com/user-attachments/files/15596094/reframework_crash.dmp)

**Comment by CorcairiDhearg** [comment]
I got it to launch perfectly multiple times, including loading into the game and exiting and making sure it reboots again. I also haven't had the issue that the person above me posted with the Framework generating a crash.dmp

Thank you so much for all your hard work!
