### ISSUE TITLE
It does not detect resident evil 4 controllers 

### ISSUE THREAD

**Issue by SrLuisM** [praydog/REFramework#1080]
Describe the bug
I have been able to install R4 but I'm trying to play with meta quest 2 controllers but it does not detect the resident evil 4 is detecting the mouse and keyboard I do not know if you have to modify something in the mod settings or in the game.

Logs
[re2_framework_log.txt](https://github.com/user-attachments/files/15857637/re2_framework_log.txt)

Steam VR 

Screenshots
![1](https://github.com/praydog/REFramework/assets/90636604/1839998b-7581-48e8-b181-4dd0390c7ad9)
![2](https://github.com/praydog/REFramework/assets/90636604/970fe54a-a178-4b67-94af-02159959f019)
I don't know if this error could be the problem I'm having with the controls.

Desktop

OS Windows 10
Graphics card: RTX 3060 
CPU: Ryzen 5 3600X

**Comment by praydog** [comment]
Not supported at the moment. Not a bug.
