### ISSUE TITLE
Dragon's Dogma 2 Update from 27.6. broke REframework

### ISSUE THREAD

**Issue by RDSakharine** [praydog/REFramework#1085]
Using the latest (Nightly963) version of REframework, game won't launch since the game update this morning.

**Comment by praydog** [comment]
Working on it

**Comment by praydog** [comment]
Nightly build should at least partially fix it https://github.com/praydog/REFramework-nightly/releases/

I think there are some other minor issues that I'll look at

**Comment by maramsp** [comment]
I have managed to get the game with a bit of mods working for more then 10 minutes straight.
But i didnt reactivated all my mods yet, so i manually closed the game.
Seemingly the game does crash though, when you go from ingame back to the main menu.
But for the rest, it seems working okayish :)

**Comment by l-t-burkett** [comment]
`[reframework] [error] typedb not found`

Ru-roh

**Comment by l-t-burkett** [comment]
Hey Nightly-976 fixed the TypeDB error! Good stuff. I can get past the black screen, now!

I haven't tried playing for an extended period of time, but I'd still say what's changed is a marked improvement!

**Comment by danielmazurek79** [comment]
With NightlyBuild-985 I still experience crashes with the Dragons Dogma 2 with the latest Trial Version from Steam and the VRTo3D (https://github.com/oneup03/VRto3D) Driver in combination with SteamVR and OpenXR.
I have attached the re2_framework_log.txt file
[re2_framework_log.txt](https://github.com/user-attachments/files/16071456/re2_framework_log.txt)
