### ISSUE TITLE
#971,#973,#978,#965 pd-upscaler not working

### ISSUE THREAD

**Issue by huliqan** [praydog/REFramework#1086]
#782 pd-upscaler , #900 pd-upscaler,#933 pd-upscaler,#946 pd-upscaler,#947 pd-upscaler,#948 pd-upscaler
Works fine on Pico4+VDXR(OpenXR)
but
#971 https://github.com/praydog/REFramework/actions/runs/9692421892
#973 https://github.com/praydog/REFramework/actions/runs/9693468678
#978 pd-upscaler 
https://github.com/praydog/REFramework/actions/runs/9720316825
and #965 pd-upscaler
https://github.com/praydog/REFramework/actions/runs/9389588049
  crashes when loading the game :(((
...
win10x64 21H2 | Ryzen 5600 | 32Гб DDR4 3200 | MSI RTX2080ti Ventus OC 11G

**Comment by praydog** [comment]
Need more info, what game, any logs (re2_framework_log.txt), any crash dumps (reframework_crash.dmp)?

**Comment by huliqan** [comment]
[Uploading re2_framework_log.txt…]()

**Comment by huliqan** [comment]
#980 upscaler build works fine again :) thanks
