### ISSUE TITLE
REFramework with Steam Emulator for Dragons Dogma 2

### ISSUE THREAD

**Issue by FCPerfectO** [praydog/REFramework#1088]
Hello,

Is it possible to load REFramework [REF Nightly 987] or stable [v.1.5.6] with Steam Emulator for Dragons Dogma 2? Few days ago it become possible to launch the game with SE, but if I install "dinput8.dll", the game doesn't launch with SE and an error appears - "Unfortunate something went wrong. Solution check here: https://support.codefusion.technology/anti-tamper/?e=88500005&s=at&l=english". any help please?

Windows 11 Pro 23H2 x64
Geforce 3090
Ryzen 5600x

[re2_framework_log.txt](https://github.com/user-attachments/files/16090500/re2_framework_log.txt)

**Comment by praydog** [comment]
Not supported. Out of scope.

**Comment by FCPerfectO** [comment]
> Not supported. Out of scope.

any chance to add such support?

**Comment by praydog** [comment]
No.
