### ISSUE TITLE
DD2 Ray Tracing not working (Linux)

### ISSUE THREAD

**Issue by Teddy-Kun** [praydog/REFramework#1089]
**Describe the bug**
While I can enable Ray Tracing Options in the menu they do absolutely nothing no matter what I do. The only exception is "Disable Raster Shadows" properly disabling those shadows (only of the player and npc if I am correct). The performance and visuals otherwise stay exactly the same. I didn't get any debug output or anything else. I tried setting some flags like `VKD3D_CONFIG=dxr` and `VKD3D_FEATURE_LEVEL=12_2` but they did absolutely nothing.

**REFramework version**
1.5.7 (1.5.6+28-dcc84bae as shown in game)

**Expected behavior**
The option enabling Ray Tracing of some sort.

**Proton version**
- Proton-GE 9.7
- 9.0-2
- Experimental

**PC Information**
- OS: Arch Linux
- RAM: 32GB
- CPU: Ryzen 5800X3D
- GPU: Radeon 7900XT (Mesa 24.1.2)

If you require any logs of some sort I would gladly help.

**Comment by praydog** [comment]
Yes, I need logs (`re2_framework_log.txt`). I need the game name too.

Usually you also need to turn RT on in the in-game options to get the mod to do anything.

**Comment by Teddy-Kun** [comment]
Thank you this got me down the right path. Apparently the game checks if it is running in wine/proton and disables all ray tracing in general. Hacked the exe and now it works.
