### ISSUE TITLE
ghosting in shortcurts RE7

### ISSUE THREAD

**Issue by OlDirtyMF** [praydog/REFramework#109]
I can see shortcut symbols only sharp in game when i close one eye. Tried Resident Evil 7 on my HP Reverb G1 (WMR headset) with steam. Other than that it looks amazing! Thanks A LOT for this amazin work

**Comment by praydog** [comment]
Fixed in a448631d74e24973b235d23fe6984bd7585d56b6

Download newer builds from https://github.com/praydog/REFramework-nightly/releases/
