### ISSUE TITLE
Kunitsu-Gami: Path of the Goddess

### ISSUE THREAD

**Issue by Freedom0405** [praydog/REFramework#1094]
Kunitsu-Gami: Path of the Goddess formal edition use dd2 reframework 
Will crash

**Comment by praydog** [comment]
Closed. Not enough information. No issues are appearing with this game on my system.

Follow the instructions that come up when you make an issue here: https://github.com/praydog/REFramework/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by Freedom0405** [comment]
Kunitsu-Gami: Path of the Goddess formal edition use dd2 reframework
After opening the game, only the reframework frame is displayed and then crashes.
