### ISSUE TITLE
Need help - DD2 overlay screens (like game start screen) misaligned

### ISSUE THREAD

**Issue by whyme466** [praydog/REFramework#1108]
[re2_framework_log.txt](https://github.com/user-attachments/files/16605765/re2_framework_log.txt)

All game overlay screens are not at correct depth.  Screens like the game start screen are split so far apart that (a portion) of the screen can be read only if one eye is closed.  On my setup, the last official DD2 release consistently crashed, so I migrated to the latest nightly build of DD2 (revision f2254d2cf45574f1385c189a559644c5c8d59a89).  With this nightly build release, VR is stable (the background scene looks great), but the overlay screens do not converge.  OpenVR had a little better overlay screen convergence than OpenXR mode, but the screen overlays are not useable in either mode.

I could not find any applicable solution in VR Troubleshooting, Discussions, or open/closed issues.

System info:
Windows 11 Pro (23H2)/4090/i9-13900K/64GB/multiple SSDs/Varjo Aero/VR Wire2 (nominal screen resolution used is 4504x3860)

**Comment by praydog** [comment]
Turn off "Allow Engine Overlays" under VR.

**Comment by whyme466** [comment]
Thanks for the suggestion, praydog (and outstanding VR mods like this - really appreciated!).

Unfortunately, I could not find "Allow Engine Overlays" under VR tab or any other tab in the RE Framework UI (which appears at correct depth, unlike the overlay screens).  Under the VR tab, I only found a Sync Mode setting (Early), and buttons to Set Standing Height, Set Standing Origin, and Recenter View.

**Comment by whyme466** [comment]
Sorry, I did not notice that the VR tab has MANY more settings, including Allow Engine Overlays.

Disabling "Allow Engine Overlays" creates a stable overlay version, but also repeated versions of some items like the name of the game, obliterating all background imagery as the Aero moves around.  Unfortunately, this is not playable, either.

**Comment by praydog** [comment]
Make sure it's set in the config before the game starts

**Comment by whyme466** [comment]
Unfortunately, the Dragons' Dogma title and some other overlay content are still being repeated across the entire display screen, obscuring all background scene imagery.  My config changes kept being reset when the game started, so I edited re2_fw_config.txt directly to disable "Allow Engine Overlays", ensuring that the config was set before game launch.

**Comment by whyme466** [comment]
Why is this marked closed?  The problem was never resolved.
