### ISSUE TITLE
Graphics error? Shimmer?

### ISSUE THREAD

**Issue by cleggorz** [praydog/REFramework#1114]
So I'm using the latest stable build. I have also tried nightly.

For the love of anything I cannot find a way to fix these bad shimmer effects in re2. It's not just the hair but all reflections. I'm using dx12 version but have also tried dx11 with the same effect. 

I am using a 3070 @1440p

I am sorry for using a camera pic but it really shows the issue. 

![PXL_20240822_150230474](https://github.com/user-attachments/assets/a2246cf1-146e-4c8e-a330-b6b9dbd07f38)

**Comment by cleggorz** [comment]
The game worked fine before adding reframe. I don't know what else to do at this point.

**Comment by cleggorz** [comment]
The game is playable but it looks like 360 game. I have all settings set to max. Turned raytracing on and off

**Comment by praydog** [comment]
Delete your `reframework/scripts` folder. REFramework's GitHub version comes with files that disable TAA for VR.
