### ISSUE TITLE
Cannot interact with UI menu - need a way to have it off by default

### ISSUE THREAD

**Issue by antispamtutoruser123** [praydog/REFramework#112]
This UI menu is nothing but a headache for me.  It's nice that it's there but on my system it doesn't work.  Can't click on anything because when I remove the headset the mod doesn't go back to desktop mode.

Not only this but I can't close the UI menu because I'm using a gamepad.  

Oh well then just use the INSERT key to close it!   Well, I happen to be on a mac remoting into my PC and there is no INSERT key!

I discovered that you can collapse the menu from the config file but I just want it to go away entirely when I launch the mod.  Either be able to rebind so something other than INSERT.  Or have it off by default.

**Comment by praydog** [comment]
Solution to this has been added over the past few updates.

1. You can change your menu key under "Configuration" now.
2. You can enable an option under "Configuration" to remember the closed state of the menu.

New builds can be downloaded her: https://ci.appveyor.com/project/praydog/reframework/build/artifacts
