### ISSUE TITLE
When is resident evil 4 going to support first person VR in this mod?

### ISSUE THREAD

**Issue by Laince1212** [praydog/REFramework#1128]
I was wondering when resident evil 4 would receive first person support. It's been 9 months since the release of the official PSVR2 one and I don't think Capcom is looking to release it on pc ever so I think you're the only way PC gamers can enjoy resident evil 4 in VR on pc. 

Thanks for all your work on VR!

**Comment by praydog** [comment]
Not an issue

**Comment by Laince1212** [comment]
I get that it's not an issue but it's technically a feature request and I added it in feature requests. Seems sorta weird just to close it as "Not an issue" and be done with, I just checked and it seems to be one of the biggest discussions regarding REFramework since November 2023. It would be great if we had any update or if it's even in the works.

Thanks for keeping VR alive with UEVR and REFramework, It's still a shame the RE4 question is just ignored by you for apparently no reason.
