### ISSUE TITLE
MHRise Crashes with OpenVR or OpenXR with SteamVR on the pd_upscaler branch

### ISSUE THREAD

**Issue by oneup03** [praydog/REFramework#1134]
**Describe the bug**
REFramework crashes MHRise after initializing with either OpenVR or OpenXR on the pd_upscaler branch and using SteamVR

**Upload logs and any crash dumps**
Here are dumps from both OpenVR and OpenXR
[OVR_re2_framework_log.txt](https://github.com/user-attachments/files/17386579/OVR_re2_framework_log.txt)
[OVR_reframework_crash.dmp](https://github.com/user-attachments/files/17386581/OVR_reframework_crash.dmp)
[OXR_re2_framework_log.txt](https://github.com/user-attachments/files/17386582/OXR_re2_framework_log.txt)
[OXR_reframework_crash.dmp](https://github.com/user-attachments/files/17386583/OXR_reframework_crash.dmp)

**Identify the REFramework version**
1f6fca296640458181cfc8410baf5f439cb7f36d

**Desktop and VR:**
 - Windows 11
 - RTX2080ti
 - i7-8086k

**Virtual Reality:**
 - VRto3D V2.0.0 (SteamVR)
 - OpenVR and OpenXR

**Additional context**
v1.5.7 release runs normally
9a65668bb38469904f05d4f10f660c2666258352 also runs normally

**Comment by praydog** [comment]
MHRise's upscaler branch was never fixed as the game has DLSS already. Though I'm aware that it should probably be fixed as the new renderer in it (DLSS/FSR aside...) actually fixes various rendering issues in the game in VR (or in your case, VRto3D).

If I get some time I can probably fix it. It's usually just a few offsets that need to be adjusted in the renderer code.

**Comment by oneup03** [comment]
When you have time, that would be greatly appreciated!
 
I've been trying the different pd_upscaler builds to see if they worked with MHRise due to the rendering issues like https://github.com/praydog/REFramework/issues/400

**Comment by praydog** [comment]
I almost have it fixed in 7990c00f18ea41737045a9800bdc25edb6936baa.

However it crashes when any loading occurs in VR. The upscalers work though.

**Comment by praydog** [comment]
d967aa7016305213b045d8fbbe6b7076e7545068 has improved the crashing a bit, now I'm just dealing with issues where DoF seems to be active in the right eye and bloom appears to be blown out really bad.

**Comment by praydog** [comment]
Fully fixed in 8b0d835a6ed14d0b4eaf24dde500d5fbcf265b81

You can re-open if you notice any stability issues

**Comment by oneup03** [comment]
Did some more testing with 8b0d835a6ed14d0b4eaf24dde500d5fbcf265b81 in OpenXR/OpenVR and found a few things:
- Ambient Occlusion isn't rendering right in VR (hard to see unless you use some kind of 3D photo viewer)
- ![Desktop Screenshot 2024 10 21 - 18 33 21 03](https://github.com/user-attachments/assets/93b04d96-7e54-47b2-94e1-d9e9adfbc404)
- The game crashed when I traveled to the Lava fields for the 3 star quest to hunt an Anjanath, but didn't generate a  dump. This was in OpenXR mode and I couldn't reproduce it again
- ![Screenshot 2024-10-21 183728](https://github.com/user-attachments/assets/f2471a8c-1d64-4e02-9d73-db67f886ff21)
- [OXR_re2_framework_log.txt](https://github.com/user-attachments/files/17467868/re2_framework_log.txt)
- It's not a new issue (existed with old renderer), but the detailed map view when you hold left bumper doesn't render correctly and the weapon tree UI at a blacksmith is missing UI elements
- ![Desktop Screenshot 2024 10 21 - 19 07 13 86](https://github.com/user-attachments/assets/4d50cc63-606f-40b0-9b2a-c810dfa9bc0d)
- ![Desktop Screenshot 2024 10 21 - 19 09 33 40](https://github.com/user-attachments/assets/cca75430-4f89-47a5-9ed5-6fb0fee38b47)
- In OpenVR, the first loading screen colors are inverted, but this is minor

**Comment by oneup03** [comment]
Also, there are supposed to be monster status icons that show up in the upper right that don't work currently.
Here's what the blacksmith, detailed map view and the monster icons are supposed to look like:
![Screenshot 2024-10-23 221543](https://github.com/user-attachments/assets/21084627-5c8e-43aa-93e7-551c7b321aed)
![Screenshot 2024-10-23 221942](https://github.com/user-attachments/assets/77b48a3e-8537-49d1-9d61-f7cac1864a6b)

**Comment by oneup03** [comment]
I tested some more and didn't experience a crash again. Also, it looks like the new renderer did fix the monster icons, so ignore that part of my previous post.
