### ISSUE TITLE
sdk.set_native_field always causes an exception to occur

### ISSUE THREAD

**Issue by Akrasr** [praydog/REFramework#1135]
**Describe the bug**
It's my first time using REFramework and I've examined the whole documentation so I could create a mod of my own and I didn't encounter any issues until the moment I've tried using sdk.set_native_field function. I did my best trying to fix this issue, but to no use. And exception description being just "..." didn't help at all.

**Upload logs and any crash dumps**
[re2_framework_log.txt](https://github.com/user-attachments/files/17396211/re2_framework_log.txt)

I don't really think that there is any point in re2_framework_log, because the issue I have is shown only in debug menu, so here's text file for it, too.
[lua-log.txt](https://github.com/user-attachments/files/17396256/lua-log.txt)

And here's my code as well.
[test.txt](https://github.com/user-attachments/files/17396262/test.txt)

**Identify the REFramework version**
REFramework DD2 v1.5.7.

**To Reproduce**
1. Start Apollo Justice Ace Attorney Trilogy.
2. Start the script I've attached to this report.
3. Go to any of the Cross Examinations in the Apollo Justice Ace Attorney.
3. Lose during the cross-examination.
4. See error right before "Guilty" animation being shown.

**Expected behavior**
set_native_field function should work as intended. Please, fix this issue, I'm begging you!

**Screenshots**
![Ошибка](https://github.com/user-attachments/assets/7c5f7424-5ef3-468d-b26b-c886014fa7e1)

**Desktop and VR (please complete the following information):**
 - Windows 10
 - NVIDIA GeForce RTX 4060 Laptop GPU
 - AMD Ryzen 5 7535HS with Radeon Graphics

**Comment by praydog** [comment]
Fixed in 470fe85d2946c2e1ebf0c4b653e244cf6675ec79

I know we chatted on Discord about this and it was solved another way, but this was actually a problem too and should be fixed now.
