### ISSUE TITLE
Cant shoot gun with oculus. 

### ISSUE THREAD

**Issue by nickyb78** [praydog/REFramework#114]
I cant shoot in resi 2 and 3. Are there any comunity bindings or anything i need to change in bindings that would make my oculus controlers shoot?

**Comment by admiralzeech** [comment]
I could shoot by holding the right grip button to ready the gun, then pulling the right trigger. Does that work for you?

**Comment by nickyb78** [comment]
That worked thanks. I feel a bit stupid now :)
