### ISSUE TITLE
MonsterHunterWildsBeta Crashes

### ISSUE THREAD

**Issue by KrisCris** [praydog/REFramework#1142]
Log produced by DD2 build: [re2_framework_log.txt](https://github.com/user-attachments/files/17588610/re2_framework_log.txt)

Log produced by MHRise build: [re2_framework_log.txt](https://github.com/user-attachments/files/17588669/re2_framework_log.txt)

**Comment by praydog** [comment]
Fixed

https://github.com/praydog/REFramework-nightly/releases/latest
