### ISSUE TITLE
DD2 reframework dinput8.dll crash

### ISSUE THREAD

**Issue by X-Zynth** [praydog/REFramework#1155]
**Describe the bug**
if dinput8.dll is on game folder will crash

**Upload logs and any crash dumps**
[re2_framework_log.txt](https://github.com/user-attachments/files/17792753/re2_framework_log.txt)

**Identify the REFramework version**
https://github.com/praydog/REFramework-nightly/releases/tag/nightly-01058-48058763cf0cf79822ed1646305651799f443e29

**To Reproduce**
1. Go to game folder.
2. add reframework and dinput.dll
3. launch game

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/22b6c08c-c424-484f-b4c6-fcf50153bbb5)

**Desktop and VR (please complete the following information):**
 - OS (Windows 11)
 - MSI Radeon 6650 XT 2X Mech OC
 - i3-10100F

**Comment by praydog** [comment]
Pirated copies are not supported.
