### ISSUE TITLE
ReFramework dinput8.dll file does not work for Dragons Dogma 2 v1.0.0.1-Goldberg (pre-launch) version

### ISSUE THREAD

**Issue by doctahoo** [praydog/REFramework#1157]
**Describe the bug**
When adding dinput8.dll to game folder for DD2 Goldberg version (v1.0.0.1, 27.02.2024), the game shows an issue (see screenshot attached below) and cannot start. After closing the dialog, the game exits.

**Upload logs and any crash dumps**
Locate the `re2_framework_log.txt` in your game directory and upload it along with the issue.

[re2_framework_log.txt](https://github.com/user-attachments/files/17798527/re2_framework_log.txt)

**Identify the REFramework version**
Latest DD2 Reframework from this github (v1.5.8).

**To Reproduce**
1. Start DD2 Goldberg by running the executable file runtime_il2cpp.exe.
2. The error message shows when trying to initialize Reframework.
3. Close the dialog.
4. Another dialog opens in Japanese.
5. Close this second dialog.
6. The game exits.

**Expected behavior**
The game should start as usual with no issues and mods should be able to be launched.

**Screenshots**
Please see this screenshot.

![Reframework dinput8 dll start issue](https://github.com/user-attachments/assets/0ec54c75-3b36-45a9-a4e2-e57d03023665)

**Desktop and VR (please complete the following information):**
 - OS Windows 11 Home
 - Graphics card GeForce RTX 4080 16GB VENTUS 3X OC
 - CPU Intel Core i7 Processor 14700KF

**Comment by praydog** [comment]
Pirated copies are not supported.

**Comment by doctahoo** [comment]
Too bad. Fortunately, some mods do not depend on reframework to work.

One less reframework user.
