### ISSUE TITLE
Dragon Dogma 2 QA release

### ISSUE THREAD

**Issue by eyeshield117** [praydog/REFramework#1160]
As you know, the leaked version of the DD2 is out.

I tried to make it work with it, but without any mods, just putting the dinput8.dll file in the game older, only produce the following issue: 

![nqauj79](https://github.com/user-attachments/assets/3fc82d8b-c5f1-4e50-9143-745d81445988)

Reproduce the issue: 

1. DL latest REFramework files
2. Copy dinput8.dll in the game folder
3. The game crashes

**Comment by JibJab1980** [comment]
Where can you get dragons dogma 2 from please eyeshield?

**Comment by praydog** [comment]
Pirated copies are not supported.

**Comment by eyeshield117** [comment]
> Pirated copies are not supported.

Oh whatever, not needed. There is debug mode, you can give yourself whatever items + debug to undo stamina. All I needed. Thx
