### ISSUE TITLE
Dragons Dogma 2 - Ray Tracing completely ruins graphics (and can never be turned off again!)

### ISSUE THREAD

**Issue by DominikCGI** [praydog/REFramework#1163]
**Describe the bug**
When setting a Ray Tracing option the game becomes increadibly ugly to look at (all the options are ugly and kinda broken). It can not be turned off ever again. Disabling them doe snot turn it off. The game stays ugly forever. 

Please help removing this. Or I can never play the game again! :(

**Upload logs and any crash dumps**
No logs, no crash dumb, the game is just ugly af now and I can do nothing about it. It's completely ruind.

**Identify the REFramework version**
https://www.nexusmods.com/dragonsdogma2/mods/8

**To Reproduce**
1. Go to 'Graohics'
2. Click on 'Enable Ray Tracing Tweaks'
3. Click on 'Any Ray Trace Type from the dropdown'
4. Can never be turned off again (Disabling Ray Tracing Tweaks and changing the Type to Disabled DOES NOT disable them!!! It only says it's disabled but it IS NOT)

**Expected behavior**
That the graphics resets to normal graphics without the ugly (fake) ray tracing enabled!

**Additional context**
At least give us any way to turn that ugly ray tracing or fake tracing off, please. This ruins the game completely!

**Comment by praydog** [comment]
You can turn the option off entirely and close the menu, restart the game. It will not turn RT on afterwards.

**Comment by praydog** [comment]
Fixed in e55866daf4f785d2cf28a901631ff5bd5acc6fb5

**Comment by DominikCGI** [comment]
> You can turn the option off entirely and close the menu, restart the game. It will not turn RT on afterwards.
It stayed one time. But I disabled everything and removed the generated settings file from the folders. Now it's default again. Great you found the issue allready.
