### ISSUE TITLE
RE3 VR sol: runtime error: steamapps\common\re3\reframework\autorun\re2_vr_melee.lua:27: attempt to index a nil value (local 'camera') stack traceback:  steamapps\common\re3\reframework\autorun\re2_vr_melee.lua:27: in main chunk

### ISSUE THREAD

**Issue by Chrysalis-Army** [praydog/REFramework#1166]
**Describe the bug**
When starting the game, a error message shows up
=====
sol: runtime error: steamapps\common\re3\reframework\autorun\re2_vr_melee.lua:27: attempt to index a nil value (local 'camera')
stack traceback:

steamapps\common\re3\reframework\autorun\re2_vr_melee.lua:27: in main chunk 
=====
When trying to move around in VR, the game is in first person but cant move arms and Jill do not move where the camera is facing. Game acts as normal 3rd person played with controller. Left stick moves Jill and right moves the camera only in 1st person.
 
**Upload logs and any crash dumps**
[re2_framework_log.txt](https://github.com/user-attachments/files/17969031/re2_framework_log.txt)

**Identify the REFramework version**
Have tried both v1.5.8 and v1.5.7. Both with and without RT

**To Reproduce**
Not sure how to Reproduce, Problem show up every time i reinstall the game, no mater what version i use or with or without RT.
Everything works with RE2, but not RE3 

**Expected behavior**
I expected the arms to follow my arms in real life when i move the VR controllers?

**Screenshots**
![Skärmbild 2024-11-30 122429](https://github.com/user-attachments/assets/1e4f9094-1087-4e43-9fc3-c4278c71a3e4)

**Desktop and VR (please complete the following information):**
 - OS Windows 11
 - Graphics card Radeon RX 5500 XT
 - CPU AMD Ryzen 3 3100 4-Core

**Virtual Reality (please complete the following information):**
 - Headset model Oculus 3
 - Runtime OpenVR

**Additional context**

**Comment by praydog** [comment]
Get past the first five minutes of the game. It's normal.
