### ISSUE TITLE
How can we get these to work with non steam versions?

### ISSUE THREAD

**Issue by mbell151** [praydog/REFramework#123]
I have a version that is outside of steam and when I try to get the game to start it crashes. Was able to get it to work easily with my RE2 version on steam, but when I tried with Village outside of steam it wouldn't work. Any fix?

**Comment by MeatSafeMurderer** [comment]
To be clear, when you say "non-Steam" you mean pirated, right? Because the only legitimate versions are the Steam versions, they're not sold anywhere else.

**Comment by mbell151** [comment]
Does it matter? Question is pretty straightforward.

**Comment by MeatSafeMurderer** [comment]
It only works on legitimate versions. Buy the game.

**Comment by mbell151** [comment]
Not exactly a helpful reply. I will see if I can get it to work and will buy it if it goes on sale.
