### ISSUE TITLE
RE3 first person issues

### ISSUE THREAD

**Issue by kub04** [praydog/REFramework#127]
I'm sure you're already aware of such issues, but when using the new first person mode with motion controls, during cutscenes characters frequently disappear and reappear and my first person camera jumps all over the place. It's bearable because it doesn't affect gameplay but it is extremely jarring.

Also as someone else has mentioned for a different Resident Evil, the icons that appear in-game seem to display in different spots on each VR lens and thereby create a ghosting effect. Not sure if that can be fixed but just wanted to mention it.

**Comment by MeatSafeMurderer** [comment]
Unfortunately I think it's unlikely to be fixed. It would be a huge job well above the scope of the VR mod. Characters are being culled and / or just don't have animation data when they're off-screen. It's just how non-VR games are made, it doesn't make much sense to animate something that is off-screen after all. You're probably better off playing with first person cutscenes disabled.
