### ISSUE TITLE
RE8 Crash on Startup

### ISSUE THREAD

**Issue by coolgameinside** [praydog/REFramework#132]
The game crashes after all the videos before reaching the main menu of the game. HTC VIVE, 10700K, 2070 Super, 32 GB Ram, Windows 11

**Comment by gulaschmann** [comment]
i have the same issue!

**Comment by Highlander1536** [comment]
Same, as soon as it goes to initialize the game crashes to desktop

**Comment by coolgameinside** [comment]
> Same, as soon as it goes to initialize the game crashes to desktop



> i have the same issue!

What version of the game are you using?

**Comment by coolgameinside** [comment]
> > > Same, as soon as it goes to initialize the game crashes to desktop
> > 
> > 
> > > i have the same issue!
> > 
> > 
> > What version of the game are you using?
> 
> where can i see my verison?

Steam or from torrent?

**Comment by gulaschmann** [comment]
is a cracked version

**Comment by coolgameinside** [comment]
> is a cracked version

for me, too, since the cracked version is far from fresh, the game with the vr mod does not work for us.

**Comment by gulaschmann** [comment]
but can i use the mod without vr mod? i will use the freecam or fov

**Comment by coolgameinside** [comment]
> but can i use the mod without vr mod? i will use the freecam or fov

I don’t know about you, but my game with vr mod files does not work at all, crash before main menu.

**Comment by 2022-Julian** [comment]
the resident evil 2 works perfectly, but the RE7 and RE8 crash at startup, and it is the dinput8 file.dll that blocks the start I think it's time to wait for a return version of this file @_@ HELP !!!!!!!

**Comment by coolgameinside** [comment]
> the resident evil 2 works perfectly, but the RE7 and RE8 crash at startup, and it is the dinput8 file.dll that blocks the start I think it's time to wait for a return version of this file @_@ HELP !!!!!!!

RE7 starts up for me, but my room is set up on the other side of the monitor, and since you need to play while sitting at the keyboard or gamepad, I can't play, since all the menus and interactions are in the back. But I looked at the graphics, on ps4 the game looked the same. I'd better replay on PSVR

**Comment by 2022-Julian** [comment]
the game work for torrent  or only steam ?

**Comment by aikidom** [comment]
> the resident evil 2 works perfectly, but the RE7 and RE8 crash at startup, and it is the dinput8 file.dll that blocks the start I think it's time to wait for a return version of this file @_@ HELP !!!!!!!

Same for me re2 and 3 work well....re8 crash with empress version

**Comment by coolgameinside** [comment]
> > the resident evil 2 works perfectly, but the RE7 and RE8 crash at startup, and it is the dinput8 file.dll that blocks the start I think it's time to wait for a return version of this file @_@ HELP !!!!!!!
> 
> Same for me re2 and 3 work well....re8 crash with empress version

cracked version does not work without patches (This version is old ) . If you try the RE8 demo, it works with the VR mod (crooked but works)

**Comment by aikidom** [comment]
> > > the resident evil 2 works perfectly, but the RE7 and RE8 crash at startup, and it is the dinput8 file.dll that blocks the start I think it's time to wait for a return version of this file @_@ HELP !!!!!!!
> > 
> > 
> > Same for me re2 and 3 work well....re8 crash with empress version
> 
> cracked version does not work without patches (This version is old ) . If you try the RE8 demo, it works with the VR mod (crooked but works)

Thanks for info, gonna try with steam version
