### ISSUE TITLE
RE7 error - REFramework error not found, update transform pattern

### ISSUE THREAD

**Issue by Quasim0j0** [praydog/REFramework#134]
I copied the 2 dll files from the zip into the game folder and ran Steamvr.  Get that message every time and it is not in VR, just flat screen.

![image](https://user-images.githubusercontent.com/69202124/147959955-88d98554-a309-4b1d-8f99-859e8be48ff2.png)

**Comment by MeatSafeMurderer** [comment]
Buy the game.

**Comment by Quasim0j0** [comment]
> Buy the game.

I did.  It was on sale for $9.95.  It is working now suddenly.
