### ISSUE TITLE
[RE7] Dot aim issue

### ISSUE THREAD

**Issue by delferius** [praydog/REFramework#135]
The dot pointer not match with the real path of the bullet. All my shots are shifted.

**Comment by coolgameinside** [comment]
How do you play? my screen always appears on the floor or on the wall or on the ceiling, if I manage to start a new game, I'm far from my character. And how to make a re-center, maybe you know?

**Comment by praydog** [comment]
Looking into it.

**Comment by praydog** [comment]
Should be fixed in db2d12bd460275266fe0dd3c8ccac4e5556f5102

If not, reopen the issue.

Download the new builds here: https://ci.appveyor.com/project/praydog/reframework/branch/master/artifacts

**Comment by delferius** [comment]
Tested and it work perfect!
Your work is amazing @praydog!
Thanks so much!
