### ISSUE TITLE
RE3: Game display not appearing on VR headset

### ISSUE THREAD

**Issue by gjc33** [praydog/REFramework#136]
Hi,

I have RE2 with your VR mod working fine on my Lenovo Legion 7 laptop using Virtual Desktop on a Quest 2.  :)

However . . 

I cannot get RE3 VR mod working correctly.

When I launch the game from virtual desktop on the headset (Quest 2), it initially loads in the desktop view, then just after the "Nvidia gameworks" banner, it switches to Steam VR mode and I am in the Vive "holodeck", I can hear the game music/sounds, if I lift my headset, I can see on my laptop screen that the game is indeed at the main menu in VR mode and the headset movement and controller buttons & keys are working.
If I hit the insert key the mod menu pops up and I can switch the game between 1st/3rd person view (on the laptop screen), but still nothing changes in the headset, still stuck at Vive "holodeck".

I have tried disabling any HDR settings in windows display settings and also Nvidia control panel.
NOTE: I dont have the option for choosing the color format / dynamic range as has been suggested on some forums.
(Using latest Nvidia driver 497.29 for GeForce RTX 3080)

Also tried with all combinations of Steam Theatre and Overlay options on/off.

Also tried adding RE3 to VR library and launching it from inside Vive "holodeck" or Steam VR Home, same issue, stuck in "holodeck".

UPDATE 05/01: Got it working (sort of)
The attached RE3_CONFIG.INI file works, until you exit the game, at which point the config file gets changed
It seems that the HDR setting keeps getting turned on even though you don't enable it in-game.
File can be made READ-ONLY to prevent this.

Running Game:
- Edit/overwrite file "C:\Program Files (x86)\Steam\steamapps\common\RE3\RE3_config.ini" with contents of attached file.
- Ensure Steam VR is not running.
- Launch RE3 from Steam GUI.
- Once game loads to start screen, click on it on laptop so it has main focus, this should make it appear in headset.

[re3_config.ini.-working.txt](https://github.com/praydog/REFramework/files/7816205/re3_config.ini.-working.txt)

**Comment by freelivorno** [comment]
I have the same problem with quest 2 (either with cable or airlink or vd). Once enabling and disabling hdr the game started randomly. Then it didn't start anymore: i can hear the audio but not the image, i refer to the steam valley

**Comment by Djouf76** [comment]
Hello, I found the solution for RE3 and RE8, you need in NVIDIA control panel, Output color depth at 8 bpc

Output color format set to yCbCr422

The output dynamic range should be limited

**Comment by Joshiloveyou** [comment]
> 

This worked but unfortunately vr doesn't work, I can't move my hands I can move the head but that doesn't control the body only controls the camera I have to use the joystick to move around. Any idea?

**Comment by gjc33** [comment]
> > 
> 
> This worked but unfortunately vr doesn't work, I can't move my hands I can move the head but that doesn't control the body only controls the camera I have to use the joystick to move around. Any idea?

That's the way its supposed to work.
Look with headset, move with joystick.

**Comment by Joshiloveyou** [comment]
> > > 
> > 
> > 
> > This worked but unfortunately vr doesn't work, I can't move my hands I can move the head but that doesn't control the body only controls the camera I have to use the joystick to move around. Any idea?
> 
> That's the way its supposed to work. Look with headset, move with joystick.

No I mean moving my head dosnt change the Direction my character moves. the only thing it controls is the camera I have to use the right joystick to turn left and right nothing apart from the camera works.

**Comment by Joshiloveyou** [comment]
https://youtu.be/aw_Db9JcShU sorry it's so dark but as you can see. I can't my arms, and I need to use the right stick to make jill move left and right it works like it would with a controller but the camera is free for me to move but not jill

**Comment by Gragory023** [comment]
> > > 
> > 
> > 
> > This worked but unfortunately vr doesn't work, I can't move my hands I can move the head but that doesn't control the body only controls the camera I have to use the joystick to move around. Any idea?
> 
> That's the way its supposed to work. Look with headset, move with joystick.

Can you tell us in more detail how you got to include the picture in the helmet? I can try in NVIDIA control panel change olor depth at 8 bpc and etc. but it can't help. When start game  I see in helm only  the Vive "holodeck"(((

**Comment by TheCreamster** [comment]
I am having the same issue. Resident Evil 2 VR mod worked with 0 issues and now I can't even get Resident Evil 3 VR to launch

**Comment by TheCreamster** [comment]
> I have the same problem with quest 2 (either with cable or airlink or vd). Once enabling and disabling hdr the game started randomly. Then it didn't start anymore: i can hear the audio but not the image, i refer to the steam valley

Did you ever find a fix for this ?

**Comment by Joshiloveyou** [comment]
> > I have the same problem with quest 2 (either with cable or airlink or vd). Once enabling and disabling hdr the game started randomly. Then it didn't start anymore: i can hear the audio but not the image, i refer to the steam valley
> 
> Did you ever find a fix for this ?

No and I gave up looking for a solution. Just stuck to re2

**Comment by TheCreamster** [comment]
> 

I had this issue and after 8 hours of troubleshooting I finally got the game to play in VR on my quest 2.

All I had to do is click enable HDR on the home screen then it launched in my headset and said it would only enable HDR on Fullscreen . Then the game worked just fine.
It was such an easy fix I feel stupid as fuck. Let me know if it works for you please

**Comment by praydog** [comment]
Fixed in https://github.com/praydog/REFramework/commit/163704a8521e01916abfd78ae863a46135c7228d for D3D12. Improvements will come later. Colors will still be washed out or incorrect in HDR but there will at least be video output. It will still be playable with HDR on if you can tolerate not having correct colors. HDR should still be turned off as as complete fix.

New builds can be found here: https://github.com/praydog/REFramework-nightly/releases/
