### ISSUE TITLE
RE2: The image on the PC monitor side is very shaky.

### ISSUE THREAD

**Issue by momotori01** [praydog/REFramework#137]
RE2: The image on the PC monitor side is very shaky.

The image on the PC monitor side is very shaky.
It is not a blur like up and down of the head. I think it's a rendering problem.
I'm using OculusQuest2, RTX3080, 10900kf.
The image on the HMD side is fine.

I may have overlooked a setting, so please let me know if there is something I should do.

**Comment by mamefan** [comment]
That's normal. If you want to record, use openvr obs plugin or steamvr mirror.

**Comment by praydog** [comment]
Fixed a while ago
