### ISSUE TITLE
RE8 oculus touch controllers not working.

### ISSUE THREAD

**Issue by SHADOWLORDVR** [praydog/REFramework#139]
When I play RE8 with the mod it loads but I can't select anything in the menu with my touch controllers and when I go into the intro I can't use the joystick.

**Comment by ayoits0913** [comment]
same here. no controls work in that game

**Comment by erikNORML** [comment]
Same issue. I can hit A on touch to get to the opening menu screen, but stops working there. I used a 360 controller to load up a game from that point and once i'm in the touch controllers work for moving my arms, but no buttons or sticks work. when i go back to the xbox controller i can use that to walk, but not do anything else.

**Comment by ayoits0913** [comment]
> Disconnect your real gamepad joystisk and all will works fine in touch controllers

Thanks I'll try that but RE2R works fine with my controller plugged in, not sure why Village wouldn't

**Comment by SHADOWLORDVR** [comment]
Thanks

**Comment by huliqan** [comment]
> > Disconnect your real gamepad joystisk and all will works fine in touch controllers
> 
> Thanks I'll try that but RE2R works fine with my controller plugged in, not sure why Village wouldn't

Yes! RE2 works with gamepad,but RE8 dos not work
