### ISSUE TITLE
[RE2] Disable Alternate-eye Rendering - Jittery Turning

### ISSUE THREAD

**Issue by DrizzleBoX** [praydog/REFramework#143]
Can you please have an option for disabling alternate-eye rendering? It's hard to play with displays not synced with one another.

I understand this sacrifices the 3D-effect, but it's worth the smooth movement/turning.

Love the mod,
Thank you!

**Comment by praydog** [comment]
It should already be off by default. You can turn it on under VR, it's called **Use AFR**

**Comment by DrizzleBoX** [comment]
Thanks for the quick response.
Seem to be related to issue #147 - I have low GPU usage (%30)

**Comment by praydog** [comment]
Try using this build: https://ci.appveyor.com/project/praydog/reframework/branch/master/artifacts

Should only affect D3D12 performance.

**Comment by DrizzleBoX** [comment]
Ran RE2 on DX12

I saw a small improvement (50% GPU Usage)
CPU Is sitting at around 80% which sounds wrong (7700K 4.8GHz)

**Comment by DrizzleBoX** [comment]
Sorry Praydog, I forgot to include my log.
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/7818199/re2_framework_log.txt)

**Comment by DrizzleBoX** [comment]
@praydog, RE3 has no issues.
