### ISSUE TITLE
Option to grab 2 handed weapons with both hands

### ISSUE THREAD

**Issue by nickyb78** [praydog/REFramework#146]
I hope this option will be added sometime. Holding a shotgun with one hand doesnt look right imo. Amazing mods though :)

**Comment by praydog** [comment]
Added in 13dfbec35625ecf21bfbcbda97cf1a6552972181

**Comment by nickyb78** [comment]
> Added in [13dfbec](https://github.com/praydog/REFramework/commit/13dfbec35625ecf21bfbcbda97cf1a6552972181)

How do i try this. Is there a download somewhere. Tried lastest builds and still holds shotgun one handed. Sorry if im being a noob lol

**Comment by praydog** [comment]
https://github.com/praydog/REFramework-nightly/releases

You'll need to move your left hand to the grip of the shotgun, when it's close enough, it will grip it. You can hold down the left grip for it to stay attached even when moving it far away from the original position.
