### ISSUE TITLE
Unable to recenter view / menus always behind me (RE2)

### ISSUE THREAD

**Issue by erikNORML** [praydog/REFramework#149]
Booted up RE2 and it pays quite well, only issues is that no matter how many times i recenter my Oculus Rift S, menus are always behind me. I have to turn 180 degrees basically whenever I'm on start menu, using inventory boxes, etc. Am I missing a setting somewhere? Can't keep craning my next around just to check a box in a safe room.

**Comment by praydog** [comment]
Should be fixed in ef0cff589db053a8939585cb538eeeaee534be78

New builds: https://ci.appveyor.com/project/praydog/reframework/build/artifacts
