### ISSUE TITLE
Cant really change setting using insert

### ISSUE THREAD

**Issue by mbell151** [praydog/REFramework#150]
The menu is blurry and my mouse doesnt interact well with it at all. Is there a way to expand this menu to make it easier to navigate?

Also, we need a way to turn the head Bob off, it is incredibly annoying.

**Comment by takesword** [comment]
Hmmm you can open the Menu in your VR Headset too by doing some stuff with ur Hands. Look at your hands and put them togheter. That will open the Menu so you dont need to put off ur VR Headset and mange it with ur mouse.
