### ISSUE TITLE
360 wrap vision, dx12 dll

### ISSUE THREAD

**Issue by crookeddeebz** [praydog/REFramework#154]
image is 360 video looking when using latest dx12 dll 1.0223

switch back to DX11 in the game fixes the issue but still won't work with DX12 mode toggle

**Comment by stanisz93** [comment]
taking of the headset and put it back again helps me on oculus quest 2

**Comment by praydog** [comment]
Fixed in 263ac372cb2fbbcdcae8db17ccad7d40d20c1e41
