### ISSUE TITLE
Mirrored flickering image on desktop

### ISSUE THREAD

**Issue by mangomhf** [praydog/REFramework#157]
Hello, 

Game works fine on VR "HP Reverb 2" and i want to stream it but the game image is flickering left and right. How can i fix it? 

Thanks in advance.

**PC Spec:

5950x
34GB 
HP Reverb 2
RTX 3080ti
Windows 10
Nvidia overlay disabled
Drivers updated**

**Comment by ramboCoder965** [comment]
I have the same issue using Quest 2. From inside the hmd, I stream to the desktop (Chrome browser page). Here is an example of what happens https://www.twitch.tv/spookeydonkey/clip/ScaryPhilanthropicSwallowJKanStyle-wY6VocX4v6bxhp7g:

**Comment by mangomhf** [comment]
> I have the same issue using Quest 2. From inside the hmd, I stream to the desktop (Chrome browser page). Here is an example of what happens https://www.twitch.tv/spookeydonkey/clip/ScaryPhilanthropicSwallowJKanStyle-wY6VocX4v6bxhp7g:

Same. It is fine on VR but on the desktop where it also displays, it does that. I don't want to stream it like that. >_<

**Comment by Shadowmask72** [comment]
Same here. The Steam VR preview window is slightly better though.

**Comment by WheatleyKoning** [comment]
Same here, also a Reverb G2

**Comment by Katagena** [comment]
Any news about this bug ? got the same with reverb g2 here

**Comment by praydog** [comment]
Fixed a while ago
