### ISSUE TITLE
VR functions suddenly stop working

### ISSUE THREAD

**Issue by Nemezis2** [praydog/REFramework#161]
Hello,

I've been enjoying these mods so much over the passed days and i played re3 complete in vr now, but i want to play again and now all the vr functions are not working, I believe i could look around by head movement but i was not able to use my arms and my character had an invincible torso, I was recording because i wanted to try to play it on inferno, so i'm sure this footage might help: https://www.youtube.com/watch?v=zI1HHuulJgY

Hopely anybody can help me here, 
thank you!

**Comment by coolgameinside** [comment]
Just go through the beginning of the game to the first autosave without the VR mod. Then play with the mod. I did so, this is what the creator of the mod recommends to do.

**Comment by Nemezis2** [comment]
Wel, it's worth to try it that way, but i can't remember needing to do it like this the first time, i played jills room in vr as well + inferno mode doesn't have a quicksave and less typewriters too. Not sure how far in the game i'll encounter the first one to save the game.

**Comment by Nemezis2** [comment]
> Just go through the beginning of the game to the first autosave without the VR mod. Then play with the mod. I did so, this is what the creator of the mod recommends to do.

Hey, it worked, thanks!!
First quicksave on inferno is right before you need to exit via your window, pretty fast.
