### ISSUE TITLE
Changing ammo types?

### ISSUE THREAD

**Issue by bfinz** [praydog/REFramework#162]
I've tinkered around with the bindings for hours, both the default and custom for Index controllers. How the heck do you change ammo types in RE2? Default in RB but as far as I can see that's not even an assignable binding. I was able to map the D-Pad to the right touchpad, so at least there's a shortcut for switching guns on the fly with just a flick but I HAVE to be able to change grenade round types. 

What's funny is in the inventory menu there are also bumper bindings for changing submenus (files, map, inventory) and THOSE work by clicking in on the upper portion of the touch pad. 

I also can't figure out how to bring up the pause menu. The only way to do it is to click the System menu, I guess I could assign systembutton to something, but the binding menu freezes up after opening and closing it a few times. Probably just a software problem with valve, not much we can do about it other than have solid bindings already as the default.

**Comment by praydog** [comment]
Fixed in de7a6745c68bb35730712c41acc05b59344becac

It's unbound by default. You'll need to change it in SteamVR.

**Comment by bfinz** [comment]
Would I be able to patch this into my game somehow, or would I have to wait until the next release?

**Comment by bfinz** [comment]
Thank you so much, works great I can't wait to play through some more!
