### ISSUE TITLE
Disabling motion controls in RE 8?

### ISSUE THREAD

**Issue by JackDanyels** [praydog/REFramework#163]
Hi, 

didn't know where to ask, but how do I disable motion controls for Resident Evil 8? I couldn't find anything in the cfg files, but I found the function ` vrmod:is_using_controllers()` to be used, but couldn't locate the defintion. Is there an Statement for the cfg file to disable motion controls?

**Comment by praydog** [comment]
Delete  `re8_vr.lua` from your `autorun` folder.
