### ISSUE TITLE
RE8 Not Launching in VR

### ISSUE THREAD

**Issue by silentlimelight** [praydog/REFramework#164]
I did a clean install of RE8 and dropped the files from the RE8 zip into the directory and loaded up steam vr. When I launch RE8 it doesnt launch in the headset at all only on the desktop and there is a box appearing in the upper left corner of the game that says 'REframework' with a couple of checkboxes and it says 'initializing' - after a few seconds of this the game either completely freezes or crashes. Does anyone know whats wrong and how to fix this?

**Comment by coolgameinside** [comment]
Licensed version or torrent?

**Comment by coolgameinside** [comment]
By the way, this is not playable, just play the demo version and the control on the VR controllers (Valve index controllers) is not completed at all, we are talking about the right stick, it is not possible to rotate normally. We are waiting for updates for RE8

**Comment by iiStryker** [comment]
have you tried unplugging the monitor HDMI cable from the GPU and then launching the game?

I have to unplug my HDMI from my GPU prior to running RE7 & 8 in order for it to render to my Quest 2. I'm running linked not VD or Airlink.

**Comment by aikidom** [comment]
> have you tried unplugging the monitor HDMI cable from the GPU and then launching the game?
> 
> I have to unplug my HDMI from my GPU prior to running RE7 & 8 in order for it to render to my Quest 2. I'm running linked not VD or Airlink.

Gonna try this tonight thanks
