### ISSUE TITLE
RE7 VR Some mechanisms and lockers don't animate when actuated

### ISSUE THREAD

**Issue by budwheizzah** [praydog/REFramework#166]
I noticed an issue while going through the ship wreck where some lockers and some mechanisms the player can activate don't animate when actuated. You'll hear the locker door open, but it will appear still closed. You still get the prompts to grab what's inside despite not being able to see the contents. Another example of this is the frames puzzle in the ship wreck: When trying to move one you only hear it, but the animation doesn't play... when you finally solve it and open the safe, the safe door animation also doesn't play.

Not major, but worth reporting. Here is a capture of the issue occurring at the frames section:
https://youtu.be/WIXViyrmmV4?t=296 (Timecode 4:57)

**Comment by AielOlos** [comment]
I have the same problem too. Not only in ship wreck, some lockers in house have the same problem.

**Comment by praydog** [comment]
Fixed in eb5b2af9ebcd51aeb4b5348e6f061357bdf43aed

Newer builds can be downloaded here when it's done compiling: https://github.com/praydog/REFramework-nightly/releases
