### ISSUE TITLE
Diplopy effect on UI indicators

### ISSUE THREAD

**Issue by Skeinon** [praydog/REFramework#168]
Hi guys, the mod is really really cool but i have an issue...
both in RE2 RE3 and RE8 when i approach an object or a door, the indicator spawn double... if i close an eye is single but with two eyes open, i notice this diplopy effect ...really  bad.
i play with a valve index on steamVR beta, no issues witth others games, i've tryed to switch all graphic options without success..anyone have the same problem or an idea about it?

**Comment by drowhunter** [comment]
I also have this affect.  I'm using a Pimax headset.  Parallel projections is off.  This effect is making me cross eyed

**Comment by Skeinon** [comment]
Thank you so much.... and keep it up.  We love your work!!!
