### ISSUE TITLE
RE2 view tilting

### ISSUE THREAD

**Issue by tkapis** [praydog/REFramework#172]
Playing on Pimax 8K+ using index controllers my view randomly tilts 90 degrees so I'm looking at the ceiling. Pressing down on the right joystick restores the normal view. This only happens when standing still.

Also after picking something up I have to look way above me to see the item and then the inventory.

**Comment by Martynas-Mileikis** [comment]
Seems to be a general issue, not headset dependent. The view gets tilted when standing still. Moving any direction restores the position. I hope it gets resolved

**Comment by Martynas-Mileikis** [comment]
Looks like this bug has already been addressed:
https://github.com/praydog/REFramework/commit/db2d12bd460275266fe0dd3c8ccac4e5556f5102

**Comment by titansoftime** [comment]
There is a timeout period where if you do not move or interact with the game the view will tilt like that. Praydog mentioned adding a way to alter this timeout period, not sure if it is implemented yet.

**Comment by praydog** [comment]
> There is a timeout period where if you do not move or interact with the game the view will tilt like that. Praydog mentioned adding a way to alter this timeout period, not sure if it is implemented yet.

It is implemented in ead3a470dcb6e8d6b376ca2a5d4cb0f3bdbe6615

Latest builds can be found here: https://ci.appveyor.com/project/praydog/reframework/build/artifacts

If this fixes the issue when increasing the timer (you can find it under VR), then please close the issue.
