### ISSUE TITLE
Blood screen effect re7

### ISSUE THREAD

**Issue by nickyb78** [praydog/REFramework#173]
The square window that pops up when your injured with the blood effect doesnt work properly in re7 vr as it just shows a box shape in your view. Hopefully that effect can be removed or changed to work in vr

**Comment by nickyb78** [comment]
I managed to get rid of the blood effect with a nexus mod which removes it

**Comment by praydog** [comment]
Reworked in e275d7eccccfcb70311863b3f822428bdd74ce95
