### ISSUE TITLE
Playing RE8 like RE7? (disabeling motion control)

### ISSUE THREAD

**Issue by Chiller1001** [praydog/REFramework#179]
Playing RE2/RE3 with Air Link and motion controls is great.
Playing RE7 with Link and M+K is very good too.
Playing RE8 in this Hyprid Mod is not good. (for me)

Is is possible to play RE8 like RE7 with M+K as long the motion controls are not like in RE2/3?

Thx for the Mods!

**Comment by praydog** [comment]
Delet `re8_vr.lua` from your `autorun` folder.
