### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by gamer19771356** [praydog/REFramework#180]
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/7851896/re2_framework_log.txt)
RE8 crashes after a few seconds

**Comment by Dmand420** [comment]
bummer

**Comment by Dmand420** [comment]
> [re2_framework_log.txt](https://github.com/praydog/REFramework/files/7851896/re2_framework_log.txt) RE8 crashes after a few seconds

bummer

**Comment by takesword** [comment]
EMPRESS Version? Doesnt work for now

**Comment by WaseemRakab** [comment]
> 
@takesword 
why?
