### ISSUE TITLE
RE8 - Using xbox controller, aiming is totally jacked, gun fires off screen when aiming straight 

### ISSUE THREAD

**Issue by hydro94530** [praydog/REFramework#182]
Anyone experience this or know how to fix it? Game is unplayable at first werewolf fight because of this. Thanks in advance.

**Comment by praydog** [comment]
Delete `re8_vr.lua` from your `autorun` folder if you want to play with a gamepad.

**Comment by hydro94530** [comment]
Oh thank you so much!! I will try this and report back. Awesome work on these btw!!

**Comment by hydro94530** [comment]
That fixed it immediately, thank you again!
