### ISSUE TITLE
RE3 VR open the first-person check box, the VR device is not displayed 

### ISSUE THREAD

**Issue by djmkw** [praydog/REFramework#183]
RE3 VR open the first-person check box, the VR device is not displayed main screen just black screen, with sound but if it is not checked, it can only play in third-person in VR, why ? thx sorry for my poor English , (RE2 VR is awesome)

**Comment by djmkw** [comment]
I Want play RE3 VR T_T

**Comment by djmkw** [comment]
Now the third person can‘t use it.
How could this happen?

**Comment by djmkw** [comment]
I can only hear the sound in my VR, but I can‘t see the main picture.

**Comment by djmkw** [comment]
Who can help me remotely? I can donate it.

**Comment by takesword** [comment]
Try to use the MOD Menu in Game with ur Hand on the Gun to bring VR first person or change some Mod Settings. I got this Problem when i put off my VR and changed it on my screen with my Mouse. I fixed it by clicking out of the Game window after changing with Mouse. For some Reason if you stil focus in Game with ur Mouse u getting very much laggs or Blackscreen. If you change something, minimize the Mod Menu and dont click again into the Game Screen or try to just press WIN Key or CTRL+ESC . After that put on ur VR and this should fix it.

**Comment by djmkw** [comment]
takesword:

Thank you for your answer, although I don‘t quite understand it!

I play games with 🎮 by hand, and RE2 is no problem

RE3 I have successfully entered and played it 3 times, but now I can’t play it!

I really don‘t know what the problem is...

My settings are the same as RE2.

**Comment by takesword** [comment]
I am glad to hear that <3.

what do you mean exactly by contoller? XBOX/PS Controller or Motion Control?

Hmmm what is the Problem with RE3?  Are you able to start RE3 or you gonna crash?

**Comment by djmkw** [comment]
Takesword:

I play RE2 with Oculus touch controller.

I have played RE3 successfully three times. I don‘t know why I can’t play it suddenly. I‘ve tried to reinstall and restart, but now the same setting can't play

It is normal to display the screen in HMD, and only the sound of the RE3 main menu can be heard. It is normal for the computer to rotate with the head, but the HMD screen is the background screen of Steam VR! No display the RE3 main menu Only sound!

**Comment by takesword** [comment]
Try to start the game first time without VR. Change DX12 to DX11.

After that put in the 3 files of praydog in the RE2 folder.

Then activate your VR Headset and start the Game without wearing. On your screen (flat) you should see the Game starting.

Press then "Insert" Key and enable VR in the Mod Menu. Minimize then the Mod Menu and dont klick on the Screen again. Press like WIN Key or ALT+TAb.

Put on your VR Headset and it should work.

**Comment by takesword** [comment]
Try to start the game first time without VR. Change DX12 to DX11.

After that put in the 3 files of praydog in the RE3 folder.

Then activate your VR Headset and start the Game without wearing. On your screen (flat) you should see the Game starting.

Press then "Insert" Key and enable VR in the Mod Menu. Minimize then the Mod Menu and dont klick on the Screen again. Press like WIN Key or ALT+TAb.

Put on your VR Headset and it should work.

**Comment by djmkw** [comment]
Takesword:

But openvr.dll is in the file folder, which automatically enables VR. I can‘t start it with the menu. Unless the opener.dll is renamed, I can only enter the main menu of the plane. No more VR

**Comment by takesword** [comment]
yes delete openvr.dll, dinput8.dll and the "autorun" folder.  Then follow the Steps

**Comment by djmkw** [comment]
I‘ll try it later and report it to you. Thank you for your answer.

**Comment by takesword** [comment]
Okay :). Btw which VR Headset u got ?

**Comment by djmkw** [comment]
Takesword:

It‘s really a problem of HDR automatic opening. You need to adjust Nvidia’s panel to solve the problem! Thank you for your teaching! It‘s great!

**Comment by djmkw** [comment]
Yeah

**Comment by takesword** [comment]
:-)
