### ISSUE TITLE
RE2 sound off in most recent build (1-12 build)?

### ISSUE THREAD

**Issue by teddybear082** [praydog/REFramework#185]
It appears perhaps the change to audio positioning in nightly builds may have negatively effected VR sound in RE2.  It was perfect before with release build but now sometimes sounds seem to come from the same direction.  Playing on Oculus Quest 2 plus Virtual Desktop.  Just reporting.

**Comment by praydog** [comment]
What part of the game are you at?

Does this happen still if you turn off "Head Oriented Audio", and then restart the game?

**Comment by teddybear082** [comment]
I am on the Claire Side B and before played Leon.  I will try the step you mentioned and report back.

**Comment by praydog** [comment]
Should be fixed in 2704e9f84a52f7575eef989ef01880e8392661f1
