### ISSUE TITLE
RE2 Crashing on startup

### ISSUE THREAD

**Issue by BWGFX** [praydog/REFramework#187]
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/7864868/re2_framework_log.txt)

**Comment by BWGFX** [comment]
Is the above what is needed to diagnose the issue? Thanks again for any help hope to get this working

**Comment by dmitsuki** [comment]
What is your system info? Graphics card, cpu, etc.

**Comment by BWGFX** [comment]
Thanks so much for replying! Ive tried for hours. Disabled antivirus re
installed everything. Checked all drivers. Still nothing.

Details below

AMD Ryzen 9 3900 12-Core Processor                3.10 GHz
32.0 GB
64-bit operating system, x64-based processor
NVIDIA GeFore RTX 3070

Need any other details?

Thanks again, It would be amazing if you can help me to get this to work

Ben
-------------------

Ben Whitmore Motion Graphics

Contact 07857350498

Email ***@***.***

http://benwhitmore24.wixsite.com/mgfx

**Comment by dmitsuki** [comment]
First things first, have you tried changing to DX11? You can either open the game in non VR and do that or can do it through the reconfig ini file in the root directory of re2.

**Comment by BWGFX** [comment]
Thanks again for helping.
Yes set to DX11 in the graphics settings.
Also optimised settings in game by turning off or down

**Comment by BWGFX** [comment]
[image: IMG_0155.jpg]



Please see the files that downloaded from the link. Maybe I don't have
all the correct files? There is no "ini file"

Thanks again. I will be donating if you can help to get this to work for
sure.

Ben

**Comment by lucasfisher0** [comment]
Are you launching the game directly from Steam?

**Comment by BWGFX** [comment]
So I launch occulus client,steam,steam vr. Connect via airlink then launch the game on desktop in steam. Blackscreen then warning message resident evil not supported in vr etc etc

**Comment by lucasfisher0** [comment]
Last line of the log: VRCompositor failed to initialize.

That is a SteamVR issue. I don't know how the airlink works, but I would try this:

- Start Oculus and AirLink
- Do not launch SteamVR
- Launch RE directly from Steam using the desktop
- ???

**Comment by BWGFX** [comment]
Ok cool. I will try that.

Doesnt steam have to use steam vr to play games in vr?i think it automatically boots steam vr when playing a vr game via steam?

What would be the best setup if not using airlink? Remote desktop?

Do i have all files needed by the way?

Thanks again

**Comment by lucasfisher0** [comment]
When the mod needs SteamVR, it should automatically start. There are non-Steam games that use SteamVR, but since the game is on Steam but isn't marked as a VR game, it sometimes gives me issues launching.

**Comment by BWGFX** [comment]
Ok great will try this when im home and let you know how i get on. I think it will crash again as i have tried it i think without steam vr being active but will try again.any other trouble dhooting i could try before i get back in touch?

Thanks very much

**Comment by BWGFX** [comment]
It worked!!! Loads in with some stuttering but works!Thanks so much for
your help!

2 more final things. How do you turn of vignette and how do you switch to
first person as a menu did not come up at the beginning even when I point
to my wrist as recommended etc

Thanks again

How do I donate?

Ben
-------------------

Ben Whitmore Motion Graphics

Contact 07857350498

Email ***@***.***

http://benwhitmore24.wixsite.com/mgfx

**Comment by BWGFX** [comment]
All sorted. Found the wrist menu. Thanks again for your amazing support!

**Comment by lucasfisher0** [comment]
Cheers, I am not on the dev team so I don't know about donations. This really is an amazing mod though, as much as I could help out it's nothing compared to the work that's been done so far.

**Comment by BWGFX** [comment]
Ok mate!Thanks so much again

**Comment by BWGFX** [comment]
One last thing. Do you know how to smooth out all the aliasing/sparkling.
Seems to be in reflections maybe?

Thanks again

**Comment by lucasfisher0** [comment]
This game still looks better than Alyx at the lowest settings. The mod is supposed to overwrite settings but it sounds like they are getting reverted.

All settings to lowest/off except:
Textures to around 3-4GB, whatever you have VRAM for
Bloom ON
Anisotropic filtering to X16 (max)
Ambient Occlusion to SSAO

Then open the MOD MENU by pointing at your left hand, find the sharpening filter and turn it on.

With this, I am getting around ~60fps on a 3080Ti in RE2, and I haven't checked in RE3 but it is smooth. Maybe RE7/8 will perform better since they are made for first person.

**Comment by BWGFX** [comment]
Great cheers man

**Comment by takesword** [comment]
To get ridd of the lagging stuff, open MOD in game by holding hands togheter or click out of the Window after using MOD in flatscreen with Mouse. You can also Minimize the Mod with the Mouse and Press WIN Key or CTRL+ESC. Than put on the Headset and dont klick with ur Mouse again in the Gamewindow. That fixed laggs or Blackscreen for me.

**Comment by BWGFX** [comment]
Everythings working.thanks for your kind help!

**Comment by takesword** [comment]
glad to hear! i knew u fixed the Problem, but wanted to tell you this if you would still lagging. :) <3

**Comment by BWGFX** [comment]
Amazing thanks so much!!

**Comment by BWGFX** [comment]
Hello,

Hope you are well.

I have a problem with the Resident Evil village Vr mod. I updated my
machine and it stopped working completely.

I have seen people have mentioned this online but no fixes.

Could you possibly tell me how to fix this?

Thanks so much,

Ben
-------------------

Ben Whitmore Motion Graphics

Contact 07857350498

Email ***@***.***

Showreel and website http://benwhitmore24.wixsite.com/mgfx

Design portfolio https://benwhitmore24.wixsite.com/mgfx/design-portfolio
