### ISSUE TITLE
(MHRise) Random crash when going from Steelworks to Buddy Plaza

### ISSUE THREAD

**Issue by velocity7** [praydog/REFramework#188]
Sadly I lost the REFramework log, will post again some other time. I have the crash dump at least, though. Not easily reproducible either.
![image](https://user-images.githubusercontent.com/11874183/149405456-1d22c406-435e-4469-a2c8-6dabf61aae5c.png)

**Comment by praydog** [comment]
If you are able to upload your dmp file along with the dinput8.dll and PDB you compiled, that would help.

**Comment by MartnIV** [comment]
Ive got few crashes tonight, do you need to upload anything else? Not sure what PDB is.
[MHR Crash report.zip](https://github.com/praydog/REFramework/files/7866750/MHR.Crash.report.zip)

**Comment by velocity7** [comment]
I'm only using the DLL from the artifact builds, so I don't think I have a PDB available. I did attach the dump here for you.

https://drive.google.com/file/d/13K_4tXiQRzWeztO9pGZg-SEQ040hFqs4/view?usp=sharing (696 MB)

**Comment by MartnIV** [comment]
Ive played more today and i could not do two long quest without crashing. If a quest last more than 15min, i got to relaunch the game to be sure it doenst crash on the 2nd one.

**Comment by velocity7** [comment]
Sorry, didn't realize that there was a REFramework crash dump file of its own. I don't have a pdb file unfortunately.

[reframework_crash.zip](https://github.com/praydog/REFramework/files/7874168/reframework_crash.zip)

**Comment by praydog** [comment]
Random crashes should be fixed in b98758ce3b1c0986e1bae706d92b0ce322fb57d2

Should allow you to use other third party DLLs like reshade now too.
