### ISSUE TITLE
[MHR] Random crashes

### ISSUE THREAD

**Issue by tw1nsky** [praydog/REFramework#194]
Not triggered by anything obvious. It can happen in town or in the middle of a quest.
On one pc, the game softlocks and the capcom crash manager kicks in.
On the other, the game just suddenly quits. On this one I get a crash dump.
[loggy.zip](https://github.com/praydog/REFramework/files/7874049/loggy.zip)

**Comment by praydog** [comment]
Known issue, should be fixed soon.

**Comment by praydog** [comment]
Should be fixed in b98758ce3b1c0986e1bae706d92b0ce322fb57d2
