### ISSUE TITLE
DX12 Does not work on RE2.

### ISSUE THREAD

**Issue by mbell151** [praydog/REFramework#196]
Playing with a Vive Pro 2 trying RE2 with the VR mod. Everything works fine on DX11, but read that you get much better performance with DX12. When I try to change it to DX12 it prompts me to restart the game. After I restart the game everything is zoomed in like I am looking through binoculars. Is there any fix for this?

**Comment by praydog** [comment]
Change the SteamVR resolution once or take your headset on/off. Known issue.
