### ISSUE TITLE
RE2 Weird problem with camera huuuge offset in menu & cutscena

### ISSUE THREAD

**Issue by stanisz93** [praydog/REFramework#199]
So I am sending short video with problem of 3-person camera during cutscene/menu/inventory. I's actually always sending me there.
I am also starting in that position menu. To be clear, I am using Oculus Quest 2 Airlink.

version of mod 1.1:
https://github.com/praydog/REFramework/releases/download/v1.1/RE2.zip
replaced dinput8.dll (since it written it contains the newest fixes): 
I used newer build of dinput8.dll https://ci.appveyor.com/project/praydog/reframework/branch/master/artifacts

Link to my issue:
https://youtu.be/8y8N9z0UxNQ

**Comment by stanisz93** [comment]
Also this is how my start of the game looks like below:
https://youtu.be/9ipXdch3Oj0
As you can see I am completely detached from the actual scene and walking somewhere. How to fix it?

**Comment by praydog** [comment]
Please upload the `re2_fw_config.txt` from your game folder.

**Comment by stanisz93** [comment]
ok, [here](https://github.com/praydog/REFramework/files/7876132/re2_fw_config.txt)

**Comment by praydog** [comment]
Disable the "FreeCam" option.

**Comment by stanisz93** [comment]
Ok, thanks, it changed everything. No more problems. Actually make sense, but I thought i disabled it while being in "no vr" version". Anyway, thank you very much @praydog  for quick reply :)
