### ISSUE TITLE
RE2 instantly crashes upon start

### ISSUE THREAD

**Issue by Nemesis50** [praydog/REFramework#20]
Can't get the mod working on my PC. Whenever I try to start RE2 with it, the game's window pops up and then instantly closes itself. The log file also isn't produced. Tried every possible version of the mod, results were same. Windows 7 x64, so DX11 in settings, Steam version. I'd be thankful for any help.

**Comment by Masterditto** [comment]
Same problem here on win10

**Comment by odiminox** [comment]
Could you please attach your settings files and also the stats of the machine you are running on?

**Comment by Nemesis50** [comment]
My rig: I5-2500, GTX 970, 8 GB RAM, W7 x64 SP1. NVIDIA drivers version is 399.07. I also have 2 monitors, main is 1680x1050, and second is 1920x1080. if that's of any use. I can also upload my DxDiag, if needed.

Didnt figure out how to attach my settings, so I just copypaste them:
`[Render]
PCTargetAPIFallback=Enable
Capability=
TargetPlatform=DirectX11
UseVendorExtention=Enable
UseOptimizeShader=Enable
MainMenu=True
LastCrashReport=
[RenderConfig]
PCDXver=DirectX11
PCColorSpace=0
PCWindowMode=1
PCResolution=17
PCRefreshRate=1
PCFrame_Rate=0
PCVSync=1
PCRenderingMethod=0
PCImage_Quality=5
PCTextureQuality=6
PCSamplerQuality=5
PCMeshQuality=3
PCAntiAliasing=3
PCMotionBlurEnable=1
PCShadowQuality=2
PCShadowCacheEnable=0
PCAOSetting=2
PCBloomEnable=0
PCLensFlareEnable=0
PCVolumeLight=3
PCReflection=0
PCSSSS=0
PCDOF=0
PCLensDistortion=1
PCFilmGrainNoise=0
PCContactShadow=0
PCParticleLight=0
[Display]
HDRmode=1
[Control_42249857]
MouseReverse=1
MouseBind=0
CameraNormalSpeed=24
CameraHoldSpeed=24
`

**Comment by odiminox** [comment]
Cheers, you could try setting window and HDR mode to false, try again.

Can you post the contents of the log file that the framework generates in the resi folder; might shed some more light.

**Comment by Nemesis50** [comment]
Tried every possible window and render setting, switching HDRmode to 0 in the ini, no differences, instant crash. Also tried switching off 1 monitor and launching the game in 1080p on my second one, still crashes with the mod. 

Another problem is that the log isn't generated for me, so I assume the mod doesn't inject itself in time before the game crashes. Don't know what even try anymore to make it work.
