### ISSUE TITLE
Odd UI rendering

### ISSUE THREAD

**Issue by MistressAshai** [praydog/REFramework#202]
When the menu is focused, it displays like this for me.

![image](https://user-images.githubusercontent.com/8222603/149657558-823ff772-eacb-4965-82df-7a34e73ca609.png)

When unfocused, it displays normally.

![image](https://user-images.githubusercontent.com/8222603/149657575-2a901883-f116-40cd-89ea-eeabed755b48.png)

[re2_framework_log.txt](https://github.com/praydog/REFramework/files/7876826/re2_framework_log.txt)

**Comment by praydog** [comment]
Strange. This is [@cursey](https://github.com/cursey)'s domain so I'll have them look into it, but are you using a multitude of overlays for the game? Or any particular ReShade shaders?

**Comment by MistressAshai** [comment]
I don't have ReShade. The only overlay I can think of is the steam overlay.

**Comment by Rynhho** [comment]
Same problem here. Disabling the steam overlay does not fix it.

**Comment by Rynhho** [comment]
![image](https://user-images.githubusercontent.com/25417373/150564556-d9dcf519-c4ad-4ac1-b3dc-b6a1b07b2647.png)

When unfocused it works properly, the problem is that other mods are not affected by this and remain with those weird colors like in the screenshot.

**Comment by praydog** [comment]
Can you try this old build from before a huge rendering change was made? https://ci.appveyor.com/project/praydog/reframework-dev/builds/42060847/artifacts

Please let us know if it changes anything.

**Comment by stefchiu** [comment]
> Can you try this old build from before a huge rendering change was made? https://ci.appveyor.com/project/praydog/reframework-dev/builds/42060847/artifacts
> 
> Please let us know if it changes anything.

![image](https://user-images.githubusercontent.com/9389839/150675417-15151050-684f-427c-9d38-d5995a28e5a8.png)

looks even weirder with the old build (1440p monitor, AMD 6800xt, latest driver)

**Comment by praydog** [comment]
So far the common link here is that you're both using AMD cards ([MistressAshai](https://github.com/MistressAshai) said so on the MH modding discord).

**Comment by cursey** [comment]
Do any of you experiencing the problem use an HDR monitor?

**Comment by stefchiu** [comment]
> Do any of you experiencing the problem use an HDR monitor?

I am using an HDR monitor but I'm not using it's HDR mode

**Comment by cursey** [comment]
> > Do any of you experiencing the problem use an HDR monitor?
> 
> I am using an HDR monitor but I'm not using it's HDR mode

I've just pushed a change that will log what the back buffer format the game is using. Could you grab a dev build and give it a run. Then just post the log lines that say something like
```
[2022-01-23 03:44:12.106] [REFramework] [info] [D3D12] Back buffer format is XX
```

**Comment by stefchiu** [comment]
> 

[2022-01-23 20:23:12.405] [REFramework] [info] [D3D12] Back buffer format is 24

**Comment by cursey** [comment]
So that format corresponds to 
```
DXGI_FORMAT_R10G10B10A2_UNORM                       = 24,
```
Which is the format the game uses when rendering in HDR. I know you said you're not using HDR but the games still using an HDR back buffer format. I'm thinking that this entire issue is related to this. Thanks for the cooperation. I'll come up with a solution when I wake up.

**Comment by praydog** [comment]
Can you check if this new build fixes it? https://ci.appveyor.com/project/praydog/reframework-dev/build/artifacts

**Comment by stefchiu** [comment]
> Can you check if this new build fixes it? https://ci.appveyor.com/project/praydog/reframework-dev/build/artifacts

yep, fixed. Thank you so much!
