### ISSUE TITLE
RE2 crashes when the framework loads

### ISSUE THREAD

**Issue by cordellstoyer** [praydog/REFramework#204]
For some reason, I can't seem to get this working for RE2. The whole game crashes as soon as the framework window pops up. I tried other d8input files that didn't cause a crash but then it won't let me click anything. Anyone know of a fix? I'm using the....ahem....cracked version from steamunlocked lol

**Comment by StoofManley** [comment]
I'm having the same issue, too. If you look at issue #122, the guy who posted has the paid version. There may be something there that can help. I as well have the... other version. Is yours creating the reframework_crash.dmp file? Mine isn't. 

It is worth noting that I have had no issue with RE3.

**Comment by StoofManley** [comment]
I finally got it working. Just needed to install an update for the game.

**Comment by takesword** [comment]
For me, just put on ur VR Headset before u start the game fixed it. That only happens on RE2 on my Side.
