### ISSUE TITLE
Crash on start RE8

### ISSUE THREAD

**Issue by Totiusan** [praydog/REFramework#214]
Hi!

I am very much not an expert. I downloaded the files and put them in the folder of the game.
The game crashes almost immediately. I am attaching the "re2_framework_log" file.  Thanks for any help
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/7909490/re2_framework_log.txt)
!

**Comment by takesword** [comment]
EMPRESS Version? Doesnt work at all for now

**Comment by takesword** [comment]
exact the same Problem here..

**Comment by takesword** [comment]
@praydog

**Comment by MrOmbre** [comment]
same problem to me: Failed to initialize REFramework on DirectX 12
any solution at now?
