### ISSUE TITLE
(MHRise)[Suggestion] Silent Startup

### ISSUE THREAD

**Issue by marat569** [praydog/REFramework#218]
So, thank you so much for the tool!

I personally REFramework to bypass SpecialK, so having to close the GUI on every launch a bit tedious. A small QOL would be a way to make REFramework run silent via the config or however you set it up.

No need for a fancy checkmark for silent mode, just a line that I/we can edit in re2_fw_config.txt would be enough.

The desired result is to be able to get full "bypass" functionality without having to see the GUI every launch. By bypass functionality I mean whatever magic you guys did to allow third party .dll injection without crashes.

Thank you! <3

**Comment by praydog** [comment]
Added in 3c536fc5910aa03c5c3142ca9ec6b2be08cbf70a

You'll need to enable it under "Configuration" and close the menu. Next time you start the game, menu will close after initialization.
