### ISSUE TITLE
Try to use the MOD Menu in Game with ur Hand on the Gun to bring VR first person or change some Mod Settings. I got this Problem when i put off my VR and changed it on my screen with my Mouse. I fixed it by clicking out of the Game window after changing with Mouse. For some Reason if you stil focus in Game with ur Mouse u getting very much laggs or Blackscreen. If you change something, minimize the Mod Menu and dont click again into the Game Screen or try to just press WIN Key or CTRL+ESC . After that put on ur VR and this should fix it.

### ISSUE THREAD

**Issue by djmkw** [praydog/REFramework#222]
Try to use the MOD Menu in Game with ur Hand on the Gun to bring VR first person or change some Mod Settings. I got this Problem when i put off my VR and changed it on my screen with my Mouse. I fixed it by clicking out of the Game window after changing with Mouse. For some Reason if you stil focus in Game with ur Mouse u getting very much laggs or Blackscreen. If you change something, minimize the Mod Menu and dont click again into the Game Screen or try to just press WIN Key or CTRL+ESC . After that put on ur VR and this should fix it.

__Originally posted by @takesword in https://github.com/praydog/REFramework/issues/183#issuecomment-1019399664__

**Comment by takesword** [comment]
<3
