### ISSUE TITLE
Spotlight not moving with headmovement RE7

### ISSUE THREAD

**Issue by OlDirtyMF** [praydog/REFramework#223]
Hi
If i select "decoupled camera pitch" in the VR menu it's nice that my view doesn't move with the pitch axis. Problem is, the "bright spot" still moves with the pitch axis. Would be nice to have this also locked pitch- wise and have the bright spot where i'm really looking with my headset. 
Thanks for the pitch lock option. Really helps against motion sickness.

PS: Maybe that's not possible because the spotlight reacts the same as aming with a gun?!

**Comment by praydog** [comment]
This is on our to-do list when circle back around to RE7.

**Comment by drowhunter** [comment]
If you do "fix" this can you make it optional.  I kind of like that it feels like I'm holding a flash light.

**Comment by praydog** [comment]
Fixed in #319
