### ISSUE TITLE
(MHRise) Crash on initial load

### ISSUE THREAD

**Issue by HotPocketHPE** [praydog/REFramework#225]
Only dinput8.dll added to exe directory, no other modifications made. Crashes right before "health advisory" screen. Build 1.0.261 from AppVeyor.
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/7921817/re2_framework_log.txt)

**Comment by ak-jparent** [comment]
Same issue here.

**Comment by praydog** [comment]
Can you try the previous build and report back? https://ci.appveyor.com/project/praydog/reframework/builds/42303464/artifacts

**Comment by HotPocketHPE** [comment]
Same issue.
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/7922468/re2_framework_log.txt)

**Comment by praydog** [comment]
Ok. I think you can fix it just by creating an "autorun" folder in your game directory.

**Comment by praydog** [comment]
Fixed in 6abdc3575f16fc947352c24d96dd37b191516656
