### ISSUE TITLE
Fundamental Data Types Need Implementing

### ISSUE THREAD

**Issue by odiminox** [praydog/REFramework#23]
Full capabilities of the framework cannot be utilised for mod development until a wider set of REObject and general RE:Engine data types have been implemented.

As an example, the app.ropeway.PlayerManager requires a RopeWayPlayerManager class to be implemented in ReClass_Internal.hpp. There are several bespoke data types defined in the REEngine, which REObjects such as the PlayerManager make use of; app.ropeway.PlayerDefine.PlayerType is one such type that PlayerManager uses which is not currently defined anywhere.

By assembling a more comprehensive collection of objects and types which describe the structures being used within the REEngine, more power can be leveraged from the RE2-Mod-Framework.

I can see that ReClass_Internal.hpp was generated from ReClass.NET - @praydog what was the process you used to construct the very detailed and thourough set of data for RopewayIlluminationManager (app.ropeway.IlluminationManager)? If you can describe the tools and processes you used, I can investigate this issue.

**Comment by odiminox** [comment]
Just spoke with @praydog - the process is as such:

> I use ReClass.NET to create what's in ReClass_Internal.hpp. You can use the re2.rcnet file in the reversing folder with ReClass. It has a built-in generate C++ header button. You can attach it to re2.exe to get a live view of memory for any class you want, kind of like Cheat Engine's memory dissector. You can also modify any value you want in the class, also like Cheat Engine.
> 
> In regards to process, it's pretty easy with ReClass, just input the address next the class created. To create proper inheritance, you'll need to create a class instance at the start of the class, this tells ReClass to make the class inherit from whatever class instance is at the top. From there, you'll need to give the class a proper size (which can be found with ObjectExplorer). From there, I'd match up with what I'm seeing in ObjectExplorer in ReClass, and create the proper types. There are probably some videos somewhere on using the tool.
> 
> For some fields, you will need to do manual reverse engineering work with IDA if you can't seem to match the value up to anything in ReClass. Each field has a function used to retrieve the value (you can see this in VariableDescriptor).
> 
> If you plan on making a PR with changes to ReClass_Internal, don't commit changes to re2.rcnet, it is in a binary format which makes it extremely hard to collaborate with unfortunately. I can manually add the changes made to re2.rcnet if it's not too large of a diff.

**Comment by odiminox** [comment]
I have made some progress with the RopeWayPlayerManager given the above method described, however a useful capability would be to view the current value for a variable field in the ObjectExplorer. @praydog I have tried extracting values from the VariableDescriptor void* function as you have described but I have had no luck; any suggestions as to how we can get this rendering name to the field name in the ObjectExplorer?

**Comment by praydog** [comment]
Pull the latest commit, I've added support for viewing the values if you click on the field now.
