### ISSUE TITLE
How to use manual flashlight

### ISSUE THREAD

**Issue by nickyb78** [praydog/REFramework#230]
How do i switch flashlight on and of with oculus controlers

**Comment by takesword** [comment]
At the moment you can only use (auto)Flashlight or manual on "F" key

**Comment by takesword** [comment]
Download the last input here and replace it   : https://ci.appveyor.com/project/praydog/reframework/branch/master/artifacts   



"Merge pull request #233 from drowhunter/feature/bind-manual-flashlight
add openvr binding for manual flashlight"   1.0.266    2 hours ago in 23 min 14 sec

**Comment by praydog** [comment]
Added as a binding in f73ef677299ed5bb838f1b535813779932d0f50b

Enable the option and bind the action in SteamVR.
