### ISSUE TITLE
MHR won't show in HMD

### ISSUE THREAD

**Issue by ToeKnee02** [praydog/REFramework#231]
I've spent hours trying to get this to work but it just won't. When I start the game, it won't appear in my headset. I'll see the game running on my desktop but my headset will only show the steam VR background. I've seen some people mention having this exact issue for other games but very few seem to have actually fixed the issue. 

I have already checked out the troubleshooting page and nothing there helped. I also made sure to turn off Steam VR desktop game theater and still nothing. If any is/had this issue and maybe found a fix, please let me know. Any help would be greatly appreciated.

My Hardware
HMD - Rift S
GPU - Nvidia Geforce RTX 2070 Super
CPU - Intel Core i7-10750H

**Comment by praydog** [comment]
Download the newest dev build from here: https://ci.appveyor.com/project/praydog/reframework-dev/build/artifacts

Once done, upload your `re2_framework_log.txt` after running it.

**Comment by ToeKnee02** [comment]
@praydog 

Attached below is the log from the dev build.

[re2_framework_log.txt](https://github.com/praydog/REFramework/files/7930461/re2_framework_log.txt)

**Comment by praydog** [comment]
According to the log, you have HDR enabled. I know you said you don't have an HDR monitor in another issue, but this is the reason why it's not displaying in the headset. The errors at the bottom indicate HDR being enabled as well.

```
[2022-01-24 22:43:43.595] [REFramework] [info] [D3D12] Back buffer format is 24
```

24 is the format for the HDR color format.

I don't have an HDR monitor, but I think there's a way to turn it off globally.

https://i.imgur.com/DnrOJuE.png

**Comment by ToeKnee02** [comment]
@praydog 

These were my current Nvidia settings

![Screenshot 2022-01-25 070258](https://user-images.githubusercontent.com/92264755/150983861-ea2372d3-9d6f-42bf-88b2-0509772286de.png)

I changed them to the same settings you have in that image.

![Changed](https://user-images.githubusercontent.com/92264755/150983946-cd5fccbd-f009-4897-967c-abab7d7820dd.png)

It works now. The game appears in my HMD but it wouldn't load properly, it just keeps freezing up. After doing some testing, it seems to work perfectly fine if the game window is out of focus. I'm in the game and am able to see everything but because of the window being out of focus, not a single input will register and I can't get past the main menu. Once I click on the game window and put focus on it again, the game in the HMD just freezes up and stops working.

Here is my log after all the tests.

[re2_framework_log.txt](https://github.com/praydog/REFramework/files/7933870/re2_framework_log.txt)

**Comment by ToeKnee02** [comment]
Is there maybe a way to get the controller inputs to register without having the game window focused?

**Comment by praydog** [comment]
The game freezing up is because of another issue. https://github.com/praydog/REFramework/issues/147

You'll need to disable "Hardware-accelerated GPU scheduling" in Windows.

**Comment by ToeKnee02** [comment]
That’s exactly what the issue was. After turning that off, it works perfectly now. Thanks so much for you help and assistance!
