### ISSUE TITLE
Re8 controler dont work oculus quest 2...just xbox

### ISSUE THREAD

**Issue by aikidom** [praydog/REFramework#242]
Hi ! Somone know how to make oculus quest 2 contrller work for re8...?for me the game work fine but xbox controller ,oculus controller not working help please!

**Comment by aikidom** [comment]
start the game with touch controller but when the game start touch controller move the hand in games but joystick and button dont work, so if i want to move or interact i need to tak xbox controller..had to delete the games and reinstall but same issue

**Comment by praydog** [comment]
#325
