### ISSUE TITLE
[Valve Index] Mod not working for different head shapes?

### ISSUE THREAD

**Issue by JohnSeyy** [praydog/REFramework#245]
Sounds weird but hear me out. 
I'm a big fan of this mod, amazing job overall. I've played RE2 with this mod and had a great time.
Yesterday I encountered a problem though. 
I invited a friend (who has a much larger build than me)  and wanted to let him try it out. So I started the game, everything was fine, and handed over the headset. 
But as soon as we adjusted the headset (I use a Valve Index) to his head size with the knob at the back of the strap, the mod stopped working. It was the same issue some other people in this forum had, you hear game sound, but the game won't show up. You are basically stuck in the Steam vr waiting room, or whatever you call it.

So at the end of the day we couldn't solve the issue. But today when I wanted to check the error once more, (and adjusted the size of the headstrap back to my original size) it worked again! 
When I started to realize this, I was actually able to recreate the error every time. There seems to be some threshold where the mod just stops working. I have no idea why, but that's what solved the issue for me and I wanted to let you guys know.

**Comment by praydog** [comment]
Probably cixed in 6ec78be9a17d7cc890d2039ffcfa87fcac3040b9
