### ISSUE TITLE
[MHR] Very bad stutter/lag since 1/29 update

### ISSUE THREAD

**Issue by SomeAsian420** [praydog/REFramework#246]
Trying to install the mod for the PC version of Rise. Game takes unusually long to load and freezes for seconds at a time. Using a wired PS4 controller as well. The previous version didn't have this issue. Uninstalling the mod fixes the problem.

**Comment by wakkawakka22** [comment]
@SomeAsian420 check out this plugin and see if it helps. https://www.nexusmods.com/monsterhunterrise/mods/137

**Comment by SomeAsian420** [comment]
> @SomeAsian420 check out this plugin and see if it helps. https://www.nexusmods.com/monsterhunterrise/mods/137

Thought I managed to get it work earlier this morning. However, I booted it up later and the stuttering was back. I guess I'll just have to wait and see with newer updates.
