### ISSUE TITLE
how do you choose secondary functions for weapons in RE2 and RE3?

### ISSUE THREAD

**Issue by harbingerthrace** [praydog/REFramework#248]
What are the buttons in RE2 and RE3 to select alternate/secondary functions in weapons.  In RE3 for example I want to switch between the different mine types and I tried every button combination and can't figure it out.  Please help.  Thanks so much!

**Comment by Xcidis** [comment]
Hold the left triggerwhile moving your analog up left down right , you have to hold the analog and the trigger in any direction

**Comment by praydog** [comment]
Download a newer build from here: https://github.com/praydog/REFramework-nightly/releases

You have the ability to add a binding for that in your SteamVR controller settings.

**Comment by harbingerthrace** [comment]
how do you add a binding. sounds complicated? or is it easy?
