### ISSUE TITLE
Resident Evil 8 Head /hand relative locomotions

### ISSUE THREAD

**Issue by DANdiWARhol** [praydog/REFramework#256]
Hi, 

I am having a problem turning when in standing VR. The only way to turn the body is to use right thumbpad.

**Comment by THISACCCOUNT** [comment]
> Hi,
> 
> I am having a problem turning when in standing VR. The only way to turn the body is to use right thumbpad.

That is sadly the only way to turn your body in this mod for right now. Using your head to turn will be added in a later update (paraphrasing dev's words)

**Comment by praydog** [comment]
Fixed in #319
