### ISSUE TITLE
360 degree fishbowl

### ISSUE THREAD

**Issue by DANdiWARhol** [praydog/REFramework#257]
Hi, I'm having trouble starting VR. 95% of the time I get either 1) 360 degree fishbowl; 2) left eye right eye, but they're the wrong way around. 

I have found that if I alt-enter around 20 times, The game will finally initialise in VR properly (and it looks fantastic!) but it sometimes reverts to fishbowl or wrong-eye when I go into the menu. 

I am running Vive Pro 2; rtx 3090; 10900k.

**Comment by praydog** [comment]
Known issue, duplicate issue.
