### ISSUE TITLE
Issue while trying to require a module

### ISSUE THREAD

**Issue by Diyagi** [praydog/REFramework#258]
So, the following srceenshot is an error while trying to require an module:
<details>
   <summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/9062212/152365861-fac73359-5362-4784-b11c-6c5e9046c26e.png)

</details>

Now, from what I know, you should be able to require a module like this: 
`local draw = require "modules_test.draw";`

Then, the framework should look for the following files inside the `autorun` folder:
```
autorun/modules_test/draw.lua
autorun/modules_test/draw/draw.lua
autorun/modules_test/draw/init.lua
```

But its not what its happening, I got that error which the framework cant find the module,

The way I did it was, I created a folder called `draw` inside the folder `autorun/modules_test`,
and put the script `draw.lua` inside the `draw` folder.
(`autorun/modules_test/draw/draw.lua`)

I then required the module the way I said before:
`local draw = require "modules_test";`

By the error, I can see that the framework tries to look in these folders:
```
./modules_test/draw/draw.lua
./modules_test/draw/init.lua
```
But since it cant find the modules, I can assume that the context for current dir is not the `autorun` folder.

Now, im not sure this is intended, or its a bug, could someone clarify this for me ?

**Comment by praydog** [comment]
Please try the latest commit after it's done compiling and let me know if it fixes your issue.

**Comment by Diyagi** [comment]
The framework still cant find the module if I require `draw`, and have a script named `draw.lua` in the `draw` folder.

But it now can load the module if I require `draw`, and have a script named `init.lua` in the `draw` folder, which is more than enough for me, Thank you
