### ISSUE TITLE
Invalid Example Snipped in Wiki

### ISSUE THREAD

**Issue by misharp** [praydog/REFramework#259]
The example snippet for [Dumping fields of an REManagedObject or type (very verbose)](https://github.com/praydog/REFramework/wiki/Example-Snippets#dumping-fields-of-an-remanagedobject-or-type-very-verbose) is incorrect. 

The function is defined as `local function dump_fields_by_type(type)`, but on the 3rd line of actual code instead of using `type`, `object_type` is used. It is called `object_type` in `local function dump(fields)`, but not in `dump_fields_by_type`. It just needs to be renamed so the parameter name and the variable are using the same name.

I wanted to just submit a PR to fix this.. but apparently you can't submit PR's to wiki's. Didn't know that until now.

**Comment by praydog** [comment]
Fixed it, thanks.
