### ISSUE TITLE
[MHRise] [Feature] Anyway to inject DLCs into games via Lua Scripts?

### ISSUE THREAD

**Issue by Cphmi** [praydog/REFramework#263]
I just wish I don't need to purchase everything again since MHRise is originally launched on nintendo switch and I've already purchased once :/

**Comment by Cphmi** [comment]
I tried look into snow.DlcManager & snow.DlcMounter, still confused on how the thing works

**Comment by praydog** [comment]
Probably. Don't ask about it here.
