### ISSUE TITLE
The crosshair of the RE7 gun is not in the correct position...

### ISSUE THREAD

**Issue by djmkw** [praydog/REFramework#266]
The crosshair of the RE7 gun is not in the correct position,
If the crosshair is turned off, the gun is still difficult to aim,
How to solve this problem please?

**Comment by praydog** [comment]
Download a newer build from https://github.com/praydog/REFramework-nightly/releases

This was fixed a while ago.

**Comment by djmkw** [comment]
Thank you. I'll try it right away.

從 DJMKW 的 iPhone 13 Pro 傳送
