### ISSUE TITLE
 RE8 will feel like VR in the water... impossible to play

### ISSUE THREAD

**Issue by djmkw** [praydog/REFramework#267]
Turning on RE8 will show the distorted appearance in VR,
Very dizzy in VR, abnormal display,
But sometimes it will be normal after restarting,
Now I have encountered it again, and restarting does not help,
RE other series do not have this problem,
Only RE8 will feel like VR in the water... impossible to play

Video:
[https://youtu.be/lSCbYlUXhyg](https://youtu.be/lSCbYlUXhyg)

**Comment by praydog** [comment]
Known issue, duplicate issue.
