### ISSUE TITLE
[Feature Request] Add "copy call signature" option to Object Explorer context menu

### ISSUE THREAD

**Issue by UncleClapton** [praydog/REFramework#269]
I think it would be extremely helpful to modders if there was a quick and easy way to copy the string we need to call a given method from lua scripts. 

Right now it seems we're stuck manually writing these out as strings by hand, which is prone to mistakes. When these mistakes happen they tend to be hard to trace since execution silently fails if the method is not found.

**Comment by praydog** [comment]
Done. You'll still need to erase the variable names (not the types) from the signature if you want to use the exact method. Should be useful.
