### ISSUE TITLE
RE8 CRASH after splash screens

### ISSUE THREAD

**Issue by davidpasquale** [praydog/REFramework#271]
Hi, I am currently getting frustrated because I cannot run RE Village with the VR mod.

I tried all your releases and Nightly Developer Builds but I always get the same results: the program crashes after the Quixel Megascans splash screen.
I can see the REFramework window on the left side, only the About section is available with "REFramework is currently initializing..." message.

Here my framework log:
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/8160597/re2_framework_log.txt)

I can play RE8 with no issue without VR mod.
I can play RE2 without any issue.
I managed to get working RE3 by manually selecting the color format to YCbCr422 in the advanced panel since I have an HDR monitor.

AMD Ryzen 5 5600X 
GTX 1080
Windows 10 Pro 21H2  Build 19044.1566 
Windows Feature Experience Pack 120.2212.4170.0
Oculus Quest 2

Thank for your amazing work!!

**Comment by praydog** [comment]
I don't have a pirated copy to even attempt to fix this, so this is a wontfix from me, sorry.
