### ISSUE TITLE
My Resident evil Village crashes after the loading the logos. It never makes it far enough to the menu screen. 

### ISSUE THREAD

**Issue by Broage23** [praydog/REFramework#272]
I transferred all 3 of the mod files and tried launching it through VR but it still crashed.

[re2_framework_log.txt](https://github.com/praydog/REFramework/files/8165966/re2_framework_log.txt)

This is my log file

**Comment by praydog** [comment]
I don't have a pirated copy to even attempt to fix this, so this is a wontfix from me, sorry.
