### ISSUE TITLE
RE3 Mega problem Rendering Double Screens overlapping

### ISSUE THREAD

**Issue by fivestarHERMES** [praydog/REFramework#273]
dunno what the problem is really or if everyones has this but on my monitor the game looks utter shit double screen overlapping lagging you cant even record gameplay because its all messed up, but in vr it looks good but its also double there too like if i look in mirror at start of game i dont just see 1 body, i see two jill body's splitt in the mirror.

So half half body's on each side of the mirror which is not what i've seen people have on youtube they see 1 body and 2 arms like it should be. i attach videos to make it simpler to understand.

I wanna mention my game is pirate version from fitgirl repack dunno if this is what causes the problems if its outdatet or not otherwise i will buy game if this is the problem for it.

https://user-images.githubusercontent.com/100847800/156568485-004822f6-4d2d-4cee-9129-b33e9dcd8ed1.mp4

Screen recording https://drive.google.com/file/d/1Han3R9d03oOKZNryrYJIdL1Y8JhgdN2s

Now it dont look like that bad in vr its all normal in vr like it should be exept that i see some stuff double example mirror or if i look at a button it Says Button A with a circle around it but its double A A next to eachother and if i look at people on youtube testing same mod they see only 1.

System Specs i run game in 2k Res all max settings
CPU 5800x
GPU RX 6800 XT 16gb
ram 32 gb 3200mhz
samsung 980 pro 1tb

**Comment by praydog** [comment]
Not a bug, completely normal due to how the VR rendering is done. You must record your screen with the OpenVR capture with OBS, SteamVR view, or Oculus Mirror.

**Comment by praydog** [comment]
Also download a newer build from here, it fixes the double vision for interaction icons: https://github.com/praydog/REFramework-nightly/releases/

**Comment by fivestarHERMES** [comment]
Alright thats very nice that it was not a bug glad it works like it should,
and ill download that file directly and try this out really glad to get a
chance to play this game in vr im using valve index and i wanna try Re8
aswell super good work mate, appreciate that you have made this mod its
amazing stuff that hand tracking works and the depth of the 3d in the game
amazing stuff thanks again.

Den tors 3 mars 2022 kl 14:47 skrev praydog ***@***.***>:
