### ISSUE TITLE
can't use the mods menu

### ISSUE THREAD

**Issue by Maichevsky** [praydog/REFramework#281]
I see the menu when I push Insert, but in the headset it is mostly out of sight. I can see it on my monitor but nothing reacts, when I push on the options nothing happens. Is there an obvious reason? Am I missing something?

**Comment by praydog** [comment]
You are only supposed to use it in the headset with your controllers. Face your left palm towards your face, and look at it, then point your right controller towards the center of your palm, and the menu will show up if you are not pressing any buttons.

If you want to use the desktop (insert) menu, you cannot have your headset on when using it.

Additionally, download newer builds from here: https://github.com/praydog/REFramework-nightly/releases
And read the troubleshooting guide: https://cursey.github.io/reframework-book/troubleshooting/VR-Troubleshooting.html
