### ISSUE TITLE
RE8 - disturbing effect

### ISSUE THREAD

**Issue by Clodo76** [praydog/REFramework#289]
There is an effect near light sources that is wrong (nonsense in VR, and rendered only on one eye) that break immersivity.

I captured the gif below with "SteamVR VR View", it's the white "cloud" in the left eye.
Before capture, i lowered or turn OFF any settings (so, it's not "bloom" or "flare" etc), so from what i understand it's not an effect that can be disabled in settings.
![re8_2](https://user-images.githubusercontent.com/1511345/161380304-1d7d5da7-0fb1-46c3-b72b-17ee9629eb01.gif)

**Comment by praydog** [comment]
Please try the latest build here and let me know if it fixes the issue: https://github.com/praydog/REFramework-nightly/releases

It should fix other kinds of graphical issues as well, like the sky in RE8 not looking quite right, and the god rays in RE8. Partial fix for TAA as well (there is still some haloing around objects).

**Comment by Clodo76** [comment]
Perfect, thanks!
