### ISSUE TITLE
RE8 crashed after initialize REFramework

### ISSUE THREAD

**Issue by MrOmbre** [praydog/REFramework#290]
Failed to initialize REFramework on DirectX 12

tested on Win10 21H2 with latest GPU driver (Nvidia 512.15  WHQL)
latest VR Mod Build 1.3
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/8407953/re2_framework_log.txt)
5

**Comment by praydog** [comment]
Only fix for this is to buy the game. I don't have a pirated copy to even attempt to fix this, so this is a wontfix from me.
