### ISSUE TITLE
RE 8: Can't Change ANY Settings In Menu

### ISSUE THREAD

**Issue by MaleFeminist** [praydog/REFramework#295]
The game boots up fine in VR but as soon as I change _any_ setting in the menu (even just audio or controls) the game only renders in one eye, with the screen "following" head movements. It is very disorienting and is only fixed by rebooting the game. (Even resetting settings to default doesn't fix it.) EDIT: Also, I can't see my hands/weapons outside of cut scenes. Is there any fix for this? 

Thanks!

**Comment by praydog** [comment]
Should be fixed in #319
