### ISSUE TITLE
Reframework not initialising on direct x 12 or direct x 11.

### ISSUE THREAD

**Issue by Bertieboo08** [praydog/REFramework#299]
When I try and play re2 with reframework it crashes after the capcom splash screen and the log says that it couldn't initialise on direct x 11 or 12. I'm also having an issue with re7 where it can't find a update transform pattern or something like that

**Comment by praydog** [comment]
Post your re2_framework_log.txt

**Comment by Bertieboo08** [comment]
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/8507874/re2_framework_log.txt)
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/8507884/re2_framework_log.txt)
my apologies for not uploading these in my initial post here you go

**Comment by praydog** [comment]
I don't have a pirated copy to even attempt to fix this, so this is a wontfix from me.
