### ISSUE TITLE
RE7 Recenter View/Reset Height toggle key option re2_fw_config.txt

### ISSUE THREAD

**Issue by J4cKP0t777** [praydog/REFramework#303]
Hi there,
 played RE8 through no problem! edited options in re2_fw_config.txt for toggle keys(came up with 'press any key'?) to Recenter View/reset height..is that not an option with re7?? makes game much easier as can just tap button whenever view drifts which seems to happen after a while. 
Also playing on laptop without an INSERT key so having to use a virtual keyboard to open menu , is there a better way?
Good mods Thanks

**Comment by praydog** [comment]
You can change the menu key in a newer build. Use a newer one. You also should use a newer build if you are missing options in RE7.

https://github.com/praydog/REFramework-nightly/releases
