### ISSUE TITLE
RE7 VR Works but no buttons do

### ISSUE THREAD

**Issue by Scarab2099** [praydog/REFramework#304]
So like, I can’t skip the Go Tell Aunt Rhody Intro, and when I try to select the gamemode and all that, nothing works, it’s still bound to my keyboard. My first instinct was to try rebinding the controls, but that didn’t really work either because I just like, wasn’t able to bind ANYTHING to the right controller. What do I do now??

**Comment by Scarab2099** [comment]
Also forgot to clarify I’m on a Rift S. Does this game not support rift controllers? I thought it had motion controls. (I don’t mean that in a snarky way I swear)

**Comment by praydog** [comment]
Wait until it's released. Also duplicate issue, closed.
