### ISSUE TITLE
Feature Suggestion - Hook from menus

### ISSUE THREAD

**Issue by sigve10** [praydog/REFramework#306]
Whilst I've made myself a quick debugging module for hooking to methods without writing new code, it'd be a welcome change to have the option to hook through right clicking a method. All I personally need is knowing when a function gets called, which could be as simple as a counter in a secondary menu (much like the pin menu).

**Comment by praydog** [comment]
Good idea, I'll probably do it.

**Comment by praydog** [comment]
Added in 37140f45d3896b64dff478986130928fbdbfa4a0
