### ISSUE TITLE
Rainbow colors

### ISSUE THREAD

**Issue by Koniving** [praydog/REFramework#307]
Alright.  Quest 2, PC, etc.  AMD cards.

RE2 works perfectly, with the exception that the desktop display does this double-vision thing killing any fun of having an audience.
RE7 and 8 worked in testing but I haven't gone beyond just booting them up and briefly exploring.

Now on to my RE3 issue.
So originally I had an issue in which the Quest 2 would softlock into forever loading, then when backing out Steam VR would crash and the oculus link could not be re-established without a full reboot.  But going from a version from a few weeks ago to the newest one released very recently fixed that.  Everything worked except displaying in the headset and headtracking.

HDR is off, but I tried the HDR monitor/TV fix.  Nothing.  In fact it usually made the game crash.  I read on one older forum that Directx12 was not supported or the culprit behind a similar issue so prior to this I had switched to 11.  I also read in my REframework crash dump that it tried to write to a virtual address that it didn't have access to, so I changed to admin.  This didn't actually fix anything but things seemed to load faster so I kept it.

I saw a thing about OpenVR and OpenXR, so I deleted the OpenVR to make the switch.  Finally, getting somewhere.  VR headtracking and controllers work.  It doesn't have the double vision on the desktop--awesome!  Except SteamVR is forever stuck.

But reading recent info on common issues there was performance enhancements on DirectX12, so I switched it back on.
Immediately I had a great improvement, the steamvr thing went byebye and I saw an hour glass, then working VR display...

....In rainbow colors.  I can see, but it's like a cross between gourad mode in Turok 2 and Predator vision.  I suspect it isn't loading textures into the display, or at least that's the impression I'm getting.  But everything appears fine on the desktop display.

  (Going back to DX 11 causes no display again.)

While trying to figure out how to disable the Steam VR theater (home is disabled but I have no idea how to disable the basic displayed environment of dots and lines if that's what theater is), I saw an option to have SteamVR be the openXR app...  Thought that might quickly fix it.  That was a bad move; when I tried to start RE3 again it crashed all the displays and everything became unresponsive.

There's no log file for my RE3 framework.  And github won't let me upload the dump file.

**Comment by Koniving** [comment]
I tried removing the OpenVR.dll to use OpenXR on the other REs... they fail to create any kind of displays.
But using OpenVR.dll for RE3 gives me the SteamVR environment with no game display in the HMD, and openXR in RE3 gives me textureless rainbow meshes (everything loads correctly on the desktop but displays bizarre colors on seemingly textureless meshes in the headset).

**Comment by praydog** [comment]
Need your log files.

**Comment by Koniving** [comment]
Here's the log (didn't realize it was going to name it RE2 despite being in RE3) and the crashdump.
[RE3.zip](https://github.com/praydog/REFramework/files/8653719/RE3.zip)

While tweaking around, it's begun crashing again similar to what it was originally doing.  (I tried upgrading my drivers, SteamVRintegration on my AMD card, removing SteamVRintegration after how negatively it affected everything, looking for and not finding any way to force HDR off (as HDR runs on my standard desktop settings and turns off when going into the game), and I can't remember what else I tried but I messed with some Steam VR settings.

Somehow, though, the tweaks I've done have fixed the double desktop image in Resident Evil 2 and its performance has become incredible, but... yeah.  Also RE7 started the no display through the Quest 2 (hard link connection) thing but through OpenXR.
[KonivingRE7.zip](https://github.com/praydog/REFramework/files/8653780/KonivingRE7.zip)
Both RE3 and RE7 are running through OpenXR, bypassing SteamVR as neither are working with it in the OpenVR.

**Comment by praydog** [comment]
If you are using Virtual Desktop, that is not supported in OpenXR unless you are using the SteamVR OpenXR runtime. Only airlink can run the mods natively through Oculus' OpenXR runtime.

The RE3 logs indicate that you're still running HDR and the game is creating a backbuffer format that is incompatible with VR headsets.

The RE7 logs indicate that it couldn't find a headset, I get the same error when using Virtual Desktop and trying to use the native Oculus OpenXR runtime.

Disabling HDR can be done like this on Nvidia cards, not sure how it's done on AMD:
![b](https://user-images.githubusercontent.com/2909949/167476487-bdc03d6d-52b9-4f7e-9719-323d12d9b759.png)

**Comment by Koniving** [comment]
Okay, so I removed Virtual desktop completely.  In Windows HDR is off, Radeon's Adrenaline software supposedly has no HDR.  There's a "WCDR" wide color display range but that's disabled, there's also an sRGB which also ties to colors.

I deleted the logs altogether for a fresh start on them and tried them.
Did Re3 first.  Crashed everything.
Tried RE7...  everything worked while messing with the menu, but when I tried to use the back button to exit the game all the displays crashed again.

Neither produced a crash report -- so the displays just stopped working (but the computer would not respond to the reset button).

RE7 worked today after removing Virtual desktop completely at least until I hit back one too many times on the main menu then all the displays crashed again.  But I wonder if that was me hitting buttons.
RE2 has no issues whatsoever which has me wondering if maybe it's just RE3?

RE3's HDR is turned off in the options; is there a way to force it off anyway?  It seems RE3 is the only one that had an issue regarding HDR.  (Though now it's crashing all the displays.)

[KonivingRe7Working.zip](https://github.com/praydog/REFramework/files/8654787/KonivingRe7Working.zip)
[KonivingRE3newCompleteCrash.zip](https://github.com/praydog/REFramework/files/8654796/KonivingRE3newCompleteCrash.zip)

Thank you for your help so far.  Where can I donate?  RE2 in VR's been pretty amazing and I appreciate the effort you've put in.

**Comment by Koniving** [comment]
![HDR settings](https://user-images.githubusercontent.com/18667806/167486818-2bf5276c-29ad-4c42-aef3-32a31a5f3e1f.jpg)
My settings similar to the Nvidia.  Mine only does 4:2:0 though rather than 4:2:2

**Comment by HairlineBandit** [comment]
Hello, just wondering if you have discovered a fix to the rainbow display problem. I've been having the same issue with all resident evil VR mods.

**Comment by Buzbee** [comment]
The config file posted in issue 136 fixed the rainbow issue on my amd card using openxr on quest 2. for re2 non ray tracing version.  I set my amd settings to 8 bit 4:2:2 also. i am still trying to solve the rainbow issue in re7 ray tracing version though.
[https://github.com/praydog/REFramework/issues/136]

**Comment by IC3CU8E** [comment]
I've been having the same issues which after messing around I found a simple workaround for Openvr being stuck at steamvr loading screen which fixed both RE3 and RE7 after updates. Just select the game icon (so by pressing enter it would launch) then unplug your monitor from your computer, press enter and after the game has fully launched in your VR you can plug the monitor again whilst playing.

**Comment by d1andonlyantman** [comment]
Fyi i appear to have sorted my RE2 rainbow screen issue by switching back to the dx11 non-rt beta version.

**Comment by harveyshepherd** [comment]
I have the same rainbow colour issue in RE8 using an AMD 6750XT. no HDR enabled in game or windows. 

I would love to work to solve this issue and will make any settings adjustments and provide new logs in short order for you. 

[logs.zip](https://github.com/praydog/REFramework/files/10096421/logs.zip)

**Comment by bbakrr1818** [comment]
Hey guys. I have tried every possible fix for this issue. Although I'm unaware of how to remove the virtual desktop. It will run on openXR but the colors are rainbow like others have seen. Would greatly appreciate someone helping me

**Comment by d1andonlyantman** [comment]
> Hey guys. I have tried every possible fix for this issue. Although I'm unaware of how to remove the virtual desktop. It will run on openXR but the colors are rainbow like others have seen. Would greatly appreciate someone helping me

Hi. I fixed mine by downloading the old Non-RT version. Minimal fiddling and then it just worked.

**Comment by bbakrr1818** [comment]
> 

I cant even get the game to run with the non ray tracing version. itll open up then just close

**Comment by d1andonlyantman** [comment]
Oh, thats annoying. Sorry, i cant really help any more

**Comment by praydog** [comment]
> > 
> 
> I cant even get the game to run with the non ray tracing version. itll open up then just close

You need to download the old version of the mod, the ones that have "TDB" in the file name.

**Comment by bbakrr1818** [comment]
> > > 
> > 
> > 
> > I cant even get the game to run with the non ray tracing version. itll open up then just close
> 
> You need to download the old version of the mod, the ones that have "TDB" in the file name.

I did that.  Then extracted it just like normal and it would open up the game then it would just close

**Comment by andreymoskvenkov** [comment]
Have got same issue with RE4. All other versions of RE are working fine.

**Comment by andreymoskvenkov** [comment]
I have resolved the issue with RE4 - each time, when I start the game, in Resident evil menu in graphics settings I enable HDR (because it is always disabled, when you start the game, but looks like it does not work) and then disable it again - and colors become not rainbow.

**Comment by Mousuou** [comment]
I've been trying to fix the colour issue on re7, I eventually got it to actually work the game but the colours are all rainbow and makes the game unplayable. I eventually found this whole page and basically went through every solution that's here but none worked. I tried going into the beta files on Steam and switching to the dx11 non-rt and tried it with the old vr files but it just doesn't show on the headset. Has anyone ever found another fix for it?

**Comment by Chinga3** [comment]
I am having the exact problem as @Mousuou, and I tried the below steps 
Turning HDR off and Turning Ambient Occlusion off. Although the display is perfect on my monitor and deleted OpenVR dll to use OpenXR.
I have also turned off the Steam Home in SteamVR, although I am not sure that's what is meant by "Turn off Virtual Desktop"
Any help would be highly appreciated. Thanks in advance.

**Comment by Chinga3** [comment]
> > Hey guys. I have tried every possible fix for this issue. Although I'm unaware of how to remove the virtual desktop. It will run on openXR but the colors are rainbow like others have seen. Would greatly appreciate someone helping me
> 
> Hi. I fixed mine by downloading the old Non-RT version. Minimal fiddling and then it just worked.

@d1andonlyantman Can you please mention what kind of minimal fiddling?

**Comment by praydog** [comment]
Try just switching to windowed mode instead of fullscreen. This usually fixes it for me if explicitly disabling HDR does not.

**Comment by Chinga3** [comment]
@praydog thanks for the quick reply.. but window mode didn't work. what worked is unplugging the monitor before the game launch.. I was able to plug in the monitor without any issues. 
monitor resolution is 4k. but when unplugged game defaulted to 1080p, and I wasn't able to make it 4k even if the monitor is plugged in. But disabled FSR and made the resolution scale 1.4x and its smooth as butter.

**Comment by Masano91** [comment]
OK,  i found a workaround for rainbow color in openxr with quest 2: turn off your monitor then start the game in oculus libraries (obviously desktop mode doesn t work), the turn on. Everything work fine now!

**Comment by praydog** [comment]
Partial fix has been added in 2c09f11a08143963530f5a2ea291e10fbce366ac for the D3D11 (non-RT) versions of the games. D3D12 will come later.

**Comment by praydog** [comment]
Fixed in 163704a8521e01916abfd78ae863a46135c7228d for D3D12. Improvements will come later. Colors will still be washed out or incorrect in HDR but there will at least be video output. It will still be playable with HDR on if you can tolerate not having correct colors. HDR should still be turned off as as complete fix.

New builds can be found here: https://github.com/praydog/REFramework-nightly/releases/

**Comment by MehrdadMolavi** [comment]
Hello friends,

I solved this issue simply as following:

-delete "openvr_api.dll" file from the game folder to urge it using OpenXR runtime.
-copy "dinput8.dll" file from the game folder to your Desktop and delete it from the game folder to avoid running the Praydog mod.
-run the game normally and turn down all the graphic settings in the game.
-from your Desktop, copy "dinput8.dll" back to the game folder.
-press "Insert" key to show the mod manager menu.
-in the "VR" popdown menu, change the Rendering method to "Two Frame Sequential".
-restart the game.

Do not forget to restart the game after changing the Rendering method!
After solving the color issue, you could turn up the graphic settings in the game.

Thanks Praydog for such a nice job.
My specs: Quest 2, Occulus Link Cable, Core i5 12400F, AMD Rx 6700 XT GPU, 16 GB RAM.

**Comment by praydog** [comment]
> ![Praydog Mod VR Color Correction](https://private-user-images.githubusercontent.com/136899488/311184472-77075bca-87ff-40f9-97fa-8e7bf3fd4a84.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4OTY0MzMsIm5iZiI6MTcwOTg5NjEzMywicGF0aCI6Ii8xMzY4OTk0ODgvMzExMTg0NDcyLTc3MDc1YmNhLTg3ZmYtNDBmOS05N2ZhLThlN2JmM2ZkNGE4NC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwOFQxMTA4NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NDA5ZmYwNzRkNjA2ZDM0YTVjYjAwZDI4MjUwZGExZGQxY2QyODkwZTdmZDQwN2ZkMTU4ZDM1ZTM0NWVkODliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JF6E-RM-hv-HRycU-N6X5WNhnuMmHT5ntZ_NDw3lxSY) Hello friends,
> 
> I solved the color issue in RE4 Remake Praydog mod VR as following:
> 
> -delete "openvr_api.dll" file from the game folder to urge it using OpenXR runtime. -copy "dinput8.dll" file from the game folder to your Desktop and delete it from the game folder to avoid running the Praydog mod. -run the game normally and turn down all the graphic settings in the game. -from your Desktop, copy "dinput8.dll" back to the game folder. -press "Insert" key to show the mod manager menu. -in the "VR" popdown menu, change the Rendering method to "Two Frame Sequential". -restart the game.
> 
> Do not forget to restart the game after changing the Rendering method! After solving the color issue, you could turn up the graphic settings in the game.
> 
> Thanks Praydog for such a nice job. My specs: Quest 2, Occulus Link Cable, Core i5 12400F, AMD Rx 6700 XT GPU, 16 GB RAM.

Just so you know, this rendering method is far less performant than the single frame multipass. At least it is on my machine.

**Comment by MehrdadMolavi** [comment]
Above mentioned method, now I'm playing RE4 Remake smoothly in VR.
FSR-1 set on Quality.

**Comment by sean81** [comment]
Wait resident evil 7 vr does not support virtual desktop? I ran it through virtual desktop and it ran just fine and I wasn't even running steam VR
