### ISSUE TITLE
Re8 crash on startup

### ISSUE THREAD

**Issue by bradley2234** [praydog/REFramework#308]
Re2 and Re3 work just fine but when i open re8 it loads up and just crashes it works without the mod just fine at max settings so im at a loss. Here is the log if that helps at all
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/8657298/re2_framework_log.txt)
:

**Comment by praydog** [comment]
Use a newer build.
https://github.com/praydog/REFramework-nightly/releases

**Comment by bradley2234** [comment]
thank you so much, love your work dude

**Comment by Volklegator** [comment]
Hey ! I also have re8 crashes on startup. installing the latest mod did not solve the problem. Please help.

**Comment by Volklegator** [comment]
Hey ! I also have re8 crashes on startup. installing the latest mod did not solve the problem.

**Comment by Volklegator** [comment]
[re2_framework_log.txt.txt](https://github.com/praydog/REFramework/files/8682128/re2_framework_log.txt.txt)

**Comment by praydog** [comment]
> [re2_framework_log.txt.txt](https://github.com/praydog/REFramework/files/8682128/re2_framework_log.txt.txt)

I don't have a pirated copy to even attempt to fix this.
