### ISSUE TITLE
Player camera offset, no auto rotation-based movement and crash in first few minutes on my PC rig.

### ISSUE THREAD

**Issue by tanspired97** [praydog/REFramework#313]
Having the issues on the VR mods:
- Player camera getting offset as I see the players body into third-person camera when I moved the real-world position.
![image](https://user-images.githubusercontent.com/96433438/168456632-561cd662-23a8-4434-8e7a-7cc4d2b03102.png)

- No auto-rotation based movement, only have to manually rotate by using right thumbstick.
- Crashed in first few minutes during VR gameplay.

Running on Oculus Quest 2, OpenXR.

Hope you can fix those problems, let me know if you have any updates. Thank you.

Issues attachments:
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/8694263/re2_framework_log.txt)
[reframework_crash.zip](https://github.com/praydog/REFramework/files/8694264/reframework_crash.zip)

Hardware Specs and Report: [DxDiag.txt](https://github.com/praydog/REFramework/files/8694271/DxDiag.txt)

NOTE: Image in the thread are just for reference.

**Comment by praydog** [comment]
Wait until it's released.
