### ISSUE TITLE
RE7 Freezing early game

### ISSUE THREAD

**Issue by Hochgeschwindigkeitsrennfahrer** [praydog/REFramework#322]
The game freezes and becomes completely unresponsive, though the sounds still keep on playing normally as they should.

This happens in the early game where you find Mia
The freeze happens after she opens the wooden door, right after you squeeze through the shelves.

Specs:
OpenXR
WMR

Logs:
![image](https://user-images.githubusercontent.com/93285193/168805798-9007ab6a-95fd-406a-8d72-9f4886a2cbd0.png)

"[2022-05-17 13:50:02.774] [REFramework] [warning] REManagedObject:release attempted to release an object that was not managed by our Lua state" keeps on repeating forever, making the log file over 30mb big.

Dump:
No dump file due to the game just freezing

**Comment by praydog** [comment]
Fixed in 5c5f59576e57e02fd8c6f8c1ade62a3db7ea8b50. You can find it on the nightly page, I've also updated the main release with this build.

Thank you for the issue. Please re-open the issue or make another one if your game is still freezing.
