### ISSUE TITLE
Does not display to index HMD

### ISSUE THREAD

**Issue by bigdilfpapi** [praydog/REFramework#324]
When trying to use the mod with my index it does not fully display to the HMD. It shows in SteamVR the RE8 app is running but when I put on the headset it just shows the loading screen as if I'm transitioning apps.

**Comment by bigdilfpapi** [comment]
Update, uninstalled the openvr.api.dll and now it displayed the loading screen for the game but did not progress any further (The type writer that says Loading...)

**Comment by daemonatheart** [comment]
This is where I'm also at with troubleshooting this. Praydog has my log so hopefully there's a solution...

**Comment by optimumbox** [comment]
I'm glad I'm not the only one with the issue. I just opened one on RE7. I was able to play it earlier today, then it just stopped hooking properly on launch of my next session.

**Comment by daemonatheart** [comment]
I've never been able to load it into the headset. I was hoping with the release of 7 and 8 that I'd have better luck and it got fixed but no luck... Same unknown vr errors all over my log. 🙃

**Comment by optimumbox** [comment]
I may have found a fix as I was able to get it working again. The sensor right above the lenses may be giving all of us trouble. It's used to detect when the user is wearing the headset, but the mod is extremely sensitive to it for some reason. I put my headset on and slightly pulled up on the gasket material and I was able to boot in and play.

**Comment by optimumbox** [comment]
Sure, the sensor is located up where the red circle is. I still think it's a fault of the mod as I haven't had to make this kind of adjustment for any other game.

https://imgur.com/a/ECW9sFO

**Comment by daemonatheart** [comment]
No shit. It worked like a charm. Instead of messing with the gasket I stuck a cotton ball under the sensor.

**Comment by optimumbox** [comment]
If you want something even more comfortable, I just covered the sensor with painters tape. Completely fixed the issue.

**Comment by daemonatheart** [comment]
My first thought was to block it with electrical tape but it wasn't consistent. I guess the down side to the cotton ball is it blocking the air path for my front fans.

**Comment by praydog** [comment]
Might be fixed with 6ec78be9a17d7cc890d2039ffcfa87fcac3040b9

Re-open the issue if it's not.
