### ISSUE TITLE
RE7 Demo VR Controller Input Not Working

### ISSUE THREAD

**Issue by TheBLKMN** [praydog/REFramework#325]
Howdi, 
Trying to test out the mod through the demo prior to buying 4 games I wanted to experience in VR. While I'm able to load in nicely (and crank the resolution, like seriously good job optimizing everything), I have to use an xbox controller to tab through the menus, move around, and input basically. Am I the only one with this issue?

**Comment by praydog** [comment]
Unplug your controller and any other controller-like devices and it will work. I'll leave this issue open because it's not desired behavior to have to do this.

**Comment by TheBLKMN** [comment]
OH! I am so sorry! Left my Hotas X plugged in, so all the controls were probably routing into there. I feel real dumb rn. Thanks again for your hard work!

**Comment by huliqan** [comment]
> Unplug your controller and any other controller-like devices and it will work. I'll leave this issue open because it's not desired behavior to have to do this.

Thanks! I'll Try now without another  joys!

**Comment by huliqan** [comment]
...and this works!!!

**Comment by huliqan** [comment]
How to switch weapons?

**Comment by mamefan** [comment]
In the inventory screen or, if you have a recent version, hold left trigger and press directions on your left analog stick.

**Comment by praydog** [comment]
Fixed in 31324903b53e126e38df4f23488ac3069075f7c4. Re-open the issue or create a new one if you notice the issue again.
