### ISSUE TITLE
black screen 

### ISSUE THREAD

**Issue by AzDaSpaz** [praydog/REFramework#327]
i tried the resident evil 7 demo and it worked fine but the main game i boot up and the screen on my vr headset is just black i can still control and move through the pc monitor but nothing through my headset i have an oculus rift s

**Comment by Powerless001** [comment]
I am having a similar issue. When I boot the game I am getting nothing but blackness in my Quest 2, but on my computer screen it shows that it's tracking just fine, it's just not showing on the headset. I have been racking my brain to figure it out. I installed it onto my other computer, and after some fiddling I got it to work just fine. Idk why it just won't work.

**Comment by Powerless001** [comment]
> I am having a similar issue. When I boot the game I am getting nothing but blackness in my Quest 2, but on my computer screen it shows that it's tracking just fine, it's just not showing on the headset. I have been racking my brain to figure it out. I installed it onto my other computer, and after some fiddling I got it to work just fine. Idk why it just won't work.

The PC I'm trying to get it to work on is my girlfriend's, she has a beefier PC then mine, yet it works on my PC and not hers. I need help figuring out why

**Comment by DFilho264** [comment]
I "solve" that problem, changing to OpenVR. The black screen in the oculus, with the normal image in the monitor, appears only in the OpenXR

**Comment by AzDaSpaz** [comment]
iv tried both open xr gives me a black screen and open vr gives me the steam vr overlay and background i can hear the game running and can go through the menu i just cant see the game through my headset its weird as the demo worked flawlessly, i appreciate the reply

**Comment by M4st0d0n** [comment]
Hey there, thanks for the great mod,

I had the same issue and used this workaround :
https://github.com/praydog/REFramework/issues/221#issuecomment-1025136659 #

**Comment by Pandoriaantje** [comment]
> Same problem as AzDaSpaz... On Quest 2 -openvr has steamvr Overlay that shows VR judder on Desktop -openxr has a all black screen with perfect VR movement on the Desktop
> 
> Please help

Same problem here. RE7 DX11 update 2021-12-17.
REFramework 1.4 (RE7_TDB49.zip)

Is this a bug in the game/mod or openVR openXR?

**Comment by AzDaSpaz** [comment]
It's an HDR issue unplug monitor or TV before game starting the game

**Comment by praydog** [comment]
Fixed in https://github.com/praydog/REFramework/commit/163704a8521e01916abfd78ae863a46135c7228d for D3D12. Improvements will come later. Colors will still be washed out or incorrect in HDR but there will at least be video output. It will still be playable with HDR on if you can tolerate not having correct colors. HDR should still be turned off as as complete fix.

New builds can be found here: https://github.com/praydog/REFramework-nightly/releases/
