### ISSUE TITLE
free cam as positional tracking?

### ISSUE THREAD

**Issue by duig0** [praydog/REFramework#33]
hi,

i was thinking, like the gta vr mod,

could the free cam be mapped to a vr hmd?

to enable positional tracking?

this, coupled with the first person mod and a third party 3d program (vorpx, reshade, tridef etc.)

could lead to a very nice vr implimentation similar to RE7 on psvr

**Comment by Gonzaxpain** [comment]
That would be awesome, I'd die for this game with some kind of VR support.

**Comment by cercata** [comment]
> That would be awesome, I'd die for this game with some kind of VR support.

It seems it comming:

[https://streamable.com/07xuh7](url)

**Comment by duig0** [comment]
Oh man, if this is true ill be sooooo happy
