### ISSUE TITLE
How to open map in resi 7 and resi 8?

### ISSUE THREAD

**Issue by nickyb78** [praydog/REFramework#330]
Using the new motion controls mod how is the map opened with oculus controlers?

**Comment by Clodo76** [comment]
I assign the "minimap" button with SteamVR binding.
Unfortunately there are too many commands for oculus/index controllers.

**Comment by BlargleSchmeef** [comment]
For Oculus, reach over your left shoulder with your left hand and press Y

**Comment by nickyb78** [comment]
The over the shoulder way works. Thanks for letting me know :)
