### ISSUE TITLE
RE2: Can’t swap 3rd/1st person on oculus quest 2.

### ISSUE THREAD

**Issue by jmdurh** [praydog/REFramework#336]
I’m stuck at the boss that glitches out in the sewer where you need to swap 1st/3rd person.  The problem is double clicking left stick doesn’t change the view and thus, I’m hard locked at this point in the game.

Was there a button change for swapping view I’m unaware of?

**Comment by elliotttate** [comment]
You can also just switch by pulling up the mod menu or doing it from your desktop

**Comment by elliotttate** [comment]
Oh, also, if you were following the button mapping here: https://beastsaber.notion.site/Praydog-s-Resident-Evil-2R-3R-7-8-Village-VR-mods-3db8bd110ebf4a38870e1a5114b16998 then you also need to get that SteamVR button profile

**Comment by dtdman420** [comment]
Take the headset off and press insert on your keyboard to bring up the mod menu in the desktop window. From there you can disable/enable 1st/3rd person views.

**Comment by mamefan** [comment]
Point at your left hand with your right hand to bring up a menu to change things like 3rd/1st person.
