### ISSUE TITLE
RE7 & RE8 Gamepad Bodies Issues

### ISSUE THREAD

**Issue by N4RJoM** [praydog/REFramework#338]
RE7 & RE8 have missing bodies and arms cut off at the upper wrist. This makes all arm animation and cut-scenes strange to watch. Also, on RE8, the upper arm on Ethan is black with a gradient. Very weird.

**Comment by praydog** [comment]
Intended so the player doesn't clip through the body. Doubly intended when using a gamepad because of hard-to-solve issues with repositioning the body.

RE8 can be fixed with this: https://www.nexusmods.com/residentevilvillage/mods/123
