### ISSUE TITLE
RE villiage keeps crashing after installing the VR mod

### ISSUE THREAD

**Issue by CharlotteLiuok** [praydog/REFramework#352]
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/8777302/re2_framework_log.txt)
RE villiage keeps crashing after installing the VR mod. Please help me with the trouble shooting. Really looking forward to this game.
My CPU is AMD Ryzen 7 5800 8-core processor, GPU is RTX 3070ti.

**Comment by xeoburn** [comment]
thats a framework log for re3, link the village log

**Comment by CharlotteLiuok** [comment]
problem solved. Just purchased the game.
