### ISSUE TITLE
Left handed support for RE7

### ISSUE THREAD

**Issue by gme1999** [praydog/REFramework#356]
Just wondering if there was a way to swap controller input to the left hand, being left handed its currently pretty hard to play without having that option.

**Comment by HaraRMC** [comment]
same here , would be nice thou !

**Comment by praydog** [comment]
Duplicate issue #347

**Comment by gme1999** [comment]
Any updates on this?

**Comment by HughVR** [comment]
[Praydog](https://github.com/praydog)

Dear! How to solve the problem of left-handers? Can you reply instead of redirecting from the same topics?))
