### ISSUE TITLE
API does not line up with Object Explorer 

### ISSUE THREAD

**Issue by hntd187** [praydog/REFramework#358]
I have found that searching and calling methods from the API sometimes leads to unexpected weirdness. 

Additionally, the PTRs for finding these and managed singletons don't seem to lineup with the object explorer. I'm confused as to whether or not I am doing something wrong, but here is an example. 

```C++
auto rank_points = API::get()->tdb()->find_method("app.ropeway.GameRankSystem", "get_RankPoint");
auto vm_ctx = API::get()->get_vm_context();
auto rp = rank_points->call<float>(vm_ctx);
```

This call does not return anything. The pointer for this function doesn't line up with what the object explorer shows me either. On the flip side the method for getting current HP does work, but the pointers still do not line up. 

Am I misunderstanding this or doing something wrong?

**Comment by hntd187** [comment]
Thanks Preydog, the documentation wasn't 100% clear that was what needed to happen. So the pointer line-ups aren't important then?

**Comment by praydog** [comment]
Yeah, I'm aware. Not many people are using the plugin system at the moment so issues like this help. Most people are using the Lua scripting portion instead as it's easier to get into and a lot of the details like you're running into here are abstracted away.

What do you mean by pointer line-ups?

**Comment by hntd187** [comment]
I mean in the object explorer vs. what I see from what the API returns. It's not a huge deal just figured I'd ask just to make sure it wasn't something I had to keep in mind under certain circumstances.

**Comment by praydog** [comment]
> The pointer for this function doesn't line up with what the object explorer shows me either.

I believe the pointer the Object Explorer gives you is the raw function pointer. The pointer returned by the API is the actual metadata structure for the method itself. `rank_points->get_function_raw()` or `rank_points->get_function<void*>()` would get you the pointer provided by the object explorer, which is the actual function you can call.

**Comment by hntd187** [comment]
Okay cool, that all looks good. thanks for the help!
