### ISSUE TITLE
RE2: Switch floor on map

### ISSUE THREAD

**Issue by darkmetalman** [praydog/REFramework#360]
Hello!!
Is there a way to switch the floor while viewing the map?
I can't find any key combination that works.

Regards!!!

**Comment by mamefan** [comment]
Hold left trigger and use right analog. Use the latest version.

**Comment by mamefan** [comment]
Probably an answer here https://bit.ly/REVRMod

**Comment by darkmetalman** [comment]
Hello! I found a workaround by selecting another controller key binding through steam. Now I can change the map by pressing the right thumbpad twice, Thanks!

**Comment by mkaflowski** [comment]
Doesn't work for me. I have tried v1.514 and stable. How to fix that?
