### ISSUE TITLE
the mod is not working

### ISSUE THREAD

**Issue by samir310** [praydog/REFramework#361]
the mod is not working with cracked version of the games

**Comment by mamefan** [comment]
Buy the game.

**Comment by samir310** [comment]
i don't have money

**Comment by mamefan** [comment]
Get a job.

**Comment by samir310** [comment]
you think its that easy to get one not all people live abeautiful life you have

**Comment by BoobyMcJackson** [comment]
> Get a job.

That's not the point. You cannot own the version you buy on Steam. Cracking is the only way to own a DRM-free version of this game. The cracked version should be supported for preservation's sake alone.

**Comment by mamefan** [comment]
Are you old enough to get a job?
