### ISSUE TITLE
RE7 cant use inventory

### ISSUE THREAD

**Issue by HaraRMC** [praydog/REFramework#362]
when using Oculus quest 2 controllers , I can open inventory but can't use any item from it , can't change weapons , tried different buttons combinations , nothing works.
Anybody had same problem ?
Any solutions ?
TNX !

**Comment by praydog** [comment]
Changing weapons is LT + joystick. If you tried to heal at all during the first Mia fight, you won't be able to use anything, you need to reload your save.

**Comment by HaraRMC** [comment]
tnx praydog , will try that !

**Comment by HaraRMC** [comment]
LT + joysick works like a charm !
TNX a million man .
