### ISSUE TITLE
Sorry but appears a Trojan emotet in re7&8

### ISSUE THREAD

**Issue by Iannnnnnnnnnnnnn** [praydog/REFramework#374]
In this website tells me that the zip is infected, i would appreciate if you could remove it, thanks for your amazing work

https://www.virustotal.com/gui/file/d7bd6d07f47012d8a186126aaaff2c4facff8f739dd893ecc478a21c86f342f7/detection

**Comment by praydog** [comment]
There's only one vendor that sees it as one, and it's only on the OpenXR DLL. Not an issue.

**Comment by praydog** [comment]
And download the nightly build if you're afraid, it's compiled and uploaded on GitHub's own servers, not my PC: https://github.com/praydog/REFramework-nightly/releases
