### ISSUE TITLE
Game immediately crashes when booting (RE2)

### ISSUE THREAD

**Issue by puzyckid** [praydog/REFramework#381]
I've done a clean install for RE2, RE7, and RE8 a couple times now and whenever I export the appropriate zip folder contents to the steamapps/common/[game] folder, I instantly crash. I am using version 1.2.

My PC has an RTX 3080, R7 3700X, and 32GB of memory, and I am using an Index as my headset.
(I had to convert reframework_crash.dmp to a .txt file for github)
[reframework_crash.txt](https://github.com/praydog/REFramework/files/8895988/reframework_crash.txt)
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/8895976/re2_framework_log.txt)

**Comment by praydog** [comment]
https://github.com/praydog/REFramework-nightly/releases/
