### ISSUE TITLE
framework error unable to find update transform pattern

### ISSUE THREAD

**Issue by hedtrip** [praydog/REFramework#384]
Hi, i cant use vr mod for RE2
Maybe because the game is updated?
Any solution?
Thanks a lot

**Comment by hedtrip** [comment]
Thanks, will try to downgrade my game.

**Comment by Micahelj12** [comment]
> @resident Evil VR Important: A new update for all the Resident Evil games (besides Village) just came out. It looks like all previous games have been updated to the RE 8 Village engine and thus all the VR mods will need to be updated before they will work. Do not update until Praydog says it's safe to do so stuck_out_tongue . See the official guide here how to make sure Steam doesn't update https://store.steampowered.com/news/app/418370/view/3351254920159811049
> 
> If you accidentally updated already, you can easily revert your game to the previous version using Steam Depot Downloader here: https://github.com/mmvanheusden/SteamDepotDownloaderGUI

Its also first person and third person camera not functioning with new patch

**Comment by zenroch** [comment]
Anyone have any luck rolling back the DLC content for RE7?

**Comment by praydog** [comment]
https://github.com/praydog/REFramework-nightly/releases/
