### ISSUE TITLE
Anti-Aliasing Not Working

### ISSUE THREAD

**Issue by erictheaussie** [praydog/REFramework#389]
Reframework seems to disable every anti aliasing option. Checked RE2 and 3 and both had this issue.

reframework uninstalled with TAA enabled
![reframework disabled](https://user-images.githubusercontent.com/107562099/173846770-815221fb-e619-47ce-a8ac-269383eab6fc.png)

reframework installed with TAA enabled (but not working)
![reframework enabled](https://user-images.githubusercontent.com/107562099/173846829-63a6998b-bc19-4cb5-aa57-b388e37a3101.png)

I tried 10 different releases from the nightly builds and they all had this issue even from the newest release to the oldest available 1-d29c481. Versions 1.2 and 1.1 on the official releases page both have this issue too. v1.06.3 from Jul 2021 does not.

**Comment by praydog** [comment]
Delete the `re2_sharpness_removal.lua` from your `reframework/autorun` folder.
