### ISSUE TITLE
Framework not initializing

### ISSUE THREAD

**Issue by mjanek20** [praydog/REFramework#398]
Hi,
I've bought the game today to play exclusively in VR and unfortunately it's not working. REFramework is not initializing. Yesterday there was an update. Maybe that's what causes the problems
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/8933299/re2_framework_log.txt)
.

**Comment by praydog** [comment]
https://github.com/praydog/REFramework-nightly/releases/tag/latest
