### ISSUE TITLE
RE2 VR Showing in compressed window

### ISSUE THREAD

**Issue by BoscoFanelli** [praydog/REFramework#402]
Problem solved for anyone else experiencing similar issue:

It turns out that the latest update from Capcom on Steam disables the VR mod because they restructured a lot of the files. However, if you go to Properites>Betas on steam you can select the dx11 rollback and the VR will work again.

Original post:

Using an Oculus Quest 2, i7 12th gen processor, Nvidia 3070ti.

RE2 VR mod was working fine last time I played 6/11/22. Tried to start it today and RE2 would not load in VR. I was getting REFramework error: unable to find updatetransform pattern.

Downloaded latest files and replaced the files in the RE2 installation folder.

VR now starts but everything is viewed as if I'm looking at a desktop where the vertical ratio is "squished" and there are black bars above and below the "screen." The controllers and everything else works fine, but it is unplayable like this.

Any assistance would be much appreciated because I was really enjoying the mod and it worked perfectly.

**Comment by praydog** [comment]
Turn off borderless windowed mode. If that doesn't work, change the in-game resolution around.

**Comment by BoscoFanelli** [comment]
Thanks for the quick response. It looks like rolling back the update solved the issues.

Thanks again.

**Comment by praydog** [comment]
This should be fixed in the latest nightly as well if you happen to go back to the newest.
