### ISSUE TITLE
Unreliable menu summoning

### ISSUE THREAD

**Issue by cpeng03d** [praydog/REFramework#403]
I am on WMR, I think the menu summoning is too fickle.
The game I tested is RE2 remake, TDB version (non-ray tracing)
I did what described in toubleshooting page
"Aim at the palm of your left hand with your head and your right hand. Do not press anything, and an overlay menu should show up."

I successfully summone menu once. 
after clicking something on the menu, I cannot summon it again with the same hand gesture.
It seems one time deal and broken.
Can anyone help? Thanks.

**Comment by praydog** [comment]
Duplicate issue #396
