### ISSUE TITLE
RE7 lighting / shadow bug

### ISSUE THREAD

**Issue by AndersMalmgren** [praydog/REFramework#408]
https://www.youtube.com/watch?v=jhHDothVVXA

**Comment by QBCPotate** [comment]
i have this on the latest version even without reframework installed
something tells me it's a bug in the game itself, trying to find a solution online rn

**Comment by AndersMalmgren** [comment]
> i have this on the latest version even without reframework installed something tells me it's a bug in the game itself, trying to find a solution online rn

Yeah since i discovered this i also tried without VR mod and the artifact is present there too
