### ISSUE TITLE
Mouse not working

### ISSUE THREAD

**Issue by Rex000** [praydog/REFramework#41]
I can move the mouse pointer on screen and use the framework's menu but the mouse is not working in-game at all.

**Comment by cobryan05** [comment]
I was able to get the mouse working again by commenting out 

```
    // If we are ignoring input then we call the original to remove buffered    
    // input events from the devices queue without modifying the out parameters.
    if (m_isIgnoringInput || m_doOnce) {
        device->Unacquire();
        device->SetCooperativeLevel(m_wnd, DISCL_FOREGROUND | DISCL_NONEXCLUSIVE);
        device->Acquire();

        m_doOnce = false;
    }
```
in DInputHook.cpp.

Not really sure exactly what it's trying to do here, but the 'Unacquire, Reacquire' appears to break the mouse, regardless of whether SetCooperativeLevel is there or not.

I suspect it's something to do with that block of code running regardless of what device it's operating on. For example, if I let that code run the second call to the function (which is another device) it doesn't break the mouse. However, I didn't investigate enough to know what device is being passed in each call. I also don't know if I'm breaking anything by removing that line.

I'm attaching a build with that block commented out. Hopefully it gets you going, and hopefully it doesn't break anything.

[dinput8.zip](https://github.com/praydog/RE2-Mod-Framework/files/3999116/dinput8.zip)

**Comment by Rex000** [comment]
Mouse appears to be working now. Hope there is no other issue now. Thanks cobryan05!

**Comment by muhopensores** [comment]
Do you happen to play without steam overlay? This seems to only happen when the game is run without it. Doing this thing also helps it seems
```
    if ((m_isIgnoringInput || m_doOnce) && (size == 256)) {
        device->Unacquire();
        device->SetCooperativeLevel(m_wnd, DISCL_FOREGROUND | DISCL_NONEXCLUSIVE);
        device->Acquire();

        m_doOnce = false;
    }
```
Can you test this one also?
[dinput8.zip](https://github.com/praydog/RE2-Mod-Framework/files/4007511/dinput8.zip)

**Comment by Rex000** [comment]
No, it's not working.

**Comment by kevmuller** [comment]
im having trouble, i had the same issue with the mouse not working in game, but now i updated the dinput file and now the first person isnt even working, i dont get a fov slider or anything in the REFramework widget, pretty much just the enable and disable toggle switch but its not doing anything
