### ISSUE TITLE
Oculus Quest - no motion controls for RE3

### ISSUE THREAD

**Issue by Kronbonger** [praydog/REFramework#411]
Hello!

Fired the game up for the first time. Unzipped the file and placed content into the RE3 file. Fired up through steamVR and loaded game. Game seemed to load fine, though that one screen in the top left that videos have said to put on "first person" did not have that option. Everything seemed to run fine in that I was able to move the character into the bathroom and to the apartment door. However, when i tried to move my hands, arms stayed at side. Running quest 2 through airlink.

**Comment by mamefan** [comment]
That's normal for the apartment. Leave the apartment.

**Comment by Kronbonger** [comment]
Hey thanks for the fast reply. I left the apartment and it was in third person from when nemesis (think that's his name) came until being chased into the jack bar. Is that normal too?

**Comment by mamefan** [comment]
Yeah. You can change it to 1st person in the left hand menu. Point your right hand at your left hand. It'll mess up some cutscenes though.

**Comment by Kronbonger** [comment]
So tried pointin my right hand in towards my left wrist in all sorts of ways and that VR menu will not pull up. WHen I load into the game, I can see it on the capcom screen for maybe half a second.

**Comment by mamefan** [comment]
point at palm and keep left palm facing you
