### ISSUE TITLE
RE7 - only half refresh rate

### ISSUE THREAD

**Issue by HaraRMC** [praydog/REFramework#412]
Hello !
Just a question,  is there any reason why game menu works on 90Hz , but as soon as game is loaded and starts , it goes to half refresh rate , 45FPS
Same thing is when I change to 80Hz , it plays with 40FPS.
Thank you for all your work , hope to get answer for this problem.

**Comment by d0x360** [comment]
Sounds like vsync is on or ASW is engaging because you aren't hitting the native refresh rate of the HMD.    If you're on the Rift S try downloading oculus tray tool and disable ASW.

**Comment by HaraRMC** [comment]
well , I have Oculus Quest , in OTT asw is disabled , in Half life Alyx everything is fine , 90 fps , this only happenes in RE 7 and my driving games Dirt Rally 2 , Project cars 2 
Tried many things from net , nothing helps yet.
