### ISSUE TITLE
Missing Map button in RE7

### ISSUE THREAD

**Issue by AndersMalmgren** [praydog/REFramework#414]
I cant seem to bring up the map.

**Comment by praydog** [comment]
Move your left hand over your left shoulder and press the inventory button. You can also bind it to an individual button.

https://cursey.github.io/reframework-book/troubleshooting/VR-Troubleshooting.html#gestures-1

**Comment by AndersMalmgren** [comment]
Maybe could add a little section with the controls to the VR menu?
