### ISSUE TITLE
RE7 crazy wonky camera tilt

### ISSUE THREAD

**Issue by A1450** [praydog/REFramework#415]
My head is parallel to the table in vr meaning the whole room is tilted sideways. All of insert menu options on pc are unselectable. Oculus quest 2 via virtual desktop

**Comment by praydog** [comment]
Enable "decoupled camera pitch".

Use the VR menu if you need to change settings. If you still can't do that, then change settings in re2_fw_config.txt

https://cursey.github.io/reframework-book/troubleshooting/VR-Troubleshooting.html

**Comment by A1450** [comment]
Thanks so much
