### ISSUE TITLE
Oculus controller vibration for RE7 removed post RT update

### ISSUE THREAD

**Issue by Ubernoodles** [praydog/REFramework#417]
I was suprised & very grateful to see how quickly praydog got the mod working again after the RT update, however, I noticed oculus controller vibration in openxr for RE7 has since been removed. I just wanted to check that this is correct & not just an issue with my individual installation. Many thanks all
*it appears oculus controller vibration is still present with SteamVR.

**Comment by praydog** [comment]
Fixed in 79a9fbf74835b82d9155f7862119477a057575a9
