### ISSUE TITLE
RE7 Demo Crashing

### ISSUE THREAD

**Issue by PenguinVEVO** [praydog/REFramework#418]
Hey, I'm having an issue with RE7 Demo. I extracted the files for the RE7 mod into the demo folder and when I launch the game, the game does not appear in the headset and the game crashes before the first disclaimer screen is about to disappear.

Here's my crash data:
[crash_data.zip](https://github.com/praydog/REFramework/files/8984910/crash_data.zip)

**Comment by praydog** [comment]
Use the `re7_tdb49.zip` release when playing the demo.
