### ISSUE TITLE
MHRSB crash

### ISSUE THREAD

**Issue by RRReyesC** [praydog/REFramework#425]
I extract .dll file into game folder and the game crashed when initializing the REFramework
it said Failed to initialize REFramework on DirectX 12 in log

**Comment by amelecanape** [comment]
yeah i downloaded the "sunbreak-fix" file but it still crashes

**Comment by talran** [comment]
Fix is still in progress and as of right now two commits ahead of master.

**Comment by coavins** [comment]
The crashing appears to have stopped for me as of 8c03ad5, I'm able to open the developer tools to start fixing my mod for Sunbreak. Thank you @praydog!

Fair warning, I would advise against using this branch for normal gameplay until we get the all clear. It's probably not done and could possibly endanger your save file.

**Comment by praydog** [comment]
Fixed.

**Comment by kuuji** [comment]
Thanks a lot for that @praydog . Works flawlessly! Real MVP :+1:
