### ISSUE TITLE
Monster Hunter Rise crash at the startup

### ISSUE THREAD

**Issue by jochuan** [praydog/REFramework#428]
After the update of the game it is crashing on launch and even with the updated RE framework with support for sunbreak it still crashes. The only thing that i am trying to use is this https://github.com/KrossX/Durazno and if i remove the dll from inside the folder of the game and let the game run with only RE framework without anything else, it works.

[reframework_crash.zip](https://github.com/praydog/REFramework/files/9030461/reframework_crash.zip)

**Comment by praydog** [comment]
I need the log too. `re2_framework_log.txt`

**Comment by praydog** [comment]
ALso, I think a temporary way to fix this is to drop the DLL(s) needed into the `reframework/plugins` directory. The files loaded in here will go through the anti-crash system.

**Comment by jochuan** [comment]
> Also, I think a temporary way to fix this is to drop the DLL(s) needed into the `reframework/plugins` directory. The files loaded in here will go through the anti-crash system.

I tried to do that before the update but looks like the dll can't read the settings from it's config.ini or something like that and because of this it doesn't work.
And here is the log
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/9030985/re2_framework_log.txt)

**Comment by praydog** [comment]
Please try the latest build here and see if the issue persists. https://github.com/praydog/REFramework-nightly/releases/tag/latest

**Comment by jochuan** [comment]
> Please try the latest build here and see if the issue persists. https://github.com/praydog/REFramework-nightly/releases/tag/latest

It worked, thank you very much
