### ISSUE TITLE
MHRise breaks when vieweing arrays

### ISSUE THREAD

**Issue by Khanoz** [praydog/REFramework#431]
Breaks when looking at array (maybe might just be this specific array):
HuntingLogManager > Save data (the data not the manager) > Hall Weapon Usage

Tried with both nexusmods release and the one here from a few hours ago. But i removed all the vr luas and dlls as well as the sharpness removal since it crashed the game on launch but i left all of the utility files intact, which are not present in the nexusmods download

**Comment by praydog** [comment]
Fixed in 68fea1c2897b747e0192b88426843e3f5b5b4e71
