### ISSUE TITLE
Crash on startup of MHR SB

### ISSUE THREAD

**Issue by servel333** [praydog/REFramework#433]
* REFramework version: REFramework-26-1-2-2-1656811492
* Platform: Steam Deck running on Proton
* Proton version: Experimental (July 3 2022)
* Proton Version: 7.0-3
* Game: Monster Hunger Rise: Sunbreak
* `steamapps/common/MonsterHunterRise/reframework` folder exists but is empty

Game crashes with `dinput8.dll` in the MHRSB directory. It compiles shaders, shows teh logos, and crashes at the small dialog

> Loading...
> Do not quit the game

There is no Reframework crash report, but the MHR crash reports are attached. [CrashReport.zip](https://github.com/praydog/REFramework/files/9035335/CrashReport.zip)

Let me know what other information you need.

**Comment by servel333** [comment]
And thank you SO MUCH for maintaining this mod.

**Comment by servel333** [comment]
Also attempted with the [nightly build](https://github.com/praydog/REFramework-nightly/releases).

* REFramework MHRISE nightly v1.195-419fe8e

This time, it crashed at the Capcom logo, before the loading dialog listed above.

[2022_0703_1457.zip](https://github.com/praydog/REFramework/files/9035352/2022_0703_1457.zip)

**Comment by servel333** [comment]
And, just to be clear, the game does not crash after I delete the `dinput8.dll` file.

**Comment by praydog** [comment]
Can you try this build and report back? https://github.com/praydog/REFramework/suites/7185405935/artifacts/286771125

You should also have an `re2_framework_log.txt` in your game folder from REFramework.

**Comment by cat-tired** [comment]
I have a similar issue, with few differences.
I'm trying to run the game on win7 through vkd3d(2.6), which was completely fine pre-SB thanks to your third party dll fix. 
Now, MHR crashes exactly in a way described above: game starts, compiles shaders, shows logos, and crashes at pre-menu loading screen. Sometimes, it does that at earlier point during one of the logos.
One more difference is that the problem occurs even without REFramework's `dinput8.dll` , in which case Capcom's Crash Report Tool shows up and displays an unsuccessful crash report message with Error Code: 0x20000.
Since I can't run the game without vkd3d and required dxvk dlls, I can't confirm state of affairs otherwise.
The following files are generated with use of `dinput8.dll` linked above.
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/9036140/re2_framework_log.txt)
[reframework_crash.dmp.zip](https://github.com/praydog/REFramework/files/9036144/reframework_crash.dmp.zip)

**Comment by praydog** [comment]
Knowing that VKD3D crashes it on Windows is a good first step, I'll see if I can replicate the same problem on W10.

**Comment by servel333** [comment]
Re doesn't generate any files, but I'll try with that build.

**Comment by servel333** [comment]
> Can you try this build and report back? https://github.com/praydog/REFramework/suites/7185405935/artifacts/286771125

Tried with this build, and got a crash at the `Loading...` dialog.

The crash dialog says `Error Code: 0x2000000` if that helps any...

There is no `re2_framework_log.txt` file in the MHRSB folder.

**Comment by servel333** [comment]
I want to make sure you're aware, I'm not running under Windows. I'm MHR SB on a Steam Deck running Arch Linux and proton. It worked before the Sunbreak update though.

**Comment by cat-tired** [comment]
Are you sure that REFramework initializes properly? It may be the case of proton/wine trying to use its own dinput8 implementation, in which case there's a helpful suggestion I saw at nexus forums:

> If you're looking to use this mod on the Steam Deck or Linux with Proton, you have to enable loading it in Steam's Launch Options.  Right  click the game in the Steam Library, then select Preferences.  Cut and paste "WINEDLLOVERRIDES="dinput8=n,b" %command%" into the Launch Options box without the surrounding double quotes.

**Comment by praydog** [comment]
@cat-tired and @servel333 please try the latest build here: https://github.com/praydog/REFramework-nightly/releases/tag/latest

**Comment by cat-tired** [comment]
First launch has crashed even before any window appeared.
[re2_framework_log_1.txt](https://github.com/praydog/REFramework/files/9037821/re2_framework_log_1.txt)

Second try did launch the game, but it crashed as soon as I glimpsed the intro picture.
[re2_framework_log_2.txt](https://github.com/praydog/REFramework/files/9037878/re2_framework_log_2.txt)
[reframework_crash_2.zip](https://github.com/praydog/REFramework/files/9037881/reframework_crash_2.zip)

However, the third time onwards MHR works seemingly as it did before SB. I was able to load my save file, complete a mission, and then quit as expected. Logs are attached for consistency sake.
[re2_framework_log_3.txt](https://github.com/praydog/REFramework/files/9037938/re2_framework_log_3.txt)

Thank you very much for your time and effort!

**Comment by rev47** [comment]
The version on Nexus was working fine for me when it was first updated for Sunbreak, now it's crashing on launch.
Saw that there's a github page, I tried the latest nightly build, but it's the same thing.
Game opens up in a black window, holds for a couple seconds, goes fullscreen black and then simply closes with no errors.

[re2_framework_log.txt](https://github.com/praydog/REFramework/files/9038067/re2_framework_log.txt)

**Comment by servel333** [comment]
Attempted with the nightly build dated Jul 4, 2022, 5:39 AM EDT `2022-07-04T09:39:25Z`

Game crashed at the loading screen. No `re2_framework_log.txt` file was created.

I tried a few more times with this build in the directory as MHR, and it crashed each time. No RE-log file was created any of these times. I'm not sure what's going on here...

I deleted the dll and was able to get all the way into the game.

Thanks for working on this.

**Comment by Shiranui-Izayoi** [comment]
Yer the same is happening for me. It was working a couple days ago. But now it will crash when loading. Roughly around the splash screen. I have tried removing all plugins, data and autorun stuff and still crashes.

If I remove the dll it works fine. But now no matter which version on the nexus I use it won't launch. Haven't yet tried the github ones.

I have also tried reverifying files, but still nothing will update if it starts working again.

**Comment by servel333** [comment]
I tried again with tonight's nightly with the same results.

**Comment by servel333** [comment]
Attempted again with the 07 Jul 2022, 12:05AM build from Nexus. Same crash.

**Comment by rev47** [comment]
I think I solved the crashing on my end.

There was a config file generated, I deleted it and it started working.
Today it started crashing the exact same way, I deleted the config file and it started working.

The only thing in terms of settings I'm changing is that "remember menu open/close state" option.

**Comment by OnePunkArmy** [comment]
Joining this because I'm also crashing on my Steam Deck. I get the REF window to appear during the Mag/Mal splash screen, but the game crashes during the following Health Warning screen.
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/9067402/re2_framework_log.txt)

**Comment by the-science-guy** [comment]
I got everything working as described here https://github.com/praydog/REFramework/issues/229#issuecomment-1179620995

**Comment by servel333** [comment]
Tried again with the nightly from an hour ago, and also gave a try to (these instructions)[https://github.com/praydog/REFramework/issues/229#issuecomment-1179620995] and it looks like the DLL override in the Steam launch options has done the trick.

> `mangohud gamemoderun WINEDLLOVERRIDES="dinput8.dll=n,b" %command%`

IT FINALLY WORKS!!!

**Comment by OnePunkArmy** [comment]
> Tried again with the nightly from an hour ago, and also gave a try to (these instructions)[https://github.com/[/issues/229](https://github.com/praydog/REFramework/issues/229)#issuecomment-1179620995] and it looks like the DLL override in the Steam launch options has done the trick.
> 
> > `mangohud gamemoderun WINEDLLOVERRIDES="dinput8.dll=n,b" %command%`
> 
> IT FINALLY WORKS!!!

Tried again using the latest build. Still crashing like before. I've been posting in that thread already - no matter how many times I redo the steps, nothing changes. I posted my latest log in that thread.

**Comment by the-science-guy** [comment]
> Tried again with the nightly from an hour ago, and also gave a try to (these instructions)[https://github.com/[/issues/229](https://github.com/praydog/REFramework/issues/229)#issuecomment-1179620995] and it looks like the DLL override in the Steam launch options has done the trick.
> 
> > `mangohud gamemoderun WINEDLLOVERRIDES="dinput8.dll=n,b" %command%`
> 
> IT FINALLY WORKS!!!

Glad I could help :blush: 



> > Tried again with the nightly from an hour ago, and also gave a try to (these instructions)[https://github.com/[/issues/229](https://github.com/praydog/REFramework/issues/229)#issuecomment-1179620995] and it looks like the DLL override in the Steam launch options has done the trick.
> > > `mangohud gamemoderun WINEDLLOVERRIDES="dinput8.dll=n,b" %command%`
> > 
> > 
> > IT FINALLY WORKS!!!
> 
> Tried again using the latest build. Still crashing like before. I've been posting in that thread already - no matter how many times I redo the steps, nothing changes. I posted my latest log in that thread.


You might wanna edit / update your comment that you got it working in this thread too :smiley:

**Comment by servel333** [comment]
I installed a bunch of mods and now the game won't start, but it's no longer REFramework I'm fighting with. I'll have to take it one mod at a time.

It seems to be ok with me. Sucks it takes a dll-override to get it working on Proton, but it still boggles my mind how it could have possibly worked before the Sunbreak update, when I had no dll-override set up.

**Comment by servel333** [comment]
> Glad I could help 😊 Just a small note, to implement links you need to swap the brackets with the paraentheses, thus [ word ] ( url ) not the other way around. Also github recognizes the issue links directly, so just pasting the url alone is enough to point towards the issue and comment [#229 (comment)](https://github.com/praydog/REFramework/issues/229#issuecomment-1179620995)

I always get those confused for some reason, but usually I check if I'm not sure. I think this is the case of confidently incorrect. Lol.

**Comment by the-science-guy** [comment]
> I installed a bunch of mods and now the game won't start, but it's no longer REFramework I'm fighting with. I'll have to take it one mod at a time.
> 
> It seems to be ok with me. Sucks it takes a dll-override to get it working on Proton, but it still boggles my mind how it could have possibly worked before the Sunbreak update, when I had no dll-override set up.

For me it would not work pre-Sunbreak without the Override, maybe it is just a loading (order) issue for you after the update? Seems like some mods may need to be updated to work with the new content as the framework itself works fine, I only have 3 mods:
1. Carve Timer Skip and Fast Return
2. VIP Dango Tickets
3. Rise Tweaks to unlock FPS in the menu screen / cutscenes and adjust image quality percentage more finely

**Comment by servel333** [comment]
Turns out it works on the deck in desktop mode, but does not work in gaming mode. I'm not sure why, but I can play it in desktop mode.

**Comment by the-science-guy** [comment]
> 

Maybe because gamescope runs as wayland and desktop mode as Xorg? I might be totally wrong since I heard this in some video long ago. But hey, at least there is some workaround that seems to function

**Comment by servel333** [comment]
@the-science-guy I'm very happy that there is a workaround and it's good enough. Eventually I'll unstill most of the mods so I can play in gaming mode, but I'm working toward regaining the progress I had on my Nintendo Switch, so not yet.

Thanks for all the help, from everyone.

**Comment by servel333** [comment]
Finally got it to generate a crash dump! I hope this helps!

[reframework_crash.zip](https://github.com/praydog/REFramework/files/9224710/reframework_crash.zip)

**Comment by servel333** [comment]
@praydog FYI, new crash dump here.
