### ISSUE TITLE
[MHRISE] Loading plugin dll fails on proton

### ISSUE THREAD

**Issue by hfn92** [praydog/REFramework#434]
I'm using commit a68d3c7 as referenced here https://www.nexusmods.com/monsterhunterrise/mods/26?tab=files

While lua plugins work just fine dll plugings just won't work.

I looked into it and it fails loading the function from the library here: https://github.com/praydog/REFramework/blob/29631003d2ef98105f4780652d2cfc8efcff438b/src/mods/PluginLoader.cpp#L633
(An Error log would be great here)

Removing this line 
https://github.com/praydog/REFramework/blob/29631003d2ef98105f4780652d2cfc8efcff438b/src/mods/PluginLoader.cpp#L595
fixes it for me.  The plugin works fine now.

Any Ideas? I'm honestly not sure what that function does :D

Thank you

**Comment by praydog** [comment]
That function unlinks the DLL from the operating system's module list. MHRise uses it to crash your game if a DLL is loaded inside the game directory, and only the root game directory. I will probably remove that line now that I've recently understood this.
