### ISSUE TITLE
RE7: Mouse locked in the middle of screen

### ISSUE THREAD

**Issue by AnticOwl** [praydog/REFramework#435]
Hello,

I downloaded the last RE Framework for RE7 (not the nightly build) and while in game, the mouse stays locked in the middle of the screen. No way to move it to the framework window.

But, when in pause or main menu, no problem at all.

Ideas?

PS: Input passthrough doesn't work either

**Comment by praydog** [comment]
Extract this into your RE7 folder https://github.com/praydog/REFramework-plugins/releases/download/v1.0.5/reframework-disablesetcursorpos.zip
