### ISSUE TITLE
RE8 VR dos't work nightly

### ISSUE THREAD

**Issue by huliqan** [praydog/REFramework#437]
All RE works fine,but RE8 no works after v1.122-dbc2265
win10x64 21H2 | i5-4670K 4.5GHz | 16Гб DDR3 | MSI GTX1080ti GAMING X 11G | Oculus Quest2

**Comment by huliqan** [comment]
All RE works fine,but RE8 no works
win10x64 21H2 | i5-4670K 4.5GHz | 16Гб DDR3 | MSI GTX1080ti GAMING X 11G  | Oculus Quest2

**Comment by praydog** [comment]
Post your `re2_framework_log.txt`

**Comment by huliqan** [comment]
Works after delete all VR-files,install
v1.122-dbc2265 run set and close
install
v1.200-d39b784 run= works ! )))
Thanks you very much!!!

**Comment by huliqan** [comment]
but  I observe frequent picture breaks (in 1.122  much less often)
