### ISSUE TITLE
RE2 and RE8 rainbow oculus quest 2 display issue.

### ISSUE THREAD

**Issue by HairlineBandit** [praydog/REFramework#440]
So, my issue is that RE2 and RE8 have this graphical error where the game runs and looks fine on my monitor, but on my quest 2, everything looks like a rainbow splurge. I'm guessing the textures didn't load right in my headset, but everything is just like neon rainbow colored, super bright. RE3 VR doesn't load at all but I'll worry about that later. 

(Note that I'm using an AMD GPU)

I've tried using both OpenVR and OpenXR files to no avail. HDR is off both in game and on my windows setting as Radeon Adrenaline has no HDR settings. Ive played with the color settings in the game settings which did not work either. 

[re2_framework_log.txt](https://github.com/praydog/REFramework/files/9059018/re2_framework_log.txt)

**Comment by praydog** [comment]
Duplicate issue. #307
