### ISSUE TITLE
MH Rise crashes when attempting to load RiseCharmEditorREF.dll under Proton/Linux 

### ISSUE THREAD

**Issue by v1ld** [praydog/REFramework#442]
REF GitHub dev build c145803 as downloaded from Nexus crashes if Charm Editor and Item Cheat is installed under plugins/ on Proton/Linux.   The crash log and dump are attached.

Before this version, REF would show the plugin as loaded but it would never open a window.  The crash is good in that it shows there's a problem.  I saw the [ Fix plugins not loading on Proton](https://github.com/praydog/REFramework/commit/d39b784d9a98cd9bfe0dd9e9f4feed12ff8ede65) commit - it's possible that this would work on the Deck, as I'm running on a desktop LInux.

As can be seen in the log file, Lua-based mods work with no problems at all if the Charm Editor files are removed.

[re2_framework_log.txt](https://github.com/praydog/REFramework/files/9075707/re2_framework_log.txt)
[reframework_crash.dmp.zip](https://github.com/praydog/REFramework/files/9075709/reframework_crash.dmp.zip)

**Comment by praydog** [comment]
There was a recent MHRise update. I would check the Nexus page to see if there are any issues with it. @Fexty12573 may also be using some APIs that are not compatible on Linux, not sure.

**Comment by Fexty12573** [comment]
The only Windows APIs I am using (directly) are `OutputDebugStringA`, `GetOpenFileNameA/GetSaveFileNameA`, and then MinHook is using a bunch under the hood. So not sure. I don't have a linux environment set up to test this myself.

**Comment by v1ld** [comment]
Thanks for the responses, folks.  Doesn't look like there's a simple way to debug this, so I'll go ahead and close it.

**Comment by v1ld** [comment]
@praydog @Fexty12573  The latest version of REFramewok, the one with the large filepaths fix, allows Charm Editor to load and function perfectly in Linux/Proton.  I happen to be running Arch Linux, which is the underlying OS for Steam OS 3, so there's a very good chance this will allow DLL loading on the Deck as well.

Great news for me - I just switched to Linux for gaming and am pleased as punch.  Thanks both of you for your efforts on these two mods.  

Cheers.
