### ISSUE TITLE
Sunbreak VR graphics glitch

### ISSUE THREAD

**Issue by Hydrolutra** [praydog/REFramework#446]
Awesome mod BTW. Was working fine with Rise, since the Sunbreak update I can get VR to work ok. But there seems to be a problem with the 3D/stereoscopic effect I think. Environments look fine but my hunter and other characters have a blurry line around them, almost like two images not matching up, and my hunter, if I close one eye has hair, and the other eye has no hair.

I've tried several builds, including the nightly but have the same issue.  I've uninstalled, manually cleaned the game folder, reinstalled and only run re-framework with no other mods. I've tried openxr and openvr. I'm using a Quest 2, tried airlink and virtual desktop.

Any suggestions?

[re2_framework_log.txt](https://github.com/praydog/REFramework/files/9079578/re2_framework_log.txt)

**Comment by praydog** [comment]
It is a problem with the newer version of the RE Engine, I haven't figured out why. Same issue as #400. Closed as duplicate.
