### ISSUE TITLE
Monster Hunter Rise crashing randomly;BSOD

### ISSUE THREAD

**Issue by JuRgEnTheWaRLoK** [praydog/REFramework#456]
Hello, been having an issue with Rise and Rise alone where I can play for a random amount of time, and then at some point the game will freeze, and a BSOD will trigger with the Stop Code Memory Management. I've updated everything I can find including drivers, security and BIOS, even going as far as to run a RAM diagnostic test which turned over no results.

The mods I run on the game are few. Only REFramework, NativesFirst, and OP Kamura Bow.
Attached are the requested files as well as my windows dmp file. I offer thanks in advance to anyone who could possibly tell me what's going on.

**Comment by JuRgEnTheWaRLoK** [comment]
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/9125078/re2_framework_log.txt)

**Comment by JuRgEnTheWaRLoK** [comment]
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/9125080/re2_framework_log.txt)

**Comment by JuRgEnTheWaRLoK** [comment]
DMP Files for both Windows and REFramework:
https://mega.nz/file/7AcwVChY#of9aB0c7mGRASuh08UuGqsIW15KfyKay2cKTuPCw1jk

**Comment by praydog** [comment]
BSODs are out of scope.
