### ISSUE TITLE
MHR Sunbreak blackscreen on startup

### ISSUE THREAD

**Issue by phoenix5980** [praydog/REFramework#458]
If dinput8.dll is in the game directory, the game always freezes on startup with blackscreen.
I tried the following workarounds but still no luck:
1. Clear all mods and plugins
2. Update video card driver
3. Update DirectX 12
4. Update VC++
5. Reboot
6. Steam Game Integrity Check
7. Clean reinstall the whole game

Windows 10, 19044, GTX 1070, 4770K, BIOS Z-87 PRO

log attached
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/9125683/re2_framework_log.txt)

**Comment by perkel666** [comment]
switch off HDR

**Comment by phoenix5980** [comment]
> switch off HDR

Thanks for the advice. Unfortunately HDR option is greyed out by default, my monitor doesn't support HDR at all. 
![Screenshot 20220723140745](https://user-images.githubusercontent.com/2919202/180592949-f634ef04-5c34-48c9-92a6-22f221af249e.png)
