### ISSUE TITLE
MHR Sunbreak freezing on initialization

### ISSUE THREAD

**Issue by critcap** [praydog/REFramework#462]
Monster Hunter Rise Sunbreaks freezes at the splash screen and stops responding.
- Tried with release and nightly build.
- only placed the dinput8.dll in the folder
- also tried clean install
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/9153813/re2_framework_log.txt)

**Comment by praydog** [comment]
Please try the latest build here and see if it fixes the issue: https://github.com/praydog/REFramework-nightly/releases/tag/latest

**Comment by critcap** [comment]
Tried the build on a fresh install, still not able to further
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/9162714/re2_framework_log.txt)

**Comment by praydog** [comment]
Try shutting down "GPU Tweak III" or any ASUS tools you may have running in the background. You have a lot of DLLs loaded that aren't loaded into MHRise by default and they might be conflicting with REFramework.

**Comment by critcap** [comment]
Okay GPU Tweak III was the culprit. Everything is now working perfectly.
Thanks for your support!
