### ISSUE TITLE
In the VR mode of MHR, the GPU and CPU usage is only 50%, and the fps is as low as 30~41fps.

### ISSUE THREAD

**Issue by sweetlanzi** [praydog/REFramework#463]
Win10 21H1
R5 3600 
RX 5700XT
16G RAM
Oculus Ritf S
The fps in the VR picture is very low, which was discovered by monitoring a software called 'fpsVR' on Steam.
My GPU and CPU usage is half and sometimes lower.
But on a desktop monitor, the game is smooth, around 120fps. However, the fps in the VR display screen is only 34~41fps, and the GPU usage is not high.
It's weird. I shake the VR headset, and on the desktop monitor, the game screen movement is very normal, there is no stuttering and smoothness. On the other hand, the screen in the VR headset showed stuttering and unresponsiveness, as well as smearing.

**Comment by praydog** [comment]
Please read #147.
