### ISSUE TITLE
[VIVE COSMOS] Related issues if it can help devs ;)

### ISSUE THREAD

**Issue by TheFabs20** [praydog/REFramework#470]
Hi guys!
I will try to list here all the **Vive cosmos** issues. **Cosmos use Open XR**, so it's not a wonderful journey to play.
(Sorry for my english, i speak french ^^')

 1: The controller's key binding.
It's impossible (for me who's noob) to re-bind the controlers keys. The menu is not available in VR (known issue) and in desktop mode the menu is stretch so i can't see all the options to rebind...
Perhaps a little .txt for easy rebind is possible?  

2: Coming soon...

**Comment by praydog** [comment]
Same issues as #396, #430, and #148. Closed as duplicate.
