### ISSUE TITLE
MHR Sunbreak crash with REFramework

### ISSUE THREAD

**Issue by Nergal08** [praydog/REFramework#476]
Hi !
I extract dinput8.dll from the zip file into my Monster Hunter Rise game install folder but after launch the game, the game crash directly with a CAPCOM "CrashReport". I'm pretty sure i'm doing everything right though... Any ideas ? I really don't know how to solve this problem :/

[re2_framework_log.txt](https://github.com/praydog/REFramework/files/9212761/re2_framework_log.txt)
[2022_0728_1849.zip](https://github.com/praydog/REFramework/files/9212763/2022_0728_1849.zip)

**Comment by praydog** [comment]
Please try the newest build from here and upload your log again if you crash: https://github.com/praydog/REFramework-nightly/releases

**Comment by Nergal08** [comment]
It works !!! Thank you
