### ISSUE TITLE
MHR Fresh Install Crashes

### ISSUE THREAD

**Issue by Logan7697** [praydog/REFramework#479]
MHR Crashes either immediately, whenever I click, or whenever I load my character. I've tried downloading the newest version on here from 3 hours ago and it still crashes repeatedly. I would have added my comment to a previous identical issue but it was closed about 30 minutes before I got to it. Any Suggestions?
Edit:
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/9214677/re2_framework_log.txt)

**Comment by talynflaym** [comment]
Think I'm having a similar issue. First time trying to use REFramework, I believe I have it all installed correctly but MHR crashes consistently within ~2 seconds of launching. I tried removing all of the mods I was trying to load, then a fresh install, then the nightly version; all had the same issue.

[re2_framework_log.txt](https://github.com/praydog/REFramework/files/9214679/re2_framework_log.txt)

**Comment by praydog** [comment]
I have made some speculative fixes, please try the latest build here: https://github.com/praydog/REFramework-nightly/releases/tag/latest

**Comment by Logan7697** [comment]
That seemed to fix the issue! Only setback is it rapidly flashes now but its a step forward. Cant believe you found a solution so fast!

**Comment by praydog** [comment]
Can you upload your log again?

**Comment by Logan7697** [comment]
I just launched it now and there's no flickering, whatever it was is fixed. Thanks a ton!
