### ISSUE TITLE
Suggestion: Add info about proton

### ISSUE THREAD

**Issue by Lunatik00** [praydog/REFramework#483]
This mod works fine trough proton, but it would be desirable for regular users to know what to do, the instruction is simple:

- go to the game on steam
- right click
- properties
- write in launch options the command `WINEDLLOVERRIDES="dinput8.dll=n,b" %command%`  

And with that they will have the mod working trough proton, this is for linux users (aka also steam deck users)

It also would be great to have the instructions in the nexusmod page alongside the windows instructions, is the same plus indicating the system that an additional dll has to be loaded

**Comment by FoxStevenHY** [comment]
On my Linux desktop won't start the game with this config.
Any ideas?
Thanks

**Comment by Lunatik00** [comment]
this config tells the game to load the dll that should be used, when the game doesn't start is usually because the game was updated and the mod is not compatible with the new version, the modders tend to release a new version quickly after an update.
