### ISSUE TITLE
RE:7 on meta quest 2, no d-pad emulation ?

### ISSUE THREAD

**Issue by quotekio** [praydog/REFramework#485]
Hi,
I am currently experiencing RE7 with REFramework on meta quest 2 and so far the it was amazing, but i'm currently facing an annoying issue: i accidently disbound my gun and whenever i try to equip it, i can't seem to do it since weapon equip is done with the digital pad, which i don't have on my occulus controler.. is there any way/alternative button to make one of the analog pads temporarly act as d-pad ? i'm really stuck on this one, thank you.

**Comment by praydog** [comment]
Left trigger + joystick.
