### ISSUE TITLE
MHR Freezes at initialization.

### ISSUE THREAD

**Issue by kuhazahn** [praydog/REFramework#486]
After checking the log, it looks to be DX12 related
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/9245190/re2_framework_log.txt)
.

**Comment by praydog** [comment]
It looks related to this script: `[2022-08-02 14:37:46.299] [REFramework] [info] [ScriptState] Running script C:\Steam\steamapps\common\MonsterHunterRise\reframework\autorun\dog_gatherer.lua...`

**Comment by kuhazahn** [comment]
Thanks, I'll delete that and see what happens.  I just saw the DX thing running over and over again so my smooth brain thought that was it.

**Comment by kuhazahn** [comment]
That worked, thank you so much.
