### ISSUE TITLE
Resident Evil Village on Steam Deck, overlay won't appear.

### ISSUE THREAD

**Issue by Xbob42** [praydog/REFramework#488]
Hi, I've gotten this mod working for Monster Hunter Rise, and it was quite easy. Simply add the dinput8.dll to the game directory then add `"dinput8"="native,builtin"` to the user.reg files in the compatdata/pxr folder for the game. (I'm sure WINEDLLROVERRIDES="dinput8=n,b" in the Steam launch options probably would've worked too.)

I figured it'd be the same for Village, but despite doing the same thing, I have yet to get the overlay to appear. Obviously I'm in the compatdata folder for Village (1196590) -- but no go so far. And yes, I've tried hitting Insert.

**Comment by RyuSeisuke1992** [comment]
On the Steam Deck crash the newest nightly Build from today always at the start. But overlay is displayed.
![20221015010505_2](https://user-images.githubusercontent.com/24828026/195956303-5248eaa9-2bfc-4448-ab02-f9260d72c3a4.jpg)
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/9790675/re2_framework_log.txt)

Other game e.g. RE2, RE3, RE7 work fine.

**Comment by RyuSeisuke1992** [comment]
With the latest nighty build, bugs that crash the game and that the UI is not visible are thus solved. It works great on the Steam deck.

**Comment by RyuSeisuke1992** [comment]
@praydog please Close this Ticket. Reframework worked fine on the Steam Deck for RE8
