### ISSUE TITLE
re3 stuck in third person with no arm movement

### ISSUE THREAD

**Issue by Otomok** [praydog/REFramework#490]
I do not have any vr ability other than when i put on the headset im in game and can see all around me but the character body is still in front of me (third person) and i do not have any arm movement.

using valve index

**Comment by praydog** [comment]
Turn it on under FirstPerson. It's not on by default.

You can find this in the menu with the "insert" key or the in-game VR menu. You can also change it in the `re2_fw_config.txt` in your game directory.  https://cursey.github.io/reframework-book/troubleshooting/VR-Troubleshooting.html
