### ISSUE TITLE
Re8 vr settings 

### ISSUE THREAD

**Issue by Tucky99** [praydog/REFramework#491]
So I have a pretty beefy pc (3080 10gb 3800x) but when I play village as soon as I get to the first overlook of the castle the game starts jarring. I’m pretty new to vr (quest 2) so I don’t really know how to do my settings. I got re7 working absolutely fine with the settings I already had from my last play through but 8 is not the same at all. Can someone with a similar pc let me know the kind of settings they run?

**Comment by praydog** [comment]
This isn't an issue. Use the Discussions section for questions like this.
