### ISSUE TITLE
In version 1.3.4 crashes randomly during quests and in Ergado

### ISSUE THREAD

**Issue by h-nagasawa** [praydog/REFramework#499]
In version 1.3.4 crashes randomly during quests and in Ergado. 
I turned off DLSS with the screen mode borderless,
but although the frequency has decreased considerably 
(once every 2~3h?). Still, 
it seems to happen. Please investigate.

**Comment by h-nagasawa** [comment]
[log&dmp.zip](https://github.com/praydog/REFramework/files/9332694/log.dmp.zip)

**Comment by keezow** [comment]
[logs2.zip](https://github.com/praydog/REFramework/files/9337209/logs2.zip)
same issue, using nightly build from 8/14

**Comment by h-nagasawa** [comment]
[log&dmp.zip](https://github.com/praydog/REFramework/files/9350725/log.dmp.zip)
nightly build from 8/14
I tried putting it in, but still the crash reproduces.

**Comment by h-nagasawa** [comment]
[log&dmp.zip](https://github.com/praydog/REFramework/files/9372076/log.dmp.zip)
V1.290-7145DBD crashed during quest. We will send you a log, so please investigate.

**Comment by h-nagasawa** [comment]
very sorry. It seems I was wrong. After updating the CPU driver and the motherboard BIOS, the problem no longer reappears, so we will close this issue. Thank you very much for your response.
