### ISSUE TITLE
(Feature Request) Enable Full Animation at Distance

### ISSUE THREAD

**Issue by hyperspeedgx** [praydog/REFramework#503]
RE2R and RE3R enemies has this issue, enemies runs at half framerate at distance and 1/4 of the framerate wgen they're even distant.

REFramework already has Vignette Removal, which is amazing. so it would'be awesome if it gets support for Full Animation at Distance.

btw: Somehow RE7 and RE8Village doesn't have this issue.

**Comment by hyperspeedgx** [comment]
Pls implement it

https://residentevilmodding.boards.net/thread/16261/re2r-distance-zombies-full-framerate?page=1&scrollTo=147112

**Comment by praydog** [comment]
https://github.com/TheTedder/REFix/

**Comment by hyperspeedgx** [comment]
oh thank you!!
