### ISSUE TITLE
Object Explorer API differences

### ISSUE THREAD

**Issue by d3vacom** [praydog/REFramework#504]
Inspecting through the Object Explorer gives me a different types and number of arguments then when hooking to the method.

Object Explorer:
`snow.enemy.EnemyCharacterBase.afterCalcDamage_DamageSide(snow.hit.DamageFlowInfoBase, snow.DamageReceiver.HitInfo)`
````
sdk.hook(sdk.find_type_definition("snow.enemy.EnemyCharacterBase"):get_method("afterCalcDamage_DamageSide"),
	function(args)
		log.debug("afterCalcDamage_DamageSide")
		local enemyCharacterBase = sdk.to_managed_object(args[2])
		local afterCalcInfo = sdk.to_managed_object(args[3])
		log.debug(afterCalcInfo:get_type_definition():get_full_name()) --[11796] snow.hit.EnemyCalcDamageInfo.AfterCalcInfo_DamageSide
	end,
	function(retval)
		return retval
	end)
````

**Comment by praydog** [comment]
This isn't an issue. You're just seeing inheritance in action.

Find `snow.hit.EnemyCalcDamageInfo.AfterCalcInfo_DamageSide` in the object explorer and you'll see that it inherits from:
* `snow.hit.AfterCalcInfo_DamageSideBase`
* and finally `snow.hit.DamageFlowInfoBase`, which is what your method takes.
