### ISSUE TITLE
RE7 reticle/crosshair not showing

### ISSUE THREAD

**Issue by DaddyKage** [praydog/REFramework#523]
Hi, I've searched through here and across the net and nobody seems to be experiencing this issue any more.

For some reason I have no reticle at all in RE7, with the framework, I have tried toggling it on and off, both in game, and using the REFramework menu.

I have tried on both OpenVR, using SteamVR, and OpenXR, using Oculus (Using a Quest 2 btw).

I have tried the regular release build, and the latest nightly one.

No matter what I do I can't seem to get a reticle, everything else is working flawlessly.

It's not the end of the world, but definitely bugging me.

Absolutely loving the framework other than that!

Thanks for any help given!

**Comment by praydog** [comment]
Roll back to the old version of the game and use the TDB49 build of REFramework.

**Comment by DaddyKage** [comment]
Wow, thanks for the swift response, I'll give that a try now, fingers crossed!

**Comment by praydog** [comment]
Fixed in 8bc17ce4c0f6a62e035ba41ead1a8544c4f31330 for the newer version.
