### ISSUE TITLE
Bizarre Colors

### ISSUE THREAD

**Issue by Jamavo83** [praydog/REFramework#524]
Having the same issue with both RE7 and RE8.   If I leave the file openvr_api.dll in the folder, the game will start and display on the monitor, but the HMD (quest 2) remains on the SteamVR loading grid (deck? IDK).  I can hear the game through the headphones, but I remain in the SteamVR deck.

If I remove the openvr_api.dll file, the game will use the oculus openXR, but the colors are all crazy/tie-dye/predator heat vision looking.  I did try a few different in game settings,  Ambient occlusion set to SSAO or Off, others, no improvement.  I also went into steamvr/settings/developer and changed steamVR to my openXR choice, same issue.

Most of my testing has been with RE7, I only loaded RE8 for a moment with both openvr_api.dll present and not present to see if I had the same results, which I did.

Running a Quest 2, i7-12700K, RX 6900 XT, 32 gigs ram, windows 10 pro with 2 week old fresh install.  Thanks for any help you can provide.

**Comment by praydog** [comment]
Duplicate issue. See #307, #440
