### ISSUE TITLE
Silent crash if game folder requires admin permissions

### ISSUE THREAD

**Issue by Alainx277** [praydog/REFramework#531]
If the game is installed in a folder that requires admin permissions (ex. Program Files), it will fail to launch.

I think this happens because it reframework can't create the log file in the game directory. Due to this it also can't create a crash dump, causing the game to simply not launch.

A possible solution would be to show a messagebox if the log file can't be created. Maybe the game could also continue running, just without logging.

**Comment by praydog** [comment]
Fixed in 29dc1b19af0cfb51ccfc248a6c3c0072504c3609
