### ISSUE TITLE
RE2 Latest Nightly Branch Bugged Playermodel (rendered only in one eye)

### ISSUE THREAD

**Issue by scardigne** [praydog/REFramework#539]
[VALVE INDEX FULL KIT]
[OPENVR] [STEAMVR]

RE2 latest nightly's playermodel's missing rendering in one eye?

can be fixed enabling AFR

As an addition it would be nice to have the option to hide body/legs in re2/re3 :)

**Comment by praydog** [comment]
Duplicate issue #400
