### ISSUE TITLE
Game closing

### ISSUE THREAD

**Issue by temmieyayA** [praydog/REFramework#545]
i install the mod, start the game, 6 sec later it closes.

**Comment by FransBouma** [comment]
RE8? The new patch installed an anti-tamper system. It's currently being worked on to be fixed.

**Comment by temmieyayA** [comment]
> RE8? The new patch installed an anti-tamper system. It's currently being worked on to be fixed.

kay thanks

**Comment by temmieyayA** [comment]
i guess ill try out re7 in the meantime

**Comment by praydog** [comment]
RE8 should be fixed now. Download the latest release here https://github.com/praydog/REFramework-nightly/releases

Re-open the issue if this isn't the case.
