### ISSUE TITLE
Resident 8 vr, DLC no longer loads October 14 update

### ISSUE THREAD

**Issue by Bbl79** [praydog/REFramework#546]
Hi,

I'd like to point out that dlc no longer loads with the latest vr update for Resident evil village. Tested also without VR mod and that works. So the mod seems to be the problem.

Best regards,
B.

**Comment by praydog** [comment]
Should be fixed in a5ef2fa14ca0c7786ea0a754ae85f26b66a600bd. Download the latest nightly and let me know if it fixes it. Re-open the issue if it still persists.

**Comment by Bbl79** [comment]
Hi,

It is fixed. You're a genius. Thanks for all the hard work.

Best,
B.

Op zo 16 okt. 2022 04:04 schreef praydog ***@***.***>:
