### ISSUE TITLE
RE8 Village crashing on startup - possibly due to update?

### ISSUE THREAD

**Issue by RossieC** [praydog/REFramework#547]
Mod worked on the Steam game demo so bought full Steam version which shows game not responding or game crashes back to launch screen after first two title screens. Wonder if it could be that the demo has not been updated, but the full version has since you created the mod? Just a thought. Thanks - RossieC

**Comment by praydog** [comment]
Download the latest nightly build, I have released some fixes for this. There was an update a few days ago that added anti-tamper and other game breaking changes.

https://github.com/praydog/REFramework-nightly/releases/

Re-open the issue or create a new one if it does not fix it, or other issues appear.
