### ISSUE TITLE
No Sound when using REFramework

### ISSUE THREAD

**Issue by YBGud** [praydog/REFramework#550]
Whenever I'm booting up the cracked SF6 I am not getting sound in the REFramework mod. I am verified that it is REFramework causing this issue as when I turn off dinput8.dll I get sound back. however once I enable it, even with no other mods I lose all sounds.

Any suggestions?

**Comment by SenyaFR** [comment]
Did you find a solution ?? i have the same bug, i know that updating to sf6 works but...

**Comment by darlielpereira** [comment]
I solved it in, services > windows error reporting services. if it is disabled, set it to manual and the sound of the game works again

**Comment by YBGud** [comment]
Darlielp was right, idk why a windows error service was the issue but I got sound again thanks
