### ISSUE TITLE
RE8 Tool-- Manual Flashlight Inoperable

### ISSUE THREAD

**Issue by shantasma** [praydog/REFramework#555]
Hi! I discovered your work on these tools pretty recently, and I highly appreciate the work you've put in for these enhancements.

While I don't use the tool for VR, everything else has been a great value add. However, I can't get the manual flashlight feature to work for the life of me. I know it's bound to T by default, but other bindings don't have any effect either. The function for turning off the flashlight auto-toggle scenes works just fine, at least.

Any help would be appreciated if I fumbled something on my end, otherwise I hope this helps development!

**Comment by praydog** [comment]
Fixed in c7c8347ad17d1bf11cc9b08e30da4984041979f2

https://github.com/praydog/REFramework-nightly/releases/tag/latest
