### ISSUE TITLE
re8 crash

### ISSUE THREAD

**Issue by Steepmen15** [praydog/REFramework#558]
При открытии re8 игра не загружается в вр и загружается до логотипа capcom и закрывается.

**Comment by praydog** [comment]
Upload re2_framework_log.txt. The whole file.

**Comment by Steepmen15** [comment]
Была такая проблема с re7 но в место обычного мода re7 установил re7_TDB

**Comment by Steepmen15** [comment]
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/9893897/re2_framework_log.txt)

**Comment by praydog** [comment]
Pirated copies of RE8 are not supported by REFramework.

**Comment by Steepmen15** [comment]
Но re7 работало

**Comment by Steepmen15** [comment]
Прийдется
