### ISSUE TITLE
[Steam Deck] Null Command Queue Spam and dialog not showing up 

### ISSUE THREAD

**Issue by thndgonz** [praydog/REFramework#561]
My reframework logs seems to be flooded with a lot of Null Command Queue. It seems to be loading fine from the logs but the spam doesn't stop. 

Attach logs. 
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/9901653/re2_framework_log.txt)

I'm not sure which is the official key to bring up the dialog I just know it is responding to some keys to save the config but I can't see the UI anywhere. 

My only changes are in the launcher options of steam

`WINEDLLOVERRIDES="dinput8.dll=n,b" %command%` 

I have tried with mods and no modes. Both give the same result of spamming the logs.

**Comment by praydog** [comment]
You probably need to use a different version of Proton.

**Comment by thndgonz** [comment]
Seems the only version that works is Proton Experimental... tried most of the proton versions available provided by Valve. 

I guess my only question is if there's a way to turn off logging for this? It seems the mod _does_ work even with the null command queue spam.  I'm just asking in case the next update of Proton Experimental just takes it away and the spam is back.

**Comment by notpentadactyl** [comment]
FWIW: I have the same issue with Proton 7.0-6 (just released), but Proton Experimental [bleeding-edge] (didn't test normal Experimental) works.
