### ISSUE TITLE
RE 2 dont launch 

### ISSUE THREAD

**Issue by Nozaza83** [praydog/REFramework#576]
When i try to launch RE 2 it start re framework to initialise then crash with this message :
re2.exe 
"d:\runtimebuildroom\\\gitroot\\runtime\\modules\\render\\os\\renderservicedx12.cpp"266 Fatal D3D error (6) 
If somebody know why , i'll wait for the answer

**Comment by praydog** [comment]
Turn off any overlays you're using, like Discord, Rivatuner, ReShade, etc...
