### ISSUE TITLE
[MHR] VR drawing to the wrong screen

### ISSUE THREAD

**Issue by EmeraldLance** [praydog/REFramework#584]
In both the nightly build and the most recent stable build, MHR is drawing the VR camera to my monitor and is drawing the flatscreen recording render to my VR headset. This is only happening in MHR; other RE Engine games work as expected in VR. I'm using openxr, not openvr. No settings are forced in my Nvidia control panel.

Windows 10
AMD Ryzen 5800x, 3.8GHz, 8 core, 16 thread
RTX 3070ti, MSI build, 8GB VRAM
32GB RAM
Oculus Quest 2

**Comment by praydog** [comment]
Fixed in 287b929acd8dc5c3cd879c699943f98e6aa24d44
