### ISSUE TITLE
RE7 vr mod now only just loads on PC

### ISSUE THREAD

**Issue by harbingerthrace** [praydog/REFramework#585]
It was working totally fine for me for the main game and DLCs, but then one of the DLCs had the character fall into the walls last week and ever since then when the game starts it never goes to the headset into VR mode like it used to.  It just loads on the computer.  

I have completely uninstalled and deleted the game from my pc and reinstalled all of the VR mod files, including the latest night version, but nothing.  Steam VR opens but nothing shows up there, just on the pc.

Using Quest 2 with Virtual Desktop.   Please help!  Thanks in advance =)

**Comment by praydog** [comment]
Upload `re2_framework_log.txt`

**Comment by Plake0815** [comment]
I have the same issue with my Vive Cosmos, when starting VR I first reach the Vive port environment and once that is closed, I am in my virtual Steam home (or what it's called). Starting RE7 shows simply the vive environment as if a game is loading endlessly, while on PC the game is running...

PC details, RE7 folder content and log file attached.

![RE7 folder](https://github.com/praydog/REFramework/assets/133123936/2d2e610d-dbae-48e4-bea0-cd9b6de23021)
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/11442209/re2_framework_log.txt)
[Plake's PC details.txt](https://github.com/praydog/REFramework/files/11442222/Plake.s.PC.details.txt)

**Comment by harbingerthrace** [comment]
Same. I just unplugged the hdmi cable

**Comment by Plake0815** [comment]
Didn't help here, Vive Cosmos still just showinh the vive environment, while (plugging TV back in) the game is running on PC... :(
