### ISSUE TITLE
Crash when try to talk npc and get quest 

### ISSUE THREAD

**Issue by Dlrldnjs04** [praydog/REFramework#588]
after 2022/11/23 title update 3 in Monster hunter rise the game keep crash when I talk to NPC Chichae for getting into the mission board. The causing issue was reframework I remove "dinput8.dll " file and the game properly worked.
 
([re2_framework_log.txt](https://github.com/praydog/REFramework/files/10087119/re2_framework_log.txt))
[https://drive.google.com/file/d/1W-J5FwMBDHUtIQocoX0VVWnHR0IDLyYz/view?usp=sharing](url)
second link is reframework_crash.DMP. you may need to drag link and post on google...

I am post these crash log first time if i post wrong place then i am so sorry.

**Comment by praydog** [comment]
Try deleting the `RiseQuestLoader.dll` in the `reframework/plugins` directory.

**Comment by Dlrldnjs04** [comment]
> Try deleting the `RiseQuestLoader.dll` in the `reframework/plugins` directory.

ty so much it worked.
