### ISSUE TITLE
RE2- VR just goes to STEAMVR loading screen, OpenXR is all purple

### ISSUE THREAD

**Issue by d1andonlyantman** [praydog/REFramework#592]
As the title says, using OpenVR it just goes to the STEAMVR "Mountain range" screen. i can hear the game menu and on my monitor it shows 2 menu screens overlapping each other (presumably due to it rendering for 2 eyes), but nothing happens on the headset (Quest2). Im stuck looking at the stars. In OpenXR it loads and theVR technically works but everything in the headset is purple and objects are lots of different colours combined. It looks like a seriously bad acid trip! This is in the menus and everything. On the monitor, however, it looks fine.
Im running a 6700xt and have installed the latest drivers. ive never had an issue on any other game. If playing without the VR mod its fine. Also im using Airlink on Windows 11. Normally flawless.

Happy to donate if i get it working, it looks like a great MOD :) Thanks!
Picture below of OpenXR.

![purple](https://user-images.githubusercontent.com/119084228/204063397-213f0d31-2faa-4773-8f56-8850292da1d2.jpg)

**Comment by praydog** [comment]
Switch to windowed mode. If that doesn't work, try the solutions posted in #307

**Comment by d1andonlyantman** [comment]
Ive tried every suggestion ive seen. Its set to windowed. Ive played with the bpc and pixel format settings in AMD adrenaline. turning HDR on and off. Ive checked that HDR stay set to 0 in the ini file. I copied some other settings from a re3 ini that was said to work. Still the same. Any other suggestions or is this looking a bit bleak?

Thanks for your help either way 👍

**Comment by d1andonlyantman** [comment]
Hi. Ive tried everything i could find. Running windowed, playing with the BPC and Pixel settings in adrenaline. Ive turned HDR on and off and also checked its staying at 0 in the .ini file. I also tried a few random settings from a known to be working re3 ini, but there was no change. Any other suggestions or is this looking bleak?

Thanks for your help either way 👍

**Comment by d1andonlyantman** [comment]
Sorted. I went back to the dx11 non rt version. Still running dx12 according to the game, but now the colours are fine. Now I just need setup the first person VR mode, then it should be game time. I'll send you a little thank you once its all sorted. 

Thanks 👍
