### ISSUE TITLE
All new mods from 1.309-to-...1.360 dos'n work in OpenXR Oculus(not SteamVR)

### ISSUE THREAD

**Issue by huliqan** [praydog/REFramework#599]
in HMD picture in upper left corner and in a crooked window (OpenXR dll from Oculus.Not SteamVR)
Works fine with 1.303 and older
win10x64 21H2 | i5-4670K 4.5GHz | 16Гб DDR3 | MSI GTX1080ti GAMING X 11G | Oculus Quest2

**Comment by praydog** [comment]
Provide your `re2_framework_log.txt` please.

**Comment by huliqan** [comment]
> Provide your `re2_framework_log.txt` please.

[re2_framework_log.7z.txt](https://github.com/praydog/REFramework/files/10128220/re2_framework_log.7z.txt)

**Comment by praydog** [comment]
Old versions of RE8 and pirated copies are not supported, this is not an issue.

**Comment by huliqan** [comment]
it's not pirated! it's steam official vers.!!!
