### ISSUE TITLE
Image show as a heat map ... rainbow colors ...

### ISSUE THREAD

**Issue by eschrisc** [praydog/REFramework#600]
Hi, @praydog . First thank you for you excelent job and for let as use it open. 
I am trying to lanch in VR RE7. With OpenVR it only appers in PC. With OpenXR all is correct, except that all 3D environment is like I was in a heat map, rainbow colors everywhere. My glases are Quest2. My GPU AMD 6700 XT 12GB

Any configuration that can I check?

Thanks in advance

**Comment by Buzbee** [comment]
https://github.com/praydog/REFramework/issues/307

**Comment by eschrisc** [comment]
Thanks @Buzbee . You gave me the solution. My problem was solved by closing Virtual Desktop server in the PC
