### ISSUE TITLE
re7 vr controls

### ISSUE THREAD

**Issue by Buzbee** [praydog/REFramework#601]
oculus controllers with Oculus Touch Button Prompts:
how to do a 180 degree turn? this was necessary in beginning hour demo to get dirty coin
how to sort inventory in trunk? button mod prompt gives xbox view button
any others not mentioned on getting started guide png?

In order to do a 180 turn, you hit down on the left stick, and press circle if you’re on PS4, and B if you’re on Xbox One.  On PC, the keyboard button is the X button. I cannot find the control combination on the oculus controllers.

While the cursor is in the item box, you press either the view (xbox one) or the touchpad button (ps4) to auto-sort items. Not sure on PC.

**Comment by praydog** [comment]
https://github.com/praydog/REFramework/discussions
