### ISSUE TITLE
crash report 

### ISSUE THREAD

**Issue by M03BIUM** [praydog/REFramework#604]
hi, I added your latest 370 framework directly to the steam common re8 root and it crashes at the capcom logo., the helmet doesn't engage (yes I have steam vr running) still doesn't go into the helmet I get the same result from your earlier Ver. mods also.  So I tried adding the RE8.zip mod files that contain the autorun folder, dinput and openvr and at least get the tv game to come up with that options box (like reshade) in the upper left corner. although Im guessing that it is an early mod or not yours at all?  at the very least says its initializing then crashes to desktop. Anyways It seems like a no-brainer mod and nothing seems to be working -with both mods, with only one or the other I get nothing but crash, so I'm not sure what I am doing wrong?  I also tried running in win7 mode to no avail. hares the crash logs. thank you 
[CrashReport.zip](https://github.com/praydog/REFramework/files/10200915/CrashReport.zip)

**Comment by praydog** [comment]
None of this information helps me. You need to upload `re2_framework_log.txt` from your game folder.

**Comment by M03BIUM** [comment]
mybad ....apologies. :)  theres no crashing now but it wont go to the hmd. do you need to add an extension to target like no nams sky requires.   like -steam or -openvr?  anyways ...here you go. 

[re2_framework_log.txt](https://github.com/praydog/REFramework/files/10201086/re2_framework_log.txt)

**Comment by praydog** [comment]
Run the nightly build from here: https://github.com/praydog/REFramework-nightly/releases/

Upload the log again after you have done so.

**Comment by M03BIUM** [comment]
will do. :)

**Comment by M03BIUM** [comment]
okay ... 

[re2_framework_log.txt](https://github.com/praydog/REFramework/files/10201276/re2_framework_log.txt)

**Comment by praydog** [comment]
You still aren't using the right build, or you have uploaded the same log file unintentionally. Check if you have an %APPDATA%/REFramework folder (you can just type this into your explorer bar). If you have one, then upload the log that's in the re8 folder there.

If not, then you are not downloading the correct build and installing it correctly, at all.

**Comment by M03BIUM** [comment]
thats odd, okay Ill check my appdata folders I assumed it was in my steam game folder where i drop mod?

**Comment by M03BIUM** [comment]
thats odd,  I assumed it was in my steam game folder where I drop the mod?  which is coincidentally where i got the one I sent you.  okay which folder in appdata ,roaming, locallow or local? Im not seeing anything saying REFramework. Im not seeing anything capcom, Resevil or RE and its not in the steam or steamemu folder under its app id number either. so.. uhh what am I missing here?

**Comment by M03BIUM** [comment]
have something odd here. I removed the ref_framework_log  fro mhere _ found it i nthe game root and played the gem agian, still no joy, but it also did  not generate a new one.   shoulld I be adding the RE8  vr mod in too? _
![Capture](https://user-images.githubusercontent.com/120280310/206891489-84e8144a-eee5-464c-b148-ba9af5f96ddf.PNG)

**Comment by praydog** [comment]
The image you uploaded and removed shows that the mod you downloaded is from 2021 instead of December 2022. You are not downloading the correct one from here: https://github.com/praydog/REFramework-nightly/releases/

**Comment by praydog** [comment]
If you need a direct link: https://github.com/praydog/REFramework-nightly/releases/download/latest/RE8.zip

**Comment by M03BIUM** [comment]
Haha, I knew I was doing something completely wrong ~ such a schmuck. your mod fires right up. excellent work you've done Thank you. 

One last question if you don't mind, is the characters head supposed to be kind of set back and buried into the chest of the model? Standing or sitting It gets in the way quite a bit.
