### ISSUE TITLE
UI too small

### ISSUE THREAD

**Issue by Rebelbuffoon** [praydog/REFramework#625]
So, either I am blind, or there is no way to increase the size of the UI for the Mod.. and that sucks, because in 4k, the UI is so small that half the words are not even readable.. is there no way to resize it, or do anything about this?

(Picture given below to show size. Only 1/2 of the screen is captured)

<img width="973" alt="image" src="https://user-images.githubusercontent.com/107762661/213343852-713cb218-030b-46a9-aba0-c302625aac12.png">

**Comment by praydog** [comment]
It's under Configuration. Increase the font size.

**Comment by Rebelbuffoon** [comment]
Increasing the Font size doesnt help at all, because the WIndow Stays the
same size, all it does is cause more Text to leave the Window and make it
even harder to guess what it is supposed to say

**Comment by praydog** [comment]
You can resize the window with the triangle in the bottom right of the window.

**Comment by Rebelbuffoon** [comment]
OOOOH.. it was hidden behind the Scroll bar... I thought I tried pulling
the corner.. I feel so stupid now.. thanks for the info^^
