### ISSUE TITLE
RE 8 Rainbow colors

### ISSUE THREAD

**Issue by eschrisc** [praydog/REFramework#627]
[re2_framework_log.zip](https://github.com/praydog/REFramework/files/10472844/re2_framework_log.zip) with OpenXR

[reframework_crash.zip](https://github.com/praydog/REFramework/files/10472845/reframework_crash.zip) with OpenVR

Hello @praydog. I have the rainbow colors with RE8 Village. I am using OpenXR. Can you help me? 

With RE7 I managed to remove rainbow colors  stopping Virtual Desktop. However this solution it doesn't work today. This worked some days ago.

I use YCbCr422 8 bits and HDR disabled. My GPU is AMD RADEON 6700 XT

Thank you very much

**Comment by praydog** [comment]
Duplicate issue https://github.com/praydog/REFramework/issues/307
