### ISSUE TITLE
resident evil 8 vr problem

### ISSUE THREAD

**Issue by fabian1187** [praydog/REFramework#629]
start des spiels ist die position der text daten weit unten,trotz syncroniesieren ändert sich nicht,sobal ich ins spiel rein gehe bin ich plötzlich so als sei ich 3 meter  ,1 mission wo man das baby sieht mein kopf ist an der decke,wie ändere ich das ,das man die normale ansicht bekommt? syncroniesieren verändert garnichts bitte um ifo

**Comment by praydog** [comment]
Press the "Reset Standing Origin" button in the REFramework menu. You can also recenter your view in SteamVR.

**Comment by fabian1187** [comment]
Ok thanks

Gesendet von Yahoo Mail auf Android 
 
  Am Mo., Jan. 23, 2023 at 5:15 schrieb ***@***.***>:   


Press the "Reset Standing Origin" button in the REFramework menu. You can also recenter your view in SteamVR.
