### ISSUE TITLE
Monster hunter rise gamepass update breaks compatibility

### ISSUE THREAD

**Issue by jonjetjon** [praydog/REFramework#635]
Today's update that came with no patch notes has broken reframework, I have tried removing all mods and doing a clean install with just the dxinput8 dll file and it still gets suck on "reframework is currently initializing". I dont see any errors in the log files or a crash dump. If you alt tab out of the game and come back the reframework menu is gone, but does not come up with the assigned key indicating its stuck and unresponsive.

**Comment by jonjetjon** [comment]
update: there does seem to be an error in the log files:
[REFramework] [error] Present failed: 87a0001
unsure if this is a related issue and that error may have been present before.
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/10552692/re2_framework_log.txt)

**Comment by praydog** [comment]
Fixed in a62be521776bb3420a5fd5ddabc20aa79d4600e3 and 4456c29d6c408edec01f4642d9aee27bf69d32f9

**Comment by Guzman45** [comment]
I don't know how to solve the problem. Someone may help me?

**Comment by jonjetjon** [comment]
> I don't know how to solve the problem. Someone may help me?

The mod nexus version was outdated compared to the github version, if you're having this issue you need to download the latest build on github instead

**Comment by praydog** [comment]
> > I don't know how to solve the problem. Someone may help me?
> 
> The mod nexus version was outdated compared to the github version, if you're having this issue you need to download the latest build on github instead. Check https://github.com/praydog/REFramework/releases

The Nexus build is not outdated.

**Comment by jonjetjon** [comment]
> > > I don't know how to solve the problem. Someone may help me?
> > 
> > 
> > The mod nexus version was outdated compared to the github version, if you're having this issue you need to download the latest build on github instead. Check https://github.com/praydog/REFramework/releases
> 
> The Nexus build is not outdated.

"WAS" outdated at the time of original issue, it appears to be up to date as of the 1st.
