### ISSUE TITLE
MHR Sunbreak Crashing on Launch

### ISSUE THREAD

**Issue by yjygmingTV** [praydog/REFramework#638]
Placed dinput8.dll in MHR root folder. Launched the game and then game crashes. 
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/10581479/re2_framework_log.txt)

**Comment by yjygmingTV** [comment]
removing dinput8.dll fixes everything but will not be able to mod the game.

**Comment by praydog** [comment]
Pirated copies are not supported.d
