### ISSUE TITLE
How do i load the upscaling module?

### ISSUE THREAD

**Issue by kassindornelles** [praydog/REFramework#639]
using the upscaling branch on RE2 remake in dx12 and the reframework UI says the module is not loaded

**Comment by praydog** [comment]
https://www.nexusmods.com/site/mods/502

Read everything here, it uses the same plugin

**Comment by kassindornelles** [comment]
> https://www.nexusmods.com/site/mods/502
> 
> Read everything here, it uses the same plugin. If one version doesn't work, keep going back a few versions as I haven't checked if he has made any changes to account for.

i paste the fsr dll files to the plugins folder and it should work right?

**Comment by kassindornelles** [comment]
yeah like i did read the thing but theres no guide, i'm also using linux and theres no way to know how it works if you dont make a guide

**Comment by praydog** [comment]
You need his Upscaler plugin (PDUpscaler.dll) as well as the FSR DLLs, yes. This is not ready for public release due to VR issues that I am still sorting out, so there will be no proper documentation until then.

**Comment by kassindornelles** [comment]
i got it working and figure that you are applying FSR to the entire window including UI, isn't that possible to run the game at native res and use the in-game resolution scaling for that?

**Comment by artivision** [comment]
> i got it working and figure that you are applying FSR to the entire window including UI, isn't that possible to run the game at native res and use the in-game resolution scaling for that? (and ignore UI)

If you please, what exactly have yo done? I see the plugins loaded in the 'plugins' section but not any temporal argument?
