### ISSUE TITLE
Leon's body is transparent in one eye

### ISSUE THREAD

**Issue by TuTAH1** [praydog/REFramework#640]
It's ok in the left eye and no body (just head) in the other eye
<img width="1920" alt="Desktop Screenshot 2023 02 05 - 20 58 10 75" src="https://user-images.githubusercontent.com/15982179/216830162-a45c33c3-493a-4cef-89f0-7f2c36cfe76a.png">

Happens both in the cutscenes and,
<img width="1920" alt="Desktop Screenshot 2023 02 05 - 21 10 46 71" src="https://user-images.githubusercontent.com/15982179/216830857-06a72081-29c5-44a5-92f0-c18082c351fc.png">
 1rd 3rd person. I also can see other body in the right eye that's not moving

**Comment by praydog** [comment]
Duplicate issue #400
