### ISSUE TITLE
[MHR] Remember Menu Open/Closed State not saving

### ISSUE THREAD

**Issue by Gottschkopf** [praydog/REFramework#641]
Checked the option and closed the menu.

Every time on startup the menu pops up again and the option is unchecked.

**Comment by MinoumimiSenpai** [comment]
are you closing the window using the TopRight X ?
From my experience if not Mistaken
The Autosave,
seems likely to be triggered by pressing the Keybind
So, 
Seems To (Only Save) IF (Using "Insert/keybind") To Close
hopefully,
A Toggle Key to Save and Toggle UI will be added one day

**Comment by Gottschkopf** [comment]
Yes, that worked.

Should really be mentioned somewhere, though...

**Comment by sibir-ine** [comment]
I've noticed this behavior too. Would it be possible to make the behavior consistent between both methods of closing the menu, or is there a reason that it's different?
