### ISSUE TITLE
REFramework error: An exception has occurred during initialization

### ISSUE THREAD

**Issue by CrabdaddyLonglegs** [praydog/REFramework#645]
I just got RE2 for this mod and it simply isn't working. There are no steps for what to launch first or from where that I see on this site. I'm using Quest 2 and basically making guesses at what to launch first. Can someone lay out the steps or explain why this isn't working?

**Comment by CrabdaddyLonglegs** [comment]
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/10712393/re2_framework_log.txt)

**Comment by praydog** [comment]
Looks like you're on the old version of RE2. You need to use the corresponding old version of the mod as well.

Get it from here: https://github.com/praydog/REFramework/releases/download/v1.4/RE2_TDB66.zip

**Comment by CrabdaddyLonglegs** [comment]
Thanks. Steam was saying to opt in to beta for ray tracing support, which changed the game version. Do both now support ray tracing or only the beta I opted into?

**Comment by praydog** [comment]
The beta you opted into is the old version of the game. The latest (non-beta) version of the game has RT support.
