### ISSUE TITLE
RE7 and RE8 distorted colors when using OpenXR

### ISSUE THREAD

**Issue by joog78** [praydog/REFramework#651]
Hi, first of all thank you @praydog for making this even possible!
I'm having an issue in RE7 and RE8. The HMD (HP Reverb G2) displays the game with distorted colors when using OpenXR. On the desktop the game renders with normal colors. Using OpenVR with SteamVR the issue is not there, but the framerate is much lower.
Video card is AMD 7900XTX with graphics driver 23.2.1 (newest as of now), but the one before also produced the same. Clean install of Windows 10 x64 and clean install of game and REFramework 1.4.
Thank you for looking into this!

![re8_distorted_colours_hmd](https://user-images.githubusercontent.com/99419035/219782992-c3a0f25e-97ac-44c7-aef5-d340bfe1ab3f.jpg)
![re8_distorted_colours_desktop](https://user-images.githubusercontent.com/99419035/219783009-70deed4b-3a72-43e8-80d8-02987f627103.jpg)

**Comment by praydog** [comment]
Duplicate issue #307
