### ISSUE TITLE
RE7/RE8 Visual glitch blue green pink Quest 2

### ISSUE THREAD

**Issue by Haplite** [praydog/REFramework#658]
When running the RE7/RE8 REFramework mods on both games I get a strange visual glitch but I cant find anyone else who has posted about it. I've tried for hours of troubleshooting reinstalling and restarting but nothing works for me. I use my quest 2 and play via airlink and everything works but when in the main menu and in-game, there is an awful filter of neon green blue and pink over all the normal textures in the game. When I take my headset off and look at the game displayed on my monitor everything is perfectly normal so I'm not sure what the issue is exactly, I've tried via link cable as well. 

On a separate note, when running the game via SteamVR the game will boot up with the sounds and the controls work but I'm stuck in the SteamVR home area. Since OpenVR doesn't work for me, I deleted the file and have been using OpenXR with the oculus app and that actually works but like I stated above, its very glitchy looking with neon colors everywhere. 

If anyone has any suggestions or solutions I'm all ears because I've tried for hours to get these mods to work and this is my last resort, thanks!

**Comment by PaoloBrancatoN01434080** [comment]
just got the mod today worked fine then the issue came, so i deleted the game and all its files then played and it went away, later that same day I ran it again and now its back. everything is green/pink/wavy. unplayable like on quest 2. I'm using a 3070ti laptop with R9 6900hx cpu and 16 gb ram if it helps

**Comment by PaoloBrancatoN01434080** [comment]
fix for me maybe for you go out of full screen into window mode or try another monitor, as the game does not support HDR and if your monitor has it even if its off in settings this issue will still happen.

**Comment by praydog** [comment]
Duplicate issue #307
