### ISSUE TITLE
Laggy game. is it because of my components?

### ISSUE THREAD

**Issue by alari73512** [praydog/REFramework#661]
The game is laggy. only disapears when i put the resolution to minimum low, graphics to low and change steam eye resolution to like 60%

laptop specs:

GPU: NVIDIA GeForce RTX 2070 with Max-Q Design
CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
RAM: 16 GB
SSD: 2TB
Windows 11
Im using link cable 3.0.

**Comment by praydog** [comment]
Yes. Not an issue.
