### ISSUE TITLE
Disable in-game sharpening option?

### ISSUE THREAD

**Issue by soupjake** [praydog/REFramework#665]
Hi was wondering if there was a way to add an option to disable the in-game sharpening filter?

This can be done to games like RE2 and RE8 using HEX edits or another mod like RE2 3D Vision Fix so should be possible. Imagine it'll be similar process to how disabling vignette works.

Thanks!

**Comment by KoKlusz** [comment]
If you install all the files in the zip file there should be an option to disable sharpening in the very last tab. This does sadly break TAA in RE3 at least, haven't tested other games.

**Comment by soupjake** [comment]
> If you install all the files in the zip file there should be an option to disable sharpening in the very last tab. This does sadly break TAA in RE3 at least, haven't tested other games.

Ah my bad didn't see that.
