### ISSUE TITLE
Cant install UpscalerBasePlugin

### ISSUE THREAD

**Issue by Fan4eGGG** [praydog/REFramework#669]
What i done:

1. paste the _dinput8.dll_ into RE4 folder.
2. dwnld the _UpscalerBasePlugin_ from nexus and paste the _PDPerfPlugin.dll_ into `reframework\plugins folder`.
3. dwnld a lot of _nvngx_dlss.dll_ n try the last one, paste it the same `reframework\plugins folder`.
4. run the game and wont see the **TemporalUpscaler** line.

what i did wrong?

**Comment by praydog** [comment]
You need the `pd-upscaler` branch. https://github.com/praydog/REFramework/actions

**Comment by Fan4eGGG** [comment]
i dunno what to do
