### ISSUE TITLE
RE4 Steam Deck crash

### ISSUE THREAD

**Issue by trdpatrick** [praydog/REFramework#689]
The game crashes after getting into the menu, when you the game actually loads.  Was trying to use trainers with the game but it crashes with just the .dll file in the game directory.  Removing the .dll lets me get in-game with no issues.

**Comment by sunnyjocker** [comment]
try the latest build: https://github.com/praydog/REFramework-nightly/releases

**Comment by notpentadactyl** [comment]
you need this PR: https://github.com/praydog/REFramework/pull/688

**Comment by praydog** [comment]
Fixed in 7088ddb1f7924c3ed2afa90c2cfd2d7265ef6014

Download the latest build: https://github.com/praydog/REFramework-nightly/releases
