### ISSUE TITLE
DLSS is blurry on RE4 here

### ISSUE THREAD

**Issue by rodrigoxm49** [praydog/REFramework#691]
It works really well in RE4 Demo or RE Village, but it's really blurry on RE4. It looks like it's rendering in a very low resolution or something like that. I've tried every option on TemporalScaling, only DLAA works as it should, but I'm looking for better performance. Have no idea what's happening here. I've sent the exactly same files that i'm using to some friends and for them DLSS it's working fine!

**Comment by TommyCreo21** [comment]
Works fine on my end. What is your output resolution set to? 

Be sure to disable "Allow Engine TAA" in the upscaler settings, as it makes things really blurry.

Also be sure disable FSR 1 & 2 in the game settings, as well as Interlaced rendering.
Also disabling motion blur gets rid of some issues.

**Comment by praydog** [comment]
This can happen if you have the built-in FSR or FSR2 enabled. Double check that those are disabled in the game options.

**Comment by rodrigoxm49** [comment]
I'm stupid. Yes, FSR was enable and I didn't know since I hate this. I though that I have disable it. Thanks. DLSS is working fine now!
