### ISSUE TITLE
[Request] RE4Remake Scope performance fix

### ISSUE THREAD

**Issue by kassindornelles** [praydog/REFramework#698]
This is a request, feel free to close this issue
but... there is anything reframework can do to fix the goddamn scopes eating 80% of the framerate everytime you use them?
can you take a look at it?

 thanks in advance whatever is the outcome <3

**Comment by TommyCreo21** [comment]
Scopes in this game are dual rendered which is why they have a significant impact on performance.  Don't know if that functionality can be disabled.

**Comment by praydog** [comment]
The way scopes work is they create a separate scene, yes. It's possible to lower the render quality of said scene to increase the performance, but it will make the scopes look worse.

**Comment by kassindornelles** [comment]
> The way scopes work is they create a separate scene, yes. It's possible to lower the render quality of said scene to increase the performance, but it will make the scopes look worse.

might be a small tradeoff until capcom fixes it, IF they ever fix this

**Comment by praydog** [comment]
Added in 50f46296dc117c8fa12d99fcd3a4bf2b071b0ca7. Available in both master and pd-upscaler branch.

**Comment by praydog** [comment]
https://user-images.githubusercontent.com/2909949/230745275-146516af-bd58-44dc-b933-4d490391c260.mp4

**Comment by gir489returns** [comment]
IDK what you guys are talking about, I was wondering what the purpose of this commit was, and I get 60 FPS on a 1080 Ti without the scope and with the scope. But you do you.

**Comment by Unit-45** [comment]
Pardon me if I'm not supposed to reply to old threads (I don't know much about GitHub ettiquete) but why choose to reduce scope quality instead of the outside render area quality? Couldn't you guys instead set the render area around the scope to be black to save resources (just like any other game) and only choose to render the scope in 1x render res quality?
