### ISSUE TITLE
[BUG] RE4 Remake Crashing at startup

### ISSUE THREAD

**Issue by GH0STDATA** [praydog/REFramework#703]
This plugin seems to crash my game while initializing. It doesn't even reach the main menu unfortunately. I've been able to play the game perfectly fine until I applied this mod. Now I cannot launch the game at all and I'm getting constant crashes. I've posted the log as well as the dump file stored in a zip below. Hopefully this info will help fix any issues :)

[re2_framework_log.txt](https://github.com/praydog/REFramework/files/11099443/re2_framework_log.txt)
[reframework_crash.zip](https://github.com/praydog/REFramework/files/11099447/reframework_crash.zip)

**Comment by praydog** [comment]
You have an overlay that is interfering with normal operation of the mod. Something like ReShade, Discord overlay (not common), Razer stuff, ASUS tools, Overwolf, etc.

From the crash log, it looks like Rivatuner is the issue here.

**Comment by GH0STDATA** [comment]
You were right, that is very strange. It worked fine with RivaTuner before I installed this mod... oh well, I've disabled it and it seems to work fine now. Thank you! Since RivaTuner is a very popular software for monitoring component performance and temps, maybe this should be mentioned on the NexusMods page as well as in this repo's readme to prevent others from experiencing similar issues.
