### ISSUE TITLE
resi 2 stuck on initialising 

### ISSUE THREAD

**Issue by kamikazilucas** [praydog/REFramework#706]
mod dosent work for resi 2 it just says currently initialising

**Comment by praydog** [comment]
Make sure you're using the correct version of the mod. RE2.zip for the latest version, RE2_TDB66.zip for the beta/pre-RT build of RE2.

**Comment by kamikazilucas** [comment]
i see

**Comment by kamikazilucas** [comment]
when i use the b66 it just vanishes after and i cant get it to appear again
