### ISSUE TITLE
RE8 crashed on startup

### ISSUE THREAD

**Issue by GoldExynos** [praydog/REFramework#713]
I have the latest version of DODI-repack (Deluxe Edition (Build 6587890)). I tried both the latest stable version (1.4) and latest nightly build (1.431). and I face the crashing problem at the startup of the game. and after deleting dinput8.dll from game folder everything works fine and game is completely stable. I want to use FLiNG Trainer so i need the REFramework.
I don't know what the problem is with it.
Please help.
I also attached the log file.
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/11120977/re2_framework_log.txt)

**Comment by OlavoBru** [comment]
Same issue here
got RE Village DODI-repack (Deluxe Edition (Build 6587890), crashes on startup when using dinput8.dll, tried with 1.4, 1.431 as well as 1.05 and 1.06.3 from around the time Build 6587890 was released, most times it crashes as soon as the game comes up, sometimes it goes as far as the Capcom logo

Tried this "fix" but also didn't work: https://community.wemod.com/t/resident-evil-village-cheats-and-trainer-for-steam/166215/104

Plz help

[re2_framework_log.txt](https://github.com/praydog/REFramework/files/11121372/re2_framework_log.txt)

**Comment by praydog** [comment]
Pirated copies are not supported.
