### ISSUE TITLE
RE4: FoV option breaks cutscenes, attaché case, save menu, and others

### ISSUE THREAD

**Issue by djuniah** [praydog/REFramework#716]
Not sure if this is the intended behavior or not, but using the FoV override setting doesn't seem to override the value set in the game's settings, it instead just applies globally to the main camera.  This has the side effect of overriding the times when the game manually adjusts the Fov.  Some examples i've seen:

* Cutscenes where the camera would be doing a close-up are shown from a wider FoV and this often leads to unintended things happening like parts of the level being invisible.  For example, Ashley is sitting on a bed at one point and as the camera angle changes, the bed disappears and re-appears each time it changes (pretty sure the times where it is invisible, the camera is supposed to be close enough where you wouldn't see it happening)
* Sections in the game that have a binocular prompt don't work at all since the zoom function seems to be tied to the FoV.  It isn't game-breaking but you end up missing whatever it is that the game was supposed to be zooming into.
* Some of the "press A to activate" overlays seem to be off-set a bit.  Not 100% sure if this is caused by the FoV change, but the only things I had enabled were DLSS and FoV.
* The attaché case and the save menu appear to have a custom FoV as well, so if you set it higher than normal, it takes up less of the screen and sort of "pops" when you close it.

I found another mod on nexusmods called "Simple FOV for RE4 Remake" which is just a cheat-engine table that apparently doesn't have these issues (I'm guessing it's just affecting whatever value is changed in the settings menu).  Not sure if it's helpful but I wanted to point that out in case it was.

**Comment by praydog** [comment]
Use the ultrawide option to adjust FOV, it will work like you expect.

**Comment by djuniah** [comment]
Ok, i'll try that.  Thanks!
