### ISSUE TITLE
Hub ingame (& intro letters resident evil 4) are huge?

### ISSUE THREAD

**Issue by Roy1970** [praydog/REFramework#717]
Hi,

Is there a way to reset the forest path intro (the letters and ingame hub) to it's original size?

Thanks.
Roy

**Comment by praydog** [comment]
VR Menu: 
Recenter view. 
Reset standing origin. 

SteamVR: 
Recenter in SteamVR.

**Comment by Roy1970** [comment]
Nope but Thanks Verstuurd vanaf mijn iPhoneOp 1 apr. 2023 om 16:24 heeft praydog ***@***.***> het volgende geschreven:﻿
VR Menu:
Recenter view.
Reset standing origin.
SteamVR:
Recenter in SteamVR.

**Comment by Roy1970** [comment]
Hello,What Causes A second vr screen popping up at the select screen in RE4. Latest build and latest nvidia drivers Thank you SirRegardsRoyVerstuurd vanaf mijn iPhoneOp 1 apr. 2023 om 18:10 heeft Roy ***@***.***> het volgende geschreven:﻿Nope but Thanks Verstuurd vanaf mijn iPhoneOp 1 apr. 2023 om 16:24 heeft praydog ***@***.***> het volgende geschreven:﻿
VR Menu:
Recenter view.
Reset standing origin.
SteamVR:
Recenter in SteamVR.

**Comment by Roy1970** [comment]
Hi Pray,Please fix the HUD in dead Island 2 uevr thanksVerstuurd vanaf mijn iPhoneOp 1 apr. 2023 om 18:10 heeft Roy ***@***.***> het volgende geschreven:﻿Nope but Thanks Verstuurd vanaf mijn iPhoneOp 1 apr. 2023 om 16:24 heeft praydog ***@***.***> het volgende geschreven:﻿
VR Menu:
Recenter view.
Reset standing origin.
SteamVR:
Recenter in SteamVR.
