### ISSUE TITLE
Changing hands for lefties

### ISSUE THREAD

**Issue by HughVR** [praydog/REFramework#718]
First of all, I want to thank you for your titanic work! You are geniuses! Please explain, 1) how to set up your mods so that the movement is on the right controller, and the turns and weapons on the left, 2) how to set up mouse and keyboard control in VR, on Oculus Quest2, when the trackers are turned off, hand tracking automatically turns on, the mouse and keyboard do not work (To all the world!)

**Comment by praydog** [comment]
Duplicate issue #347
