### ISSUE TITLE
[RE4 Demo] - Touch Controllers Not Working

### ISSUE THREAD

**Issue by StoofManley** [praydog/REFramework#721]
I'm trying the mod in the RE4 Chainsaw Demo until I'm ready to purchase the full game. I can hit OK when the message about auto-saving comes up but once I'm at the title screen no controls do anything. I've tried using OpenVR, OpenXR, DX11 and DX12 from both Oculus AirLink and Virtual Desktop.

Log is attached. Thanks!
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/11130422/re2_framework_log.txt)

**Comment by praydog** [comment]
Not a bug. REFramework does not implement generic motion controller -> gamepad mappings. Only games that have had VR support specifically added for them in REFramework are controllable via the motion controllers, and RE4 is not one of them.

**Comment by StoofManley** [comment]
Thanks for the response. I wasn't aware motion controls weren't implemented. Are there plans to have motion control in RE4.

On a similiar note, I'm going back to RE2 (with RT) and have having the same issue. Any thoughts or should I open a new thread?

**Comment by praydog** [comment]
Make sure you've fully extracted all of the files in the zip to your RE2 folder. If you only extracted dinput8.dll but not the `reframework` folder in the zip, you will be missing the actual VR implementation.

**Comment by StoofManley** [comment]
I certainly had everything extracted. I've had it working in the past with the non-RT version about a year ago when I was playing it. Everything comes up in the headset. I can hit okay at the auto-save message and then after that the controls dont respond.

**Comment by r57zone** [comment]
It would be great to at least make 3DOF for the right controller by default
