### ISSUE TITLE
Please add toggle left & right shoulder camera function.

### ISSUE THREAD

**Issue by zhm86** [praydog/REFramework#722]
There is a button in many games to toggle shoulder, e.g. GTA V, Starwars Battlefront II, Call of Duty, Alan Wake, Max Payne 3
Is it possible to modify camera offset to toggle shoulder camera in RE4?
![gta5](https://user-images.githubusercontent.com/16450203/229335008-40ba1bf6-df7a-4e78-b5d3-c43e137f40af.jpg)
![COD](https://user-images.githubusercontent.com/16450203/229335019-cfd3c0d9-7d74-4eac-ad4c-296c4b60f9db.jpg)
![battlefront2](https://user-images.githubusercontent.com/16450203/229335031-9892c5b2-285b-4a58-a9c7-eca1909f977e.jpg)

**Comment by praydog** [comment]
Not planning on this.
