### ISSUE TITLE
Zoom in/out on hub / map ?

### ISSUE THREAD

**Issue by Roy1970** [praydog/REFramework#723]
Any solution?

**Comment by praydog** [comment]
I have no idea what you're talking about. Take an screenshot of what you're seeing.

**Comment by Roy1970** [comment]
The forest opening letters come closer when you use the xbox controller left thumbstick. The image(and ingame hub) gets bigger and you cannot make it default size again.

**Comment by JoHien** [comment]
> Imagine a huge map / hub overlay, how to zoom out of a (too) big hub?

We don't understand your question. Can you provide us with a screenshot? If you're talking about how to zoom in and out of the map, use a scroll wheel on the mouse or a right stick on the controller. If that's the case, this has nothing to do with the mod.

**Comment by Roy1970** [comment]
Solved deleted re2_fw_config and ref_ui letters/hub back to default. Thanks.
