### ISSUE TITLE
Meta quest 2 controllers not tracking RE4

### ISSUE THREAD

**Issue by WrongWayUp** [praydog/REFramework#729]
starts up fine can use them outside of the game (desktop ect to launch game in vr) 
but as soon as it focused it just stops tracking them

**Comment by praydog** [comment]
Not a bug. REFramework does not implement generic motion controller -> gamepad mappings. Only games that have had VR support specifically added for them in REFramework are controllable via the motion controllers, and RE4 is not one of them.

**Comment by r57zone** [comment]
Will this ever change? The PS5 VR version probably isn't selling very well anymore and it won't hurt Capcom in any way.  Sony also seems to have given up on VR. Capcom is not interested in PC VR.
There's probably nothing to worry about anymore.
