### ISSUE TITLE
RE 3 TEMPORALUPSCALER WONT SHOW UP

### ISSUE THREAD

**Issue by Karlsonnnn** [praydog/REFramework#730]
![image](https://user-images.githubusercontent.com/113211152/230453503-3a9849bb-48cd-4089-8adc-9471791afe46.png)
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/11173076/re2_framework_log.txt)

**Comment by praydog** [comment]
This feature is in beta and not fully released. You need the `pd-upscaler` branch, and it will only work on the RT (new) versions of the games.

https://github.com/praydog/REFramework/actions
