### ISSUE TITLE
Upscaler option not showing in Reframework in RE4

### ISSUE THREAD

**Issue by maou42** [praydog/REFramework#731]
All files in correct folder. Reframework loads but no Upscale option.

**Comment by AlanBuss** [comment]
for me only appears the DLAA

**Comment by praydog** [comment]
This feature is in beta and not fully released. You need the pd-upscaler branch, and it will only work on the RT (new) versions of the games.

https://github.com/praydog/REFramework/actions

**Comment by maou42** [comment]
It used to work perfectly in the RE4 remake. It subsequently deleted it and now the upscaler refuses to show. I did get it from Nexusmods.

**Comment by artivision** [comment]
> This feature is in beta and not fully released. You need the pd-upscaler branch, and it will only work on the RT (new) versions of the games.
> 
> https://github.com/praydog/REFramework/actions

Good day praydog, how can i download the pd-upscaler branch for Village? Also do i need it for PureDark's UpscalerBasePlugin?
