### ISSUE TITLE
RE4 Remake Crash with only d8input.dll

### ISSUE THREAD

**Issue by CTO7** [praydog/REFramework#732]
Using the latest nightly release and getting a crash sometimes on launch sometimes just after getting ingame with D3D error 25 or sometimes 26. If I remove d8input it runs without any issues. 

[re2_framework_log.txt](https://github.com/praydog/REFramework/files/11183257/re2_framework_log.txt)

**Comment by praydog** [comment]
Make sure you aren't running any overlays like Rivatuner, some ASUS software, some Razer software, Overwolf, etc...

**Comment by CTO7** [comment]
Disabled rivatuner and steam before my first post, did notice nvidia overlay running so disabled that too. I don't think I have any others  but still getting the crash. 
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/11184877/re2_framework_log.txt)

**Comment by praydog** [comment]
Upload the `reframework_crash.dmp` from your game directory.

**Comment by praydog** [comment]
Actually, that won't be there because of the D3D error, nevermind.

**Comment by CTO7** [comment]
I do have one from about the same time, i'll try uploading it anyway.
https://drive.google.com/file/d/1kB0p_htB9OHIbk9lm8H3m0UbnM7ORhB5/view?usp=sharing

**Comment by PROPHETJZX100** [comment]
https://www.youtube.com/watch?v=lEMx5SwEZH8
In this video will show you how to fix two of the most common issues with REFramework on the
mod manager. This will allow you to install mods that require ReFramework without game crashes
and static startup black loading screen... BTWS (IT IS POSSIBLE TO INSTALL MODS ON THE EMPRESS CRACKED 
VERSION!!) this method works on both (steam) & (Cracked)

**Comment by Uianat** [comment]
Hello the video showing how to fix the issue is not available and I hope you can re-upload it, or tell how to fix the issue step by step

**Comment by ali-01914** [comment]
> Hello the video showing how to fix the issue is not available and I hope you can re-upload it, or tell how to fix the issue step by step

any solutions bro?

**Comment by bhpg6hsn6m-stack** [comment]
Hola al usar reframewor me da el error d3d error (25 error device hung 0x887a0006) alguna solución?
