### ISSUE TITLE
nightly re4 remake not working

### ISSUE THREAD

**Issue by ggp759** [praydog/REFramework#734]
Apologise if this is not the place for this question. Downloaded the latest nightly re4.zip from 10 hours ago at it says at the time of writing this message extracted the dinput8.dll along with nvngx_dlss (3.1.11) and the latest PDPerfPlugin.dll at the root directory of the game. The menu of the mod comes up but the temporal upscaler option is not there. What am i doing wrong? Thanks for any input.

**Comment by praydog** [comment]
This feature is in beta and not fully released. You need the pd-upscaler branch, and it will only work on the RT (new) versions of the games.

https://github.com/praydog/REFramework/actions
