### ISSUE TITLE
RE8 Village Override FOV option broken after denuvo update

### ISSUE THREAD

**Issue by Silent-Remux** [praydog/REFramework#737]
No longer working.

**Comment by praydog** [comment]
Unable to replicate. Upload your re2_fw_config.txt.

Try the nightly build as well and report back (if you weren't using it before): https://github.com/praydog/REFramework-nightly/releases/

**Comment by Silent-Remux** [comment]
> 

Hi, I am using the nightly release. 3440x1440 is resolution 21:9.

[re2_fw_config.txt](https://github.com/praydog/REFramework/files/11189544/re2_fw_config.txt)

**Comment by praydog** [comment]
I see you're using the Global FOV. Try disabling this (untick "Use Custom Global FOV"), and instead use the "RE8 FOV", and "RE8 Aiming FOV" above it.

What is the behavior you're experiencing? No FOV change at all?

**Comment by Silent-Remux** [comment]
> 

I think this was user error, my bad.
