### ISSUE TITLE
Crashing when Finished loading.

### ISSUE THREAD

**Issue by Laz55** [praydog/REFramework#741]
Current version keeps crashing on startup : Meaning once Reframework has fully loaded the game crashes. Have this on Steamdeck  with different mods such as Infinite Knife Durability, Teleport mod.

**Comment by praydog** [comment]
Not enough information. Closed.

**Comment by Laz55** [comment]
Hi


Not enough information? Translation your too lazy too fix  the issue. I
littery stated the issue.

**Comment by Laz55** [comment]
You joking right ? I littery told you the issue.

**Comment by praydog** [comment]
Right, but you didn't go to the page I linked which tells you what you need to upload to properly report a bug.

I also don't have a Steam Deck so I can't do anything without this information.

**Comment by Laz55** [comment]
Hi

Of course not .Typical.
