### ISSUE TITLE
RE3 with DLSS fails

### ISSUE THREAD

**Issue by tr1ckert** [praydog/REFramework#744]
Hello,

[2023-04-14 15:55:16.942] [REFramework] [error] Present failed: 87a0001

1.460a
UpscalerBasePlugin 1.1.0
DLSS 3.1.11.0
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/11233686/re2_framework_log.txt)

Same exact files work for RE4 Remake.

**Comment by tr1ckert** [comment]
Sorry, for anyone as stupid as me, here is what to do:
Go here: https://github.com/praydog/REFramework/actions/runs/4576684645
Download RE3 under "Artifacts".

Put the dinput8.dll dinput8.pdb + the reframework folder into the main game directory.

Download: https://www.nexusmods.com/site/mods/502
Put the PDPerfPlugin.dll directly into the game directory (no subfolder).

Download the latest DLSS dll here: https://www.techpowerup.com/download/nvidia-dlss-dll/
Put the nvngx_dlss.dll into the main folder.

Now reframework should work fine, the nexusmods version seems to be newer but also does not work.

For DLSS download https://github.com/Orbmu2k/nvidiaProfileInspector/releases
Open the profile inspector and choose Resident Evil 3 Remake in the profiles.

Set Transparency Supersampling to 0x00000008 AA_MODE_REPLAY_MODE_ALL
(Strg+F you can search for this if you don't find)

Set LOD Bias (DX) to following based on DLSS mode:
Quality: -2.0000
Balance: -3.0000
Performance: -3.0000
Ultra Performance: -3.0000

**Comment by CtrlP1** [comment]
> Sorry, for anyone as stupid as me, here is what to do: Go here: https://github.com/praydog/REFramework/actions/runs/4576684645 Download RE3 under "Artifacts".
> 
> Put the dinput8.dll dinput8.pdb + the reframework folder into the main game directory.
> 
> Download: https://www.nexusmods.com/site/mods/502 Put the PDPerfPlugin.dll directly into the game directory (no subfolder).
> 
> Download the latest DLSS dll here: https://www.techpowerup.com/download/nvidia-dlss-dll/ Put the nvngx_dlss.dll into the main folder.
> 
> Now reframework should work fine, the nexusmods version seems to be newer but also does not work.
> 
> For DLSS download https://github.com/Orbmu2k/nvidiaProfileInspector/releases Open the profile inspector and choose Resident Evil 3 Remake in the profiles.
> 
> Set Transparency Supersampling to 0x00000008 AA_MODE_REPLAY_MODE_ALL (Strg+F you can search for this if you don't find)
> 
> Set LOD Bias (DX) to following based on DLSS mode: Quality: -2.0000 Balance: -3.0000 Performance: -3.0000 Ultra Performance: -3.0000
> 
> Also disable bloom in game.

is there a way to get the expired file? I've tried all the new ones to no avail.

**Comment by lucidliam** [comment]
> Sorry, for anyone as stupid as me, here is what to do: Go here: https://github.com/praydog/REFramework/actions/runs/4576684645 Download RE3 under "Artifacts".
> 
> Put the dinput8.dll dinput8.pdb + the reframework folder into the main game directory.
> 
> Download: https://www.nexusmods.com/site/mods/502 Put the PDPerfPlugin.dll directly into the game directory (no subfolder).
> 
> Download the latest DLSS dll here: https://www.techpowerup.com/download/nvidia-dlss-dll/ Put the nvngx_dlss.dll into the main folder.
> 
> Now reframework should work fine, the nexusmods version seems to be newer but also does not work.
> 
> For DLSS download https://github.com/Orbmu2k/nvidiaProfileInspector/releases Open the profile inspector and choose Resident Evil 3 Remake in the profiles.
> 
> Set Transparency Supersampling to 0x00000008 AA_MODE_REPLAY_MODE_ALL (Strg+F you can search for this if you don't find)
> 
> Set LOD Bias (DX) to following based on DLSS mode: Quality: -2.0000 Balance: -3.0000 Performance: -3.0000 Ultra Performance: -3.0000
> 
> Also disable bloom in game.

Where did you find these LOD numbers? Using them made the game look instantly better than using the numbers most people say to use (-0.5 for quality etc) . Do you know if these settings work best for RE4R, RE7 and RE8 as well? Apologies for the necro, but these LOD settings here really are the best ones I've found.
