### ISSUE TITLE
RE7 Rainbow color issue 

### ISSUE THREAD

**Issue by Chinga3** [praydog/REFramework#745]
Hi Everyone,

I am trying to run the resident evil 7 VR mod for two days, the best I have got is the game launches in VR, but all textures are rainbow-coloured. I have tried using the DX11 version with the RE7_TDB mod, but I got no display in Oculus Quest 2, though the display was showing on the monitor.
I have tried as mentioned steps mentioned on the GitHub page here :
https://github.com/praydog/REFramework/issues/307
That is:
Turning HDR off and Turning Ambient Occlusion off. Although the display is perfect on my monitor and deleted OpenVR dll to use OpenXR.
I have also turned off the Steam Home in SteamVR, although I am not sure that's what they meant by "Turn off Virtual Desktop"
Any help would be highly appreciated. Thanks in advance.

I would be happy to provide the logs, if the steps to create the logs are provided.

**Comment by praydog** [comment]
Duplicate issue #307
