### ISSUE TITLE
 'Allow Engine TAA" option not saving state. Always starts disabled.

### ISSUE THREAD

**Issue by Milincho** [praydog/REFramework#747]
Is there any way to set the 'Allow Engine TAA" option enabled by default? the game looks worse without it (check in RE4 with the rifle scope and you will see a lot of aliasing and shimmering without TAA).

It gets tedious having to remember and reenable the setting every single time you start the game...    why doesn't it save its state?

**Comment by praydog** [comment]
It's a debug option, this is intentional. None of those options will save under there.

If you want higher scope resolution, then use the scope tweaks option under Graphics to increase the resolution of the scope.

**Comment by Milincho** [comment]
> It's a debug option, this is intentional. None of those options will save under there.
> 
> If you want higher scope resolution, then use the scope tweaks option under Graphics to increase the resolution of the scope.

It's not the resolution. TAA does perfect AA where only DLSS or DLAA are an aliasing and shimmering fest.

**Comment by praydog** [comment]
A side note: It's probably possible for me to enable TAA just on the scope image itself. I personally don't really enjoy having TAA on with the upscaler as the entire image becomes blurry, but I can see where you're coming from for the scope itself.

**Comment by Milincho** [comment]
Why not let that up to the user's choice? I get a better and more stable image with DLAA+TAA+Reshade SmartSharp.
It's easy to check what works better with these high contrast lines:

![image](https://user-images.githubusercontent.com/60118859/232255022-1fbc315b-efbf-4841-932b-0e6ab881da9e.png)

**Comment by rpinheiro0** [comment]
> Why not let that up to the user's choice? I get a better and more stable image with DLAA+TAA+Reshade SmartSharp. It's easy to check what works better with these high contrast edges:
> 
> ![image](https://user-images.githubusercontent.com/60118859/232255022-1fbc315b-efbf-4841-932b-0e6ab881da9e.png)

How did you get DLSS and Reshade working together?

**Comment by Milincho** [comment]
> How did you get DLSS and Reshade working together?

Rename Reshade's dll to d3d12.dll
