### ISSUE TITLE
MHR Reframework unable to initialize

### ISSUE THREAD

**Issue by BRSter** [praydog/REFramework#752]
Unable to initialize and start the game normally, a version before the latest version will load infinitely until the shader is compiled after the loading is complete. The latest version skips the initialization, and the shader compilation starts working directly. The game then crashes before entering the title page.
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/11269010/re2_framework_log.txt)
Unable to upload crash.dmp file since Github tells me not support.

**Comment by praydog** [comment]
Try the newest version here and report back, tried to fix it: https://github.com/praydog/REFramework-nightly/releases/

**Comment by BRSter** [comment]
> Try the newest version here and report back, tried to fix it: https://github.com/praydog/REFramework-nightly/releases/

Thank you for your help, although after re-checking mod that no longer compatible and using older versions the issues has been resolved.
