### ISSUE TITLE
MH RISE SUNBREAK PLUGIN ERROR

### ISSUE THREAD

**Issue by Kirbeh** [praydog/REFramework#758]
Hello! anyone knows why some plugin mods (like rise quest loader) won't open their respective windows, even though it says on reframework that they are loaded? i have the latest version of both reframework and quest loader, and i tried a lot of things already and none seems consistent, although sometimes they appear after a while in game (but usually is not the case)

it also can make the game go with like 30 fps or so instead of the usual 60

here is the log

[re2_framework_log.txt](https://github.com/praydog/REFramework/files/11299517/re2_framework_log.txt)

**Comment by Kirbeh** [comment]
Now it worked when i went to the training area, and this apppeared in the log below the errors:

[2023-04-22 00:44:58.212] [REFramework] [info] [Plugin] [QuestLoader] Found object allocator at {}
[2023-04-22 00:44:58.617] [REFramework] [info] [Plugin] Found via::gui::MessageManager::getMessage at 0x1444c23a0

**Comment by praydog** [comment]
Ask the quest loader developer on Nexus.
