### ISSUE TITLE
DMC5 crashes frequently with PD Upscaler

### ISSUE THREAD

**Issue by arikadovt** [praydog/REFramework#761]
PD Upscaler/DLSS mod seems to be extremely unstable with Devil May Cry 5. Crashes at any point past the prologue are frequent, and trying to adjust the brightness setting also guarantees a crash 100% of the time.

 - OS  Windows 11
 - Graphics card Nvidia RTX 3060
 - CPU Intel Core i7 10700k
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/11348463/re2_framework_log.txt)

**Comment by praydog** [comment]
Not yet correctly implemented in games preceding RE8, including the pre-RT builds of RE2/3/7. It also doesn't work on DX11.

**Comment by arikadovt** [comment]
Thanks for the prompt reply!

Just to leave one last bit here before closing this, I've found that using DLSS version 2.5.1 instead of the most recent version has drastically reduced the likelihood of crashes, although adjusting brightness still always causes a crash. Simply removing the dinput8.dll, adjusting brightness, then re-adding it acts as a way to circumvent this issue for now.

**Comment by Heliumrich** [comment]
> Not yet correctly implemented in games preceding RE8, including the pre-RT builds of RE2/3/7. It also doesn't work on DX11.

Hi sorry to bother, but is this properly implemented for DMC5 now ?
