### ISSUE TITLE
RE4 Remake Crashes on chainsaw.IInventoryController hook

### ISSUE THREAD

**Issue by caiocinel** [praydog/REFramework#763]
**Describe the bug**
Whenever I try to hook any function of the Inventory Controller class, the game crashes instantly, either through the GUI or through sdk.hook(), both cases result in the game crashing.

**Upload logs and any crash dumps**
[re2_framework_log (clean).txt](https://github.com/praydog/REFramework/files/11360052/re2_framework_log.clean.txt)
[reframework_crash.zip](https://github.com/praydog/REFramework/files/11360053/reframework_crash.zip)

**Identify the REFramework version**
Artifacts from commit "ee8402c39f0c4e9029d0391fa95171efa63870f9", but it also occurs in previous commits.

**To Reproduce**
1º Open Developer Tools
2º Open ObjectExplorer
3° TypeName = chainsaw.IInventoryController
5° Right Click on any TDB Method -> Hook

**Expected behavior**
Work as in other situations

**Desktop and VR (please complete the following information):**
Windows 11 22H2
AMD Ryzen 5600
Radeon RX580
32GB

**Comment by praydog** [comment]
Fixed in 933c4d503ec6910f174b178855512e01821038a3

By the way, these are methods that resolve to null pointers. You cannot hook them. You'll want to look at `chainsaw.CsInventoryController` and `chainsaw.InventoryControllerBase` instead.
