### ISSUE TITLE
Resident evil 3 performance

### ISSUE THREAD

**Issue by Andymrx** [praydog/REFramework#764]
Hi, i having playing almost the whole game, and im very frustrated with the performance, the thing its constsntly running with reproyection the 90% of the game, even if i lower all the graphics options to the minimun, i wondering if have something wrong with my setup o this is normal?

I have a ryzen 5 1600 with a rtx 3060ti
Oculus settings its setup on automatic res and 90hz

There is a way to play this vr mod at a smooth 90hz with my setup? Or i just have to conform with the asyncronus warp.. :/

**Comment by praydog** [comment]
Expected with your setup.

There is a separate branch being worked on which may improve performance, but your CPU may still be an issue there.
