### ISSUE TITLE
Add .pdb support?

### ISSUE THREAD

**Issue by KsaNL** [praydog/REFramework#766]
Maybe...

**Comment by praydog** [comment]
Use this: https://github.com/praydog/REFramework/tree/master/reversing/scripts/ida_namer

Then, use this IDA plugin after it's done: https://github.com/Mixaill/FakePDB

**Comment by KsaNL** [comment]
> Use this: https://github.com/praydog/REFramework/tree/master/reversing/scripts/ida_namer
> 
> Then, use this IDA plugin after it's done: https://github.com/Mixaill/FakePDB

Thanks,  I'll check that later.

**Comment by KsaNL** [comment]
I've solve all the problems...
New edition ida need change 'ida.MakeName(ea, name)' -> 'idc.set_name(ea, name, SN_CHECK)'
![image](https://user-images.githubusercontent.com/73447685/235374024-ee4f1217-e85c-47da-860a-d1ce90ba6d3c.png)

https://hex-rays.com/products/ida/support/ida74_idapython_no_bc695_porting_guide.shtml

**Comment by KsaNL** [comment]
Need fix, replace the ' '
![)J6P)UPL1P7A1G(O3 VHI~D](https://user-images.githubusercontent.com/73447685/235374287-04ce595c-474b-4fab-a970-6390fb282bb6.png)
