### ISSUE TITLE
RE7 Steam update broke game. VR mod starts, but stuck in a black screen.

### ISSUE THREAD

**Issue by ehabibeh** [praydog/REFramework#782]
### Discussed in https://github.com/praydog/REFramework/discussions/781

<div type='discussions-op-text'>

<sup>Originally posted by **ehabibeh** May  8, 2023</sup>
Hey guys. I'm new to the use of this VR mod and I believe the new RE7 build 11026049 released yesterday is causing issues with the VR mod. The framework initializes VR, but doesn't start the game fully. After the framework initializes VR, we're stuck in a black void. No sound. I am able to bring up the steam VR interface using the steam button on my controller.

Troubleshooting done:
-Uninstalled the game, deleted the game folder, reinstalled the game, unzipped latest RE7.zip into the game folder.
-Disabled "desktop Theatre"
-Tried the latest RE7TDB.zip
-Tried the dx11 beta with both the latest RE7.zip and RE7TDB.zip files

I've restarted my PC/headset between each troubleshooting step. The only changes I'm aware of since this last worked was the game update. I was able to play successfully about an hour before that update. I'm assuming this is a known issue being worked on because you seem to be on top of things, but still thought it would be wise to bring this to your attention. 

I've been using the mod for a couple days now and I love it! Thanks for your hard work!</div>

**Comment by praydog** [comment]
Turn off HDR system-wide. Also, not enough information provided as in the issue template. I need the log file and system specs, etc...

https://github.com/praydog/REFramework/blob/master/.github/ISSUE_TEMPLATE/bug_report.md


![asdgdg](https://user-images.githubusercontent.com/2909949/236893015-ce8cab51-2018-49a5-aed3-b49d52b3dd05.png)

**Comment by ehabibeh** [comment]
Thanks for the reply. The change in settings didn't seem to make a difference. There wasn't any crash, but here is the .dmp file anyway renamed to .txt. I'm using the latest version of RE7.zip.

**OS Name**: Microsoft Windows 10 Enterprise (64-Bit)
**Version**: 10.0.19045 Build 19045
**CPU**: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, 3696 Mhz, 6 Core(s), 12 Logical Processor(s)
**GPU**: Nvidia GTX 3080
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/11426020/re2_framework_log.txt)

[reframework_crash.txt](https://github.com/praydog/REFramework/files/11426009/reframework_crash.txt)

**Comment by ehabibeh** [comment]
Just an update: 

I downgraded my version of RE7 to the previous version on steam by using the steam console command "download_depot 418370 418371 5762416815192510703". This allowed me to download the files from the previous game build. Once the files were downloaded, I moved them over to my game folder replacing the updated files. Then I reapplied the RE7.zip VR mod files. The mod is now working again! 

This is good as now we know it's a problem after the game updated and nothing local on my end.

**Comment by ehabibeh** [comment]
I've updated the issue's title to make it easier for others to search in the future. I'll just stick with the pre-update files until the VR mod is updated. If anyone need help downgrading their version of RE7 to get VR working again, feel free to send me a message. Thanks again for looking into this!

**Comment by ehabibeh** [comment]
Sorry, just saw this. You have to have RE7 fully downloaded and updated without the VR mod. Copy the downloaded depot files into the RE7 steam folder and overwrite the update files, then install the VR mod. No other depots are needed.

**Comment by ehabibeh** [comment]
Github is a little confusing to me, but I see under the May 18th build the assets show they've been updated 19 hours ago (from now). Does that mean the files have been modified/updated or is that something else? I reported this issue on May 8th, so I was hoping the May 18th release had a fix for you.

**Comment by kentutkudaa** [comment]
> Alright, looks like I figured it out workaround. Solution is very the same as @ehabibeh provided, but there is one moment, which is not obvious.
> 
> 1. Reinstall RE7 (and deleted all mod files)
> 2. Run it
> 3. Select in "Beta" dx11 option (that will downgrade game a bit. This is what originally @ehabibeh tried to do to make VR Mod work, but no chance)
> 4. Run it
> 5. executed this command `download_depot 418370 418371 5762416815192510703` in Steam Console
> 6. Copy depot files in game folder (this step and previous one actually helped @ehabibeh and me as well)
> 7. Run game again
> 8. Delete `re7_config.ini` file in games folder and run game again (that will switch game back to dx12 as it will generate config file again. If not doing that your game will be in DX11 mode as you rollbacked using "Beta" and on launch it generates new config file, which targets DX11 and disables Ray Tracing)
> 9. Finally install latest RE7.zip from Releases tab in GitHub
> 10. Done, you can play VR again :)
> 
> @praydog @ehabibeh pls, pin this post somehow, because I'm more then sure I'm not the only one struggled from this issue :)

damn! I ran into this exact problem yesterday. currently just finished downloading the depot files. Currently wondering if installing nexus 4k texture mod along with the re7vr mod will still work or not with this?

**Comment by praydog** [comment]
Should be fixed on DX11 (non-RT) in 2c09f11a08143963530f5a2ea291e10fbce366ac

Newer builds can be downloaded here: https://github.com/praydog/REFramework-nightly/releases/

If this issue is not related to HDR, or you are knowingly or unknowingly using the DX12 RT build(s), then this will not fix the issue. Please comment here if it has resolved the problem.

**Comment by praydog** [comment]
> (I bet everyone used 1.519 version just because everybody believed it was latest one, but apparently - its not).

Not sure what you're talking about. 1.519 on there is the latest one. It will always be the one shown at the top.
