### ISSUE TITLE
Support symlinks for fs.glob(filter)

### ISSUE THREAD

**Issue by zxeoc** [praydog/REFramework#788]
**Is your feature request related to a problem? Please describe.**
Not exactly. Vortex mod manager deploys the files of mods with symlinks. But fs.glob(filter) has a "is_regular_file()" check, which blocks those mods reading their files deployed by Vortex. For now, players have to deploy those mods manually. Is this by design?

**Describe the solution you'd like**
FS apis support symlink as well as regular files.

**Comment by praydog** [comment]
Fixed in 005c29d58ffa8d2643352aab49538b12e4ffbb52

**Comment by zxeoc** [comment]
Thank you.
