### ISSUE TITLE
RE4 CRASH 

### ISSUE THREAD

**Issue by wowjijiji** [praydog/REFramework#791]
Aafter I put dinput8.dll file inside game doc. it crash my game, BTW I dont think it happen because of GPU, myGPU is 3090 24G, it still Crash

**Comment by kilinnik** [comment]
I have the same problem( 4070 laptop

**Comment by praydog** [comment]
Not enough information. Re-open the issue once you supply the required information and logs as laid out in the issue template.

https://github.com/praydog/REFramework/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by LOWZONEDAYZ** [comment]
Hi, Thank you for your work!
I encountered the same issue as the creator of the post.
If i copy&paste the dinput8.dll inside the installation folder of resident evil 4 2023 and start the game, it crashes to dekstop everytime the 3. logo is finished (When the "orb" with the lighthning appears)

I can see the "REFramework" window stating its initializing 
then its start flickering and when the "orb" logo sequenz starts -> crash

Without the dinput8.dll, the game is starting and running without problems
I didnt get any "reframework_crash.dmp" file though, only the re2_framework_log.txt

Here is a pic of the situation ingame, right before crashing:  [https://ibb.co/2ysXqL2](url)
Here is the the re2_framework_log.txt: [https://github.com/LOWZONEDAYZ/RE4/blob/6102806143a8c5f601699fb42caf6414afaad880/re2_framework_log.txt](url)

Would be nice to see your work in action, in my gameplay, so if if possible, i would like to ask if you could take a look
I hope you can see this post, after you closed the thread
Thank you
regards LC
