### ISSUE TITLE
RE4 auto disappear during REframework initializing

### ISSUE THREAD

**Issue by parkouryule** [praydog/REFramework#792]
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/11473693/re2_framework_log.txt)
RE4 game window auto disappear when REframework initializing, but its process still showing in process list, just with 0 CPU usage. so it is  not a crash.
I am using newest REframework for it.
Win 11 21H2
AMD 6800U
portable win device.

**Comment by praydog** [comment]
Pirated copies are not supported. 

https://cursey.github.io/reframework-book/#help-my-pirated-copy-does-not-work
