### ISSUE TITLE
GAME CRASH

### ISSUE THREAD

**Issue by Joker091944** [praydog/REFramework#793]
**Describe the bug**
A clear and concise description of what the bug is. If the bug only started to happen after a certain REFramework update, let us know which version the bug appeared in.

**Upload logs and any crash dumps**
Locate the `re2_framework_log.txt` in your game directory and upload it along with the issue.
If you crashed, upload the `reframework_crash.dmp` file as well.

**Identify the REFramework version**
If the REFramework version or commit hash is known, submit this information.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop and VR (please complete the following information):**
 - OS (e.g. Windows 11)
 - Graphics card
 - CPU

**Steam Deck/Linux (please complete the following information):**
 - Proton version
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/11483916/re2_framework_log.txt)

**Virtual Reality (please complete the following information):**
 - Headset model
 - Runtime (OpenVR or OpenXR)

**Additional context**

**Comment by praydog** [comment]
Pirated copies are not supported.

https://cursey.github.io/reframework-book/#help-my-pirated-copy-does-not-work
