### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Pocokk** [praydog/REFramework#794]
Dear praygod,

I've found this program of yours just today and I'm truly amazed what you have accomplished here! Also I've seen that the latest "official" release was in February, but since then you've worked on this project countless hours. When can we expect yet another full release? In weeks time or during the summer? 

Thank you in advance!

**Comment by Pocokk** [comment]
Well, the nightly release is even older, May 18, 2022, 1 year old.

**Comment by praydog** [comment]
It's not. It just says that. Look at the dates next to the files.

**Comment by Pocokk** [comment]
Tricky, apologize, thank you and sorry for the bother.
