### ISSUE TITLE
MHR crashing 

### ISSUE THREAD

**Issue by medlolzz** [praydog/REFramework#799]
**Describe the bug**
I installed MHR Damage overlay and it's crashing randomly

**Upload logs and any crash dumps**
Locate the `re2_framework_log.txt` in your game directory and upload it along with the issue.
If you crashed, upload the `reframework_crash.dmp` file as well.

**Identify the REFramework version
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/11515991/re2_framework_log.txt)
**
If the REFramework version or commit hash is known, submit this information.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop and VR (please complete the following information):**
 - OS Windows 10
 - Graphics card 2060
 - CPU i5-10400
 

reframework crash dmp is not supported cant upload it

**Comment by praydog** [comment]
Please upload the reframework_crash.dmp if you can. I can see that it's crashing within REFramework itself, but I can't figure out exactly where without this file. You can rename the extension to something else like .txt to get it to upload, or you can upload it to some other service if you prefer.

**Comment by medlolzz** [comment]
[reframework_crash.txt](https://github.com/praydog/REFramework/files/11520993/reframework_crash.txt)
i dont know why but when I rename it to txt,it's garbled...

**Comment by medlolzz** [comment]
[reframework_crash.txt](https://github.com/praydog/REFramework/files/11521211/reframework_crash.txt)

**Comment by praydog** [comment]
Fixed in cfd10598de4d89026ab9988451691e6f19c554da

Get new builds from: https://github.com/praydog/REFramework-nightly/releases/

**Comment by medlolzz** [comment]
Thank you

**Comment by medlolzz** [comment]
Hi,im sorry but my game is still crashing...

**Comment by medlolzz** [comment]
[reframework_crash.txt](https://github.com/praydog/REFramework/files/11522331/reframework_crash.txt)
here's the newer txt

**Comment by praydog** [comment]
The `re2_framework_log.txt` would be helpful too. This time the crash is not coming from REFramework itself it looks like from your latest dump.
