### ISSUE TITLE
RE4 Game Crash when using dinput8.dll

### ISSUE THREAD

**Issue by LOWZONEDAYZ** [praydog/REFramework#803]
Hi, Thank you for your work!
I encountered the problem, some other user stated already, about the game crashing, when copy&paste your dinput8.dll file inside the game installation folder. As the other issue were closed, due to not enough info, i hope this is enough description of the issue, as i unfortunately dont have more or cant describe it anymore than this

If i copy&paste the dinput8.dll inside the installation folder of resident evil 4 2023 and start the game, it crashes to dekstop everytime the 3. logo is finished (When the "orb" with the lighthning appears)

I can see the "REFramework" window stating its initializing
then its start flickering and when the "orb" logo sequenz starts -> crash

Without the dinput8.dll, the game is starting and running without problems
I didnt get any "reframework_crash.dmp" file though, only the re2_framework_log.txt

Here is a pic of the situation ingame, right before crashing: [https://ibb.co/2ysXqL2](https://github.com/praydog/REFramework/issues/url)
Here is the the re2_framework_log.txt: [https://github.com/LOWZONEDAYZ/RE4/blob/6102806143a8c5f601699fb42caf6414afaad880/re2_framework_log.txt](https://github.com/praydog/REFramework/issues/url)

Sometimes, when im back to desktop i also get an window pop up stating a fatal 3D error (if needed i can try reproducing the error till i get the message again, maybe)

Would be nice to see your work in action, in my gameplay, so if if possible, i would like to ask if you could take a look

Thank you
![re4crash](https://github.com/praydog/REFramework/assets/117558664/68a75df2-8e3a-47cd-93c3-8f73bbe8f41c)

regards LC
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/11523271/re2_framework_log.txt)

EDIT: i tried it with the actual stable version and the newest version (only the .dll file of course)

**Comment by Rastapsp** [comment]
Tengo la versión empress de resident 4 remake en steamdeck y se bloquea en el mismo punto por conflicto con el dinput8.dll

**Comment by Rastapsp** [comment]
Leí que alguien lo consiguió arreglar añadiendo el comando dinput8 n,b desde el archivo user.reg pero yo no lo tengo claro

**Comment by praydog** [comment]
Pirated copies are not supported.

**Comment by Rastapsp** [comment]
Sera porque no te apetece, ya te digo yo que lo conseguiremos poner, que reframework no lo has inventado ni tú ni Capcom

**Comment by Rastapsp** [comment]
Pero gracias por la ayuda

**Comment by Anonym121** [comment]
@Rastapsp Any idea about how to make it work in empress?
