### ISSUE TITLE
Game crashing issue with only the dinput8.dll

### ISSUE THREAD

**Issue by zerocouse** [praydog/REFramework#804]
[Uploading re2_framework_log.txt…]()
Downloaded the latest release for the RE4 Remake dinput8.dll
It can run past the logo and enter the menu but immediately crash to desktop shortly after that.
Need to delete the dll for the game to run without crashing issue, but I need the dll to use additional stuff.

note: for some reason having some difficulties uploading the log here, so I uploaded through google drive
https://drive.google.com/file/d/1RpGZxnjB1zS526FD4iQnHIt-eUtGq5RZ/view?usp=sharing

Thanks in advance
[Uploading re2_framework_log.txt…]()

**Comment by praydog** [comment]
Pirated copies are not supported.
