### ISSUE TITLE
Monster hunter rise app is closing but in background it is still running

### ISSUE THREAD

**Issue by asoako98** [praydog/REFramework#810]
Hi, 

Good day!

Current Specs
Ryzen 9 5900x
5700xt
32gb Ram
Windows 11

Issue: Upon opening MHR in Windows 11 the application closes but in background it is still running.

Release: v1.526

![Screenshot 2023-05-29 012558](https://github.com/praydog/REFramework/assets/30582112/cee34342-5851-4f04-80d8-2eaac081cb99)

![Screenshot 2023-05-29 012621](https://github.com/praydog/REFramework/assets/30582112/1312a168-93c0-426b-8617-17e5d68f4a68)

No Mods attached as of today.

Logs are also attached.
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/11585295/re2_framework_log.txt)

Let me know if you need further assistance on this to replicate thanks!

**Comment by WetU** [comment]
REFramework doesn't support pirate version
