### ISSUE TITLE
Crashing upon setup for RE4

### ISSUE THREAD

**Issue by wazzu232** [praydog/REFramework#812]
Hello,

I went to setup reframework for RE4 and have an issue with it crashing when loading up. I have tried numerous diff versions including the one you listed on nexusmods updated in april, the original one you created after game launch, as well as the newest developer build you listed on the main repo page under the (newer builds click here) link that was updated 3 days ago.

They all produce the same crash at the exact same spot.

I had this issue before with MHR and ended up finding out from you it was being caused by a error created because I had oculus runtime library installed on my pc cuz I have an oculus quest 2. However I AM NOT trying to play this in vr. Justy my pc.

Last time you fixed the issue but i got it working before that by unistalling all oculus software. However, this did not fix the crashing with re4.

Please help. I have attached my log file
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/11632956/re2_framework_log.txt)

**Comment by praydog** [comment]
Pirated copies are not supported.
