### ISSUE TITLE
SF6 Game's crashing after a VS loading screen

### ISSUE THREAD

**Issue by ProhorovIlja** [praydog/REFramework#815]
**Describe the bug**
After installing the latest stable or nightly release versions of reframework for Street Fighter 6 the game starts to crash every single time after a VS loading screen, right before getting me into a mode I selected in fighting grounds.
If I uninstall reframework, I can get into any mode just fine, the game won't crash.
But with reframework installed, it crashes all the time right after VS screen starts to fade out.

**Identify the REFramework version**
It happens with both versions of ReFramework stable 1.5.1 and nightly build 1.536-
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/11645410/re2_framework_log.txt)

**To Reproduce**
1. Open Street Fighter 6
2. Go to Fighting Grounds
3. Choose any game mode inside of it
4. Select a stage, fighters, etc.
5. Wait for a VS loading screen to end.
6. The loading screen will start to fade out and crash right after it.

**Expected behavior**
After the loading screen fades out, I'll get inside a selected game mode without crashing

**Screenshots**
Instead of a screenshot, I've uploaded a small video clip of an entire thing, from booting up the game, up to a point, when it crashes.

**Desktop and VR (please complete the following information):**
— OS Windows 10 x64 Enterprise
— Graphics card Nvidia GTX 1080 TI Xtreme Edition 11gb
— CPU Intel Core i7 8700k
— Ram 32gb ddr4
— SSD 250 and 1tb Samsung

**Additional Information**
https://github.com/praydog/REFramework/assets/47087189/337ef0cf-514b-40b3-99f9-06e90d16a4d5

**Comment by ProhorovIlja** [comment]
[reframework_crash.txt](https://github.com/praydog/REFramework/files/11645414/reframework_crash.txt)

Can't find a way to upload reframework_crash.dmp
Had to change it's extension from dmp to txt to upload it here, pls change it back to dmp in order to view it

**Comment by praydog** [comment]
Try turning off shader warmup and delete the shader cache in the game folder. I've seen this same report from a few people but the way it's crashing doesn't really make sense.

**Comment by praydog** [comment]
For reference, can you try the RE4 build and see if the crashing goes away?

**Comment by praydog** [comment]
I found a way to reproduce. I'll see if it's fixable.

**Comment by praydog** [comment]
Should be fixed in e072704e5efe620376375e87d93be6a8ba139068

Please download the latest nightly build and let me know if it has fixed it. https://github.com/praydog/REFramework-nightly/releases/download/latest/SF6.zip

**Comment by praydog** [comment]
Confirmed fixed by the user on Discord.
