### ISSUE TITLE
SF6 Freecam, Disable Character Movement option not working

### ISSUE THREAD

**Issue by marian0066** [praydog/REFramework#816]
Basically the Disable Character Movement option is not doing anything, I have the latest version of REFramework, but it just doesn't want to stop the characters from moving
Any idea why?

**Comment by praydog** [comment]
Yes, it's there by default in every implementation of REFramework. I've removed the option now in the latest version.

I suggest you come over to the [Modding Haven](https://discord.gg/9Vr2SJ3) Discord, alphaZomega has a Lua freecam here with more functionality than base REFramework for SF6.
