### ISSUE TITLE
SF6 will crash on start up when using the upscaler and adjusting settings in NV profile inspector.

### ISSUE THREAD

**Issue by Whatsmyename** [praydog/REFramework#817]
**Describe the bug**
After installing the latest stable or nightly release versions of reframework and the latest upscaler beta from nexusmods I can launch into Street Fighter 6 and use DLSS with no issues and play the game normally. However, after changing the anti-aliasing and LOD bios settings in Nvidia profile inspector the game will crash after REframework tries to start up at the title screen. The only way to solve the issues is to close out Nvidia profile inspector completely.

**Upload logs and any crash dumps
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/11647599/re2_framework_log.txt)
[reframework_crash.txt](https://github.com/praydog/REFramework/files/11647601/reframework_crash.txt)

**Identify the REFramework version**
v1.5.1
v1.540
Upscaler Beta GitHub developer build a58158f

**To Reproduce**
Extract upscaler beta dinput.dll into main directory folder
Open Street Fighter 6
REFramework and the game launch normally.
Exit the game.
Open Nvidia profile inspector
Change Anti-aliasing transparency supersampling settings
Change texture filtering LOD Bias (DX) settings
Apply changes
Open Street Fighter 6
The game will crash on the title screen

**Expected behavior**
The game will launch with REFramework and DLSS enabled and run normally.

**Screenshots**
I'll upload a clip

**Desktop and VR (please complete the following information):**
 - OS Windows 11 Pro
 - RTX 3090 FE
 - Ryzen 9 5900X

Additional Information
https://github.com/praydog/REFramework/assets/129132579/090602bd-aa86-4bac-b22e-85281d2df346

**Comment by praydog** [comment]
SF6 is currently not supported with the upscaler nor is the `master` branch merged into `pd-upscaler` yet, but it is being looked into.

**Comment by Whatsmyename** [comment]
I gotcha. Thanks for the clarification.

**Comment by praydog** [comment]
Fixed in 0ed072757a7687dad5443ef7217fa0fa98c12aa0.

Download upscaler builds from https://github.com/praydog/REFramework/actions

Instructions are the same as RE4.

**Comment by Whatsmyename** [comment]
Oh wow, that was fast! I'll try it out later.

**Comment by 88MPHARU** [comment]
hello, ive encountered this error recently, am trying to play around with ray tracing + dlss in sf6 and its crashing, is it because im trying to use DLSS4?
