### ISSUE TITLE
Hope to finally can play RE Village

### ISSUE THREAD

**Issue by mageddo** [praydog/REFramework#82]
Bought then refunded Resident Evil Village for  one reason, the game just drops the FPS at the cutscenes, now I know why, Denuvo it's the reason. 

This mod is a hope so I finally can enjoy the game, I will re buy the game and test it, if it works I will be glad to make a donation, have you a PayPal or something?

**Comment by mirh** [comment]
It's not denuvo, it's capcom awful drm.
