### ISSUE TITLE
Monster Hunter Rise Freezing after TU 6

### ISSUE THREAD

**Issue by imGenoo** [praydog/REFramework#822]
**Describe the bug**
After installing latest github reframework and TU 6. Freezing when joining new event quest with double narga and lucent narga. Also New Urgent quest with Primordial Malenzo freezes as soon as you join quest. I disabled all installed mods and still freezes.

**Upload logs and any crash dumps**
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/11685045/re2_framework_log.txt)

**Identify the REFramework version**
Latest v1.551

**To Reproduce**
Play Primordial urgent quest. Instant freezing. Ply double narga and lucent narga event quest. Will freeze within 4-10 minutes of playing.

**Desktop and VR (please complete the following information):**
 - Windows 10
 -  GTX 970
 - Intel(R) Core(TM) i7-10700F

**Comment by ParticleG** [comment]
I've experienced the same error after upgrade my game.

**Comment by imGenoo** [comment]
Ok, for those of you experiencing freezing. The sharpness mod is the cause of the issue. Remove the .lua file from autorun and it will fix it.
