### ISSUE TITLE
RE4R + REFramework crash 

### ISSUE THREAD

**Issue by spoopmark** [praydog/REFramework#828]
**Describe the bug**
Using REFramework causes game to crash on startup

**Upload logs and any crash dumps**
[re2_framework_log MODS.txt](https://github.com/praydog/REFramework/files/11711193/re2_framework_log.MODS.txt)
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/11711194/re2_framework_log.txt)
couldn't find the dump file 

**Identify the REFramework version**
exact version unknown, but latest version (and nightly build- nightly crash log not included) were tested.

**To Reproduce**
1. launch game with d8input.dll in game folder
2. wait

**Expected behavior**
REFramework should launch and not cause the game to crash

**Desktop and VR (please complete the following information):**
 - OS: Win 10
 - GPU: 1050ti
 - CPU: Core i3-10100

**Additional context**
I included the crash log with mods and without because I happened to have opened RE4R with mods too
removing or bypassing the dll will make the game work (for obvious reasons) but the game loads up to "Quixel Megascans" and starts the next loading scene but crashes instead.

**Comment by praydog** [comment]
Pirated copies are not supported.
