### ISSUE TITLE
Request: Version of RE8 framework with only the performance enhancements

### ISSUE THREAD

**Issue by lethargicwaldo** [praydog/REFramework#83]
Hello,

I am a Mod for the Resident Evil: Village speedrun community. We have been having quite a bit of discussion regarding allowing this tool to be used for speedruns, but have a request as some parts of the tool would allow for cheating occur.

Would it be possible to get a version of this with just the anti-stutter and performance enhancements that we could both allow and disseminate to the community?

Any help would be greatly appreciated!

**Comment by praydog** [comment]
I believe this is already possible by building with the `BAREBONES` flag. It removes all features other than the stutter fix already. I'll see if I can get an automated build going for it.

**Comment by praydog** [comment]
You can now download a build containing only the stutter fixes here:
https://github.com/praydog/REFramework/releases/tag/v1.06.2
https://ci.appveyor.com/project/praydog/reframework/branch/master/artifacts
