### ISSUE TITLE
RE2 VR Mod - Can't see Leon's Body out of Right Eye

### ISSUE THREAD

**Issue by LightningDJ98** [praydog/REFramework#837]
Hi There,

I downloaded the game and added the mod folders, and everything seems to be working perfectly fine. The only issue I am having is that I can't see Leon's body out of my right eye. I can see him in both eyes when the game is paused, but not during gameplay. I tried messing with the graphic settings, but nothing seems to be working. Has anyone else had this issue before? Any help would be appreciated. Thank you in advance.

**Comment by praydog** [comment]
Duplicate issue #400. 

This is fixed in the `pd-upscaler` branch builds which you can download from the [Actions](https://github.com/praydog/REFramework/actions) page.

**Comment by LightningDJ98** [comment]
Hello,

Strangely enough the issue fixed itself after I got the Police outfit. It seems to only affect the jacket outfit at the beginning. Thank you for your help.
