### ISSUE TITLE
RE8 Crash on Startup

### ISSUE THREAD

**Issue by oduska** [praydog/REFramework#84]
I've tried a few different versions of the dinput8.dll and it all leads to crashes.

The only time it didn't immediately crash I got this error:

"REFramework error: Failed to hook UpdateTransform"

Thank you.

**Comment by BitKovin** [comment]
Same problem

**Comment by binwnid** [comment]
Same but didn't get any error or notice. The game start and close right away before main menu pop up

**Comment by praydog** [comment]
Fixed in scripting branch.
