### ISSUE TITLE
MHRSB game are freeze when the monster was defeated

### ISSUE THREAD

**Issue by NoirroseLunalyn** [praydog/REFramework#877]
Help please My Monster hunter rise Sunbreak Freeze when the quest is done ! I use laptop to play this game I tried different version of Reframework spec is : CPU AMD ryzen 5000series GPU Radeon 6500rx ram:16gb windows 11 Please help I tried many different ways
It's not crashing when Launching the game but to ending the quest the game's freeze Thank you for helping !
![image](https://github.com/praydog/REFramework/assets/141849012/23d27350-9da4-4fac-bf0c-de46e2f4d3f3)
So here what's look likes.
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/12329697/re2_framework_log.txt)
When the monster is defeated the game's freeze

**Comment by dtlnor** [comment]
some of your script might cause error. like : Buffer.lua, SpiritBirds.lua, as they fail to load its json config in \data folder.
disable all your script to see if it is scirpt problem.

**Comment by NoirroseLunalyn** [comment]
> some of your script might cause error. like : Buffer.lua, SpiritBirds.lua, as they fail to load its json config in \data folder. disable all your script to see if it is scirpt problem.

thank you ! I will try it !

**Comment by NoirroseLunalyn** [comment]
> some of your script might cause error. like : Buffer.lua, SpiritBirds.lua, as they fail to load its json config in \data folder. disable all your script to see if it is scirpt problem.

I tried disable all the script still freeze and then I remove reframework it's work normal why i don't understand ?

**Comment by dtlnor** [comment]
> > some of your script might cause error. like : Buffer.lua, SpiritBirds.lua, as they fail to load its json config in \data folder. disable all your script to see if it is scirpt problem.
> 
> 
> 
> I tried disable all the script still freeze and then I remove reframework it's work normal why i don't understand ?

have you tried the latest reframework from reframework-nightly?

**Comment by NoirroseLunalyn** [comment]
> > > some of your script might cause error. like : Buffer.lua, SpiritBirds.lua, as they fail to load its json config in \data folder. disable all your script to see if it is scirpt problem.
> > 
> > 
> > I tried disable all the script still freeze and then I remove reframework it's work normal why i don't understand ?
> 
> have you tried the latest reframework from reframework-nightly?

I tried but it's okay now i found the issues now Thank you !
