### ISSUE TITLE
The data obtained through the Lua and C++ APIs are not the same

### ISSUE THREAD

**Issue by Traveller23** [praydog/REFramework#878]
**Describe the bug**
The game is SF6.

C++ codes:
```cpp
const auto kGBattleType = kTdb->find_type("gBattle");
const auto kSPlayer = kGBattleType->find_field("Player")->get_data<API::ManagedObject *>(nullptr);
const auto kMcPlayer = kSPlayer->get_field<common::SystemArray>("mcPlayer");
auto player_count = kMcPlayer->GetSize();
```
`common::SystemArray::GetSize()` is copied from "REFramework/shared/sdk/SystemArray.cpp" with some slight modifications:
```cpp
class SystemArray : public reframework::API::ManagedObject {
  int32_t SystemArray::GetSize() {
    static auto system_array_type = API::get()->tdb()->find_type("System.Array");
    static auto get_length_method = system_array_type->find_method("GetLength");
  
    return get_length_method->call<int32_t>(API::get()->get_vm_context(), this, 0);
  }
}
```
Result: When in the title screen, `player_count` is 0; after entering the training ground, `player_count` is always 1.

Lua codes:
```lua
_gBattle = sdk.find_type_definition("gBattle")
if not _gBattle then return end
local sPlayer = _gBattle:get_field("Player"):get_data(nil)
local cPlayer = sPlayer.mcPlayer
_playerCount = cPlayer:get_size()
```

Result: Whether in the title screen or the training ground, `_playerCount` is always 6.

**Identify the REFramework version**
```bash
$ cat reframework_revision.txt
87b3d6d6d48261def3dde61e93da88900b17d3f4
```

**Desktop and VR (please complete the following information):**
 - OS: Windows 10

**Comment by praydog** [comment]
Change the get_field to retrieve a pointer and then deference it. get_field retrieves the pointer to the field inside the object, not a pointer to what's pointed to by the field. So you need to do (*kMcPlayer) instead of how you're doing it now, along with adding a * to the get_field template parameter for the array.
