### ISSUE TITLE
RE2 Vignette not disabled at startup for third person camera

### ISSUE THREAD

**Issue by abi-21** [praydog/REFramework#88]
I'm playing in regular third person but after I start the game, vignette isn't disabled until I check then uncheck first person camera.

**Comment by LuckMic** [comment]
Hi... there is an option to turn off/on the vignette.  In re2_fw_config.txt you can find "FirstPerson_DisableVignette=false", simply change it to "true".

**Comment by abi-21** [comment]
> Hi... there is an option to turn off/on the vignette. In re2_fw_config.txt you can find "FirstPerson_DisableVignette=false", simply change it to "true".

Hi, it still doesn't disable it at startup until I check first person camera.

**Comment by praydog** [comment]
Fixed in 9cbd5189a87e6a211a2972c21e1d7b52cc30712f. FirstPerson no longer needs to be enabled for this, it has its own independent option under "Camera" now.
