### ISSUE TITLE
RE2 VR > machine room boss disappears and never comes back...

### ISSUE THREAD

**Issue by Award55555** [praydog/REFramework#880]
I found an issue with both my computers, in Hardcore level in the fight with the boss at the machine room, there's a moment he disappears and never comes back. Problem is solved removing the VR framework.

WIndows 10 GPU RTX 3080/4090
Open VR with Oculus Quest

**Comment by praydog** [comment]
Duplicate issue #131

https://cursey.github.io/reframework-book/troubleshooting/VR-Troubleshooting.html#in-re2
