### ISSUE TITLE
Zombie with a REALLY bright head in the Library (RE2)

### ISSUE THREAD

**Issue by Cyborgcr** [praydog/REFramework#889]
**Description**
In the library in the Police Station in RE2, one of the zombies' head is blindingly bright. This most likely only appears on the recent "[Merge branch 'master' into pd-upscaler #571](https://github.com/praydog/REFramework/actions/runs/5990136976)" version of the mod, though I'm not sure.

**REFramework version**
Version downloaded from "[Merge branch 'master' into pd-upscaler #571](https://github.com/praydog/REFramework/actions/runs/5990136976)" in the Actions tab

**To Reproduce**
1. Open the game with the mod installed, I specifically used the OpenXR runtime (deleted openvr_api.dll in the game files)
2. Go inside the library in the police station, for me specifically this was the first time going inside the library, from the second floor
3. Look at one of the zombies 

**Expected behavior**
Just like the other zombies in the library and the rest of the game, this one isn't supposed to have the sun for a head.

**Screenshots**
I will provide screenshots later if I can

**Desktop and VR:**
 - Windows 10
 - NVIDIA GeForce RTX 2060 SUPER
 - Intel Core i5-10400F 2.90GHz

**Virtual Reality:**
 - Meta Quest 1 (connected to PC via Quest Link)
 - OpenXR

[re2_framework_log.txt](https://github.com/praydog/REFramework/files/12448547/re2_framework_log.txt)

**Comment by vinionsinho** [comment]
Disable bloom to fix those problems

**Comment by Cyborgcr** [comment]
> Disable bloom to fix those problems

Yeah, I saw something about bloom in the Discord server as soon as I submitted this issue, I'll definitely do that and see if it's resolved.
