### ISSUE TITLE
pd-upscaler RE7 rt version black screen on main menu

### ISSUE THREAD

**Issue by nwWNTR** [praydog/REFramework#893]
Main menu is not showing in vr, but I can still hear sound. Gameplay seems to display correctly.

OS: Windows 10
CPU: intel Core i5-12400
GPU: Nvidia RTX 4070
VR Headset: HTC VIVE

[re2_framework_log.txt](https://github.com/praydog/REFramework/files/12473238/re2_framework_log.txt)

**Comment by praydog** [comment]
Fixed a while ago
