### ISSUE TITLE
[Request] Option to remove the sharpening filter

### ISSUE THREAD

**Issue by LHTakahashi** [praydog/REFramework#90]

**Comment by praydog** [comment]
Added in the scripting branch for RE2 and RE3.

Download the scripting branch here: https://ci.appveyor.com/project/praydog/reframework-dev/build/artifacts

Drop all of the files in this folder here into the `autorun` directory in your game directory: https://github.com/praydog/REFramework/tree/sdk-improvements-re7-mhr/scripts

e.g. `G:\SteamLibrary\steamapps\common\RESIDENT EVIL 2  BIOHAZARD RE2\autorun`
