### ISSUE TITLE
Characters rendering different parts in each eye camera

### ISSUE THREAD

**Issue by Duncro** [praydog/REFramework#906]
**Describe the bug**
Opened it up on Quest 2 using virtual desktop, VR boots up nicely, watch the start of the game story of the truck driver all is good. Leon's driving scene starts, each eye renders different parts of him, only his head is rendered in both. Get to the gas station, see a headless model of him i think rendered in one eye standing by the cop car, his own body still rendered wonkily. Start playing, arms are rendered in one eye not the other.

Relaunch after deleting openvr_api file same thing. 

Tried it through oculus with link cable, total chaos, renders on desktop, headset keeps saying "waiting" when in vr view

**Upload logs and any crash dumps**
Locate the `re2_framework_log.txt` in your game directory and upload it along with the issue.
If you crashed, upload the `reframework_crash.dmp` file as well.

**Identify the REFramework version**
1.5.1

**To Reproduce**
See description

**Expected behavior**
everything rendered in both eyes

**Screenshots**
Doesnt work

**Desktop and VR (please complete the following information):**
 - OS (e.g. Windows 11)
 - Win11
 - Graphics card
 - AMD 6600 XT
 - CPU
 - AMD 5600

**Steam Deck/Linux (please complete the following information):**
NA

**Virtual Reality (please complete the following information):**
 - Headset model
 Quest 2
 - Runtime (OpenVR or OpenXR)
 Tried both by later deleting the openvr_api file

**Additional context**
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/12731675/re2_framework_log.txt)
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/12731846/re2_framework_log.txt)

**Comment by praydog** [comment]
Duplicate issue #400.

Options:
* Use the `pd-upscaler` branch
* Use the old non-RT version of RE2 with TDB66 build
* Change Leon's outfit
