### ISSUE TITLE
No longer compatible with VorpX

### ISSUE THREAD

**Issue by shagerich** [praydog/REFramework#91]
I just tried this for the first time today and it no longer works with VorpX, at least for Resident Evil 3 Remake. Works in desktop mode, just not in VR.

**Comment by Virtual-Residence** [comment]
Praydog, I love the work you have been doing on the VR RE2 & 3 remake mods. Any chance a smaller YouTuber could get the mod early to make a video about it? If not I understand, however I would really love to make some content around it! Let me know either way, and sorry if this isn't the best way to grab your attention, I wasn't sure how to contact you.

**Comment by praydog** [comment]
Fixed with the VR release.
