### ISSUE TITLE
Resident evil 4 can't work with 1.5.2

### ISSUE THREAD

**Issue by Lioncky** [praydog/REFramework#911]
Game Process No Respond,1.5.1 and before can play normally

**Comment by xielu314** [comment]
Me neither.I re-installed RE4 and tried the latest stable(v1.5.2) and newer(v1.585-) REFramework, but it just crashed after the animation of RE Engine showed.

**Comment by Lioncky** [comment]
Something must be wrong, I build with the latest code, same as the latest version.
Game not show and only appeared in the taskbar.

**Comment by Com3Carne** [comment]
The same thing is happening here.
When using slightly older versions the game opens.
