### ISSUE TITLE
Temporal Upscaling not showing up in RE2

### ISSUE THREAD

**Issue by someusernamee** [praydog/REFramework#919]
Not sure if it's broken right now or if I'm not following the instructions right, but I seemed to have done everything correctly but no matter what I do the option to enable temporal upscaling never shows up in RE2. I'm assuming it just doesn't work anymore for whatever reason but has anyone been able to get it working?

**Comment by gatnom84** [comment]
The issue is this main version of REFramework. Get this fork for example and it will work:
https://github.com/yobson1/REFramework/releases/tag/empress

**Comment by IceLancerSR** [comment]
> Not sure if it's broken right now or if I'm not following the instructions right, but I seemed to have done everything correctly but no matter what I do the option to enable temporal upscaling never shows up in RE2. I'm assuming it just doesn't work anymore for whatever reason but has anyone been able to get it working?

I had the same issue. Turned out that it didnt wont to work with DX11
Once i enabled dx12 in game it was working.
DX11 menu would start to flicker and then entire framework would crash

And only with that empress edition.
Any never version of framework wont even recognize upscaler plugin

Using steam version DX11 NO-RT 
![Screenshot 2023-12-16 024400](https://github.com/praydog/REFramework/assets/4452102/8fcf5b2d-7d7d-428c-976a-2e3107642899)

**Comment by praydog** [comment]
> > Not sure if it's broken right now or if I'm not following the instructions right, but I seemed to have done everything correctly but no matter what I do the option to enable temporal upscaling never shows up in RE2. I'm assuming it just doesn't work anymore for whatever reason but has anyone been able to get it working?
> 
> I had the same issue. Turned out that it didnt wont to work with DX11 Once i enabled dx12 in game it was working. DX11 menu would start to flicker and then entire framework would crash
> 
> And only with that empress edition. Any never version of framework wont even recognize upscaler plugin
> 
> Using steam version DX11 NO-RT ![Screenshot 2023-12-16 024400](https://private-user-images.githubusercontent.com/4452102/290964085-8fcf5b2d-7d7d-428c-976a-2e3107642899.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2OTI4MzEsIm5iZiI6MTcwMjY5MjUzMSwicGF0aCI6Ii80NDUyMTAyLzI5MDk2NDA4NS04ZmNmNWIyZC03ZDdkLTQyOGMtOTc2YS0yZTMxMDc2NDI4OTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTZUMDIwODUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjJiYjAwMWY2YThhMDM5MjY2NjE3ZDMwYjBkMzUwZDljOTlhN2MwMjI2ZWNiMDMxOTk3MWVmMGQ5OTllMTJkZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nybt--lNewT9_BLVPPXmhiGcFDI_W4yQqTe4BFDZlSE)
> 
> P.S to get it to work i copied all files to root of the game. FSR and Upscaler dll
> 
> P.P.S Performance completely tanked for me. I was at 110fps and with this up , i dropped down to 15fps... So ..

Old builds are not supported with the upscaler
