### ISSUE TITLE
REFramework error: Unable to find UpdateTransform pattern.

### ISSUE THREAD

**Issue by NebbaChin** [praydog/REFramework#923]
Whenever I launch RE2 this error pops up and I cannot do anything. 
![image](https://github.com/praydog/REFramework/assets/149261352/ef02f706-8ec8-447b-b07e-c7e5bdece441)

[re2_framework_log.txt](https://github.com/praydog/REFramework/files/13196367/re2_framework_log.txt)

I'm using the latest version v1.593-.

**To Reproduce**
1. Launch RE2
2. Wait for the framework to initialize
3. Error pops up

![image](https://github.com/praydog/REFramework/assets/149261352/f1cbae55-bfce-43eb-a0d6-9170684c9246)

**Desktop and VR (please complete the following information):**
 - OS W10
 - Graphics card RTX 2060
 - CPU Ryzen 5 2600

**Virtual Reality (please complete the following information):**
 - Headset model Quest 2 via virtual desktop/airlink/link(error persists with all forms of link)
 - Runtime OpenXR

**Additional context**
Tried using both versions of the mod, regular one turns up with the "UpdateTransform" error and TBD with an "exception" error.

**Comment by praydog** [comment]
You are not using v1.593 at all. You are using a very old build.

**Comment by NebbaChin** [comment]
I might be blind or stupid or both. Grabbed the latest one directly from your profile now and this one works, thank you for your time!
