### ISSUE TITLE
RE3VR: Disable controler lookin up and down?

### ISSUE THREAD

**Issue by zzrailzz** [praydog/REFramework#924]
Is there a setting that disables the right quest controller joystick from looking up and down in resident evil 3? With RE2 it goes right and left which I want  but with RE3 it also moves the camera up and down which is making me disoriented and nauseous.

EDIT: Im new to these forums and am not sure how to delete a post but I found my answer searching through the other posts so this can be deleted. Thankyou for your work on these awsome mods. After playing in VR Ill never be able to go back to flatscreen resedent evil 😁

**Comment by praydog** [comment]
Get past the first few minutes of the game
