### ISSUE TITLE
REs dont work as they did before. 

### ISSUE THREAD

**Issue by Sawtooth76** [praydog/REFramework#927]
In the past I could play RE2/3/7/8 in VR with working motion controls.
If a issue came up, I only had to update the RE Framework and everything was fine
Actually I played RE7 last week. However this week I cant play any of them. Also bought RE4 today... same problem
Im not sure if the last steam client update could be the culbrit.? Just noticed some differences in the VR GUI

Do I start as usual while using the openvr-api the game starts on the Desktop only, not in VR.
(VR Cinema Mode is still deactivated)
Do I start while using openxr VR works fine but the motion controllers dont work. 

I updated RE Framework to the last Version 1.595 and tried one version earlier

 - OS Win11
 - RTX 4080
 - Intel I5 (this year)
 - HP Reverb G2
 - Steam Index Controller & HP Motion Controller

**Comment by Sawtooth76** [comment]
RES unplayable since ~16.11. Strong performance issue now (111ms instead of 11ms). Noticed there are 2 flat Desktops beside the VR Game itself in SteamVR GUI. Not sure if they were there before!? Anyone else having that issue? 

Tested in openxr and openvr, without latest windows updates, steamvr and steamvr beta

**Comment by MagellanOo** [comment]
Same issue here with RE7. I have 111ms. I tried to tweak graphic settings, without success. It's lagging to much to be playable.

Using VIVE Cosmos with OPENXR.
OS Win 11
RTX 4080
Intel i9-13900k

**Comment by Sawtooth76** [comment]
issue got solved

https://github.com/praydog/REFramework/discussions/932

**Comment by Sawtooth76** [comment]
I got it working with another runtime. Someone wrote a tool to switch it easily.
https://github.com/WaGi-Coding/OpenXR-Runtime-Switcher/releases/
