### ISSUE TITLE
Binary from AppVeyor unavailable

### ISSUE THREAD

**Issue by erwannevonia** [praydog/REFramework#93]
So I looked around a bit, and I couldn't find any way to put my hands on the dinput8.dll file. Like, when I go on the AppVeyor page, it just says "The build job does not contain any artifacts." via the link in the description on github, or when I try on the nexus page of the fps mod, the link says "Project not found or access denied."

Soo if anyone could help me, I would love it 👌 

Please ;-;

**Comment by praydog** [comment]
I will usually put mirrors up here: http://praydog.com/projects/
