### ISSUE TITLE
Request: Show coordinates of free camera

### ISSUE THREAD

**Issue by semyon422** [praydog/REFramework#94]
Hello! I am building Dimitrescu castle from RE8 in Minecraft. I am using a free camera mod from REFramework, and I found on the Internet a table for Cheat Engine, which shows the coordinates of the player. Could you make a display of the camera coordinates, so that I can more accurately determine the positions of objects on the map, to which I cannot walk but can fly. Thanks.

**Comment by praydog** [comment]
I'm busy with other stuff, so won't add this, sorry. There will be a scripting system in Lua soon, so you can print this yourself, among many other things.

However, if you want to do this with the current build:
Download a dev build here: https://ci.appveyor.com/project/praydog/reframework-dev
You can also compile this yourself with build_vs2019_devmode.bat

Click on Developer Tools->ObjectExplorer
Click on Native Singletons -> `via.SceneManager` -> Reflection Properties -> `MainView`
Click on `PrimaryCamera` -> 0x10: Owner -> 0x18: Transform -> `via.Transform`  -> `Position`

You should be able to see this (ignore the fact that it's RE3, it will work in RE8):
![re3_2021-11-27_11-03-16](https://user-images.githubusercontent.com/2909949/143719091-f326cd3d-aae0-412d-938f-e8d5516f9882.jpg)

**Comment by semyon422** [comment]
Thank you very much! It'll be enough!

**Comment by praydog** [comment]
Just getting back to you. Saw a lot of your projects were in Lua, so you might be interested in this.

Lua scripting (not LuaJIT) branch is available here now:
Source code: https://github.com/praydog/REFramework/tree/sdk-improvements-re7-mhr
Binaries: https://ci.appveyor.com/project/praydog/reframework-dev
Binaries mirror: http://praydog.com/projects/reframework-dev/2021_12_8%20scripting%201.0/

Scripting wiki: https://github.com/praydog/REFramework/wiki
