### ISSUE TITLE
Street Fighter 6: New Costume update broke Chat UI in the battlehub.

### ISSUE THREAD

**Issue by FallaYoDreams** [praydog/REFramework#945]
Players using REFramework after the new SF 6 update are unable to use the tool as it completely disables the Chat UI on the players end.   After numerous troubleshooting issues and collaborating with several other uses.  Renaming Dxinput8.dll fixed the problem but in turn disabled RE FRamework.   Chat did return after disabling though.   This would need investigating from a more smarter person than I.  I am just reporting the issue.

**Comment by praydog** [comment]
Fixed in 6a8221feac74a34138c2ad8c331c258b5ed7ab0d
