### ISSUE TITLE
Resident Evil 2: can't crouch when playing as Sherry

### ISSUE THREAD

**Issue by Lainier** [praydog/REFramework#951]
In Resident Evil 2, when playing as Sherry, I can't crouch by pressing LT on my Quest 3 controller.

REFramework revision: 6a8221feac74a34138c2ad8c331c258b5ed7ab0d
OS: Windows 10
GPU: RTX 4090
CPU: AMD Ryzen 7 5800x
Headset model: Meta Quest 3
Runtime: OpenXR
Additional context: When I remove the headset I can crouch by pressing the right mouse button.

**Comment by praydog** [comment]
Anything that says LT in-game is right grip.

**Comment by Lainier** [comment]
> Anything that says LT in-game is right grip.

OK, I'm just stupid ^_^
