### ISSUE TITLE
BV:Agent-AXJ[Trj] found in Enum_internal.hpp with Avast

### ISSUE THREAD

**Issue by aiartcreation** [praydog/REFramework#952]
**Describe the bug**
BV:Agent-AXJ[Trj] found in Enum_internal.hpp with Avast
Popped up in the most recent VR version of RE4. [v1.599-](https://github.com/praydog/REFramework-nightly/releases/tag/latest)

**To Reproduce**
Just ran the game in VR after installing the mod.

**Desktop and VR (please complete the following information):**
 Windows 10
 3080 TI
 AMD something....

**Virtual Reality (please complete the following information):**
 - Reverb 2
 - Runtime (OpenVR)

Hopefully someone can shed some light on this. Thanks!

**Comment by praydog** [comment]
This file is just a text file written to disk by REFramework for developers. It cannot be executed, plus it's a false positive.
