### ISSUE TITLE
The TemporalUpscaler did not appear

### ISSUE THREAD

**Issue by abaca43n** [praydog/REFramework#956]
The game is RE4 Remake. After placing the latest versions of the **dinput8.dll** file from the **pd-Upscaler branch** and **PDPerfPlugin.dll** file into the game's root directory, why doesn't REFramework display TemporalUpscaler in the game? Can someone tell me the correct installation method? Thank you very much.

**Comment by Silver812** [comment]
I think the Ada DLC completely broke the temporal upscaler functionality and it's been like that since then. I never got it to work either with the latest version of the game.

**Comment by praydog** [comment]
Use the pd-upscaler builds from the [Actions](https://github.com/praydog/REFramework/actions) page, they are compiled automatically.

**Comment by kamild1996** [comment]
Has something been broken about this again? I have dinput8.dll, PDPerfPlugin.dll and nvngx_dlss.dll in the same folder where re4.exe is and the TemporalUpscaler option does not show up. I used the latest nightly build of REFramework (https://github.com/praydog/REFramework-nightly/releases/tag/nightly-998-f2254d2cf45574f1385c189a559644c5c8d59a89) and I'm playing the Steam version of the game.
