### ISSUE TITLE
DLSS for RE4

### ISSUE THREAD

**Issue by Volklegator** [praydog/REFramework#964]
"Hello Praydog! Thank you for your work that you do for us gamers. To be inside our favorite games is probably what every game lover dreams about. I've played many RE releases with your projects, but after installing your mod on RE4, I can't get over the potato-level graphics, everything is very blurry and soapy, lacking that crispness, when you want to see clearly and have a sharp picture. I have an RTX 3090 graphics card, 64GB RAM. I've read a lot about how people used your DEV files to install DLSS libraries, and as a result, they got clearer images and an increase in FPS. Now, I can't find those files of yours anymore, and what I found doesn't work, RE4 won't start. I understand that you have very little time, but could you give me some advice on how to improve the picture quality in VR? I would be very grateful to you. Thank you very much. 

my email: volklegator@gmail.com

**Comment by Satan-friend** [comment]
By the way, please add motion control too :)

**Comment by praydog** [comment]
https://github.com/praydog/REFramework/actions

Download `pd-upscaler` builds. Necessary instructions for RE4 upscaler installation and dependency downloads are on its NexusMods page.
