### ISSUE TITLE
RE4 remake: Character heads and some objects do not update position in the right eye

### ISSUE THREAD

**Issue by REEEEE-B00T** [praydog/REFramework#966]
**Describe the bug**
Occasionally, character heads - Leon, Ashley, Luis, Certain Boss NPC's will not render in the right eye.
Sometimes you can see the head mesh appear stuck, floating where a character was.
When closing the left eye, the characters face is invisible, but their hair and body is still there.

On occasion this will happen to objects in both eyes:
Leon's gun when he meets Ada in the castle.
Luis' cigarettes and lighter during his death scene.

**Log**
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/13801683/re2_framework_log.txt)

**Identify the REFramework version**
1.5.2 Release

**To Reproduce**
As far as I can tell, just play in vr on the index

**Expected behavior**
Both eyes see the same image, and object positions are updated during draw calls

**Screenshots**
![render_error](https://github.com/praydog/REFramework/assets/36616572/bf9d9901-735c-4060-84cd-52099d9ceba8)
![render_error_distance_okay](https://github.com/praydog/REFramework/assets/36616572/f7c0a0f5-9fb3-4a63-8bda-7e87ebba1da0)
![render_error_distance_reoccurr](https://github.com/praydog/REFramework/assets/36616572/3f6abc05-6620-432b-85c8-ec23e90a8e4e)
![render_error2](https://github.com/praydog/REFramework/assets/36616572/f8b402bf-3224-4f8b-9f65-e694f2a96320)

**Desktop and VR (please complete the following information):**
Steam VR 2.2.3
Windows 10
Nvidia 3080 FE
AMD Ryzen 9 5900x

Virtual Reality
Valve Index
SteamVR (OpenVR)

**Additional context**
Other than cutscenes, It seems to happen most frequently at the beginning of chapters.
Sometimes, it can "catch up" or only reoccur when a certain distance away from the NPC.

**Comment by praydog** [comment]
Not an issue in the `pd-upscaler` branch

Download it here: https://github.com/praydog/REFramework/actions

**Comment by REEEEE-B00T** [comment]
@praydog It's worth noting, that even with that branch, objects still disappear. Though it does solve the character mesh problem. 
Ada in separate ways cutscenes constantly loses her lower body. Thank you for this mod and for your assistance.
