### ISSUE TITLE
MHRise launched, but HMD screen only shows steamvr background

### ISSUE THREAD

**Issue by KrisCris** [praydog/REFramework#97]

**Comment by praydog** [comment]
Are you using an HDR screen? Can you post the `re2_framework_log.txt` that's in your game folder?

**Comment by KrisCris** [comment]
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/7797448/re2_framework_log.txt)

**Comment by KrisCris** [comment]
ok, I somehow managed to launch the game and see it in my HMD, but it looks a bit weird...

![image](https://user-images.githubusercontent.com/38860226/147846202-4b4e5ade-3b72-4d59-be7e-4864b12a3ca2.png)

**Comment by praydog** [comment]
Can you try closing SteamVR, open MHRise *without* your headset on, and then put it on after the mod fully initializes?

**Comment by praydog** [comment]
Ok, ignore what I said there since you got it working. Turn off Borderless mode.

**Comment by KrisCris** [comment]
> Ok, ignore what I said there since you got it working. Turn off Borderless mode.

So which mode should I use, maybe fullscreen?

**Comment by KrisCris** [comment]
thanks, i fixed it :)

**Comment by KrisCris** [comment]
sorry for the off-topic question - it is possible to make the game first-person?

**Comment by praydog** [comment]
It is *possible*, but it's only currently implemented in RE2 and RE3.
