### ISSUE TITLE
RE4 does not work

### ISSUE THREAD

**Issue by DawidDe** [praydog/REFramework#971]
**Describe the bug**
A clear and concise description of what the bug is. If the bug only started to happen after a certain REFramework update, let us know which version the bug appeared in:

I wanted to test Resident Evil 4 on my Quest 3, but I didn't want to pay $20 only to find out it doesn't work. So, I installed the demo and then the REFramework. I simply copied the files from the re4.zip into my game directory (D:\Program Files (x86)\Steam\steamapps\common\RESIDENT EVIL 4 BIOHAZARD RE4 Chainsaw Demo). However, when I start the demo, nothing happens, and Steam indicates that it's running. Once I delete the added files, everything works fine again. I've attempted both the stable and nightly builds. I've seen YouTubers using the mod with the demo version. Thank you for any assistance.

**Upload logs and any crash dumps**
Locate the `re2_framework_log.txt` in your game directory and upload it along with the issue.
If you crashed, upload the `reframework_crash.dmp` file as well:

there was no log

**Identify the REFramework version**
If the REFramework version or commit hash is known, submit this information:

v1.601

**To Reproduce**
1. download latest nightly build of REFramework (re4.zip).
2. copy re4.zip to steam game directory.
3. extract all files in folder
4. delete re4.zip
5. start game

**Expected behavior**
A clear and concise description of what you expected to happen:
the game just dont start.

**Screenshots**

**Desktop and VR (please complete the following information):**
 - OS: Windows 11
 - Graphic Card: AMD Radeon RX 6600 XT
 - CPU: AMD Ryzen 5 5600X
 
**Virtual Reality (please complete the following information):**
 - Headset model: Meta Quest 3
 - Runtime: OpenXR

**Additional context**

**Comment by praydog** [comment]
Demo version is not going to be supported at this time. It did when it came out, but I had to make some changes to make it work on the full version which may have broken the demo.
