### ISSUE TITLE
Meta Quest 3 full screen issue

### ISSUE THREAD

**Issue by d3viluz** [praydog/REFramework#978]
First of all thank you for adding this mod!

I seem to experience some fullscreen issues when I tried this on my Quest 3.
I thought I did everything by the book, enabling first person view and such but somehow  when I start a new game it shows first person view but it's all windowed and not full screen. Like I'm sitting in a theatre. Will appreciate all the assistance I can get 🙏

**Comment by outtaweirdo** [comment]
Same issue
