### ISSUE TITLE
what version do i download to get dlss upscaler to work? RE2 & RE8

### ISSUE THREAD

**Issue by ShiggyComp** [praydog/REFramework#990]
RE4 was pretty easy to set up but the file was from nexus mod. I downloaded the latest version for re8 and the upscaler tab doesnt show up? Is there a different version that works? Im sorry if i made a useless post, im new to this

**Comment by praydog** [comment]
https://github.com/praydog/REFramework/actions

builds with `pd-upscaler` next to them

**Comment by ShiggyComp** [comment]
Sorry but i still dont know im looking at.
