### ISSUE TITLE
REFix plugin won't load

### ISSUE THREAD

**Issue by StarSpeak** [praydog/REFramework#993]
For some unknown reason, REFramework refuses to load the REFix.dll plugin file.  I am using REFix version 0.5.1-b1 (https://github.com/TheTedder/REFix/releases/tag/v0.5.1-beta.1) in combination with REFramework version 1.5.2 and 1.5.3; none work, and all have the same error message. There is an error with REFramework's plugin_initialize process:

>  [REFramework] [error] [PluginLoader] REFix has an exception in reframework_plugin_initialize, skipping...

I reinstalled windows, updated it via windows update, disabled any AV/windows defender/etc, installed all system/device drivers, and then re-installed the game, and the error still occurred.

System info:
Win10 Pro x64 build 19045
MSI GeForce 3070
Intel Core i7 965

Attachments:

Log
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/14300272/re2_framework_log.txt)

Screenshot
![reframework - plugin error](https://github.com/praydog/REFramework/assets/160161379/2c9bb68d-14f1-4cef-8e98-cb56cedce985)

**Comment by praydog** [comment]
Make an issue on his repo.
