### ISSUE TITLE
RE4 Remake Crashing

### ISSUE THREAD

**Issue by Cacheadov123** [praydog/REFramework#994]
When i try using REframework on RE4 Remake it doesn't work, like, the game loads normally but after 5-10 seconds of opening it, it shows the REframework menu, but it doesn't finish loading, and then the game crashes,
![image](https://github.com/praydog/REFramework/assets/160420439/e1e74802-59f5-41d2-8995-7fed94666f2c)
[re2_framework_log.txt](https://github.com/praydog/REFramework/files/14323642/re2_framework_log.txt)

**Comment by Cacheadov123** [comment]
https://streamable.com/kqzl0a
This is what happens

**Comment by praydog** [comment]
Pirated copies are not supported.
