### ISSUE TITLE
Right lens didn't show the body

### ISSUE THREAD

**Issue by Gulivert** [praydog/REFramework#998]
**Describe the bug**
In Resident Evil 2 Mod, using oculus quest 2, the full body of the character only show up in my left lens, in the right i only can see the head floating. In First Person view, i cannot see the hand neither with the right lens.

In the cinematic scenes looks without problems

**Upload logs and any crash dumps**
File wasn't generated in the folder's game

**Identify the REFramework version**
https://github.com/praydog/REFramework-nightly/releases

**To Reproduce**
1. Start the game

**Expected behavior**
See the full body

**Screenshots**

**Desktop and VR (please complete the following information):**
 - Windows 11
 - Rtk 3070 ti
 - Ryzen 5

**Steam Deck/Linux (please complete the following information):**
 - Proton version

**Virtual Reality (please complete the following information):**
 - Headset model
 - Runtime (OpenVR or OpenXR)

**Additional context**

**Comment by praydog** [comment]
Duplicate issue #400 

Already fixed in WIP `pd-upscaler` branch. You can download them from the [Actions](https://github.com/praydog/REFramework/actions) page, look for `pd-upscaler` next to the releases, and download the relevant RE2.zip artifact.
